import {applyStatStagesHandler} from './apply-stat-stages.mjs';
import {checkAccuracyHandler} from './check-accuracy.mjs';
import {applyMajorStatusHandler} from './apply-major-status.mjs';
import {applyVolatileStatusHandler} from './apply-volatile-status.mjs';
import {directDamageHandler} from './direct-damage.mjs';
import {spendPpHandler} from './spend-pp.mjs';
import {multiHitDamageHandler} from './multi-hit-damage.mjs';
import {applyRecoilHandler} from './apply-recoil.mjs';
import {applyDrainHandler} from './apply-drain.mjs';
import {fixedDamageHandler} from './fixed-damage.mjs';
import {variablePowerDamageHandler} from './variable-power-damage.mjs';
import {applyProtectionHandler} from './apply-protection.mjs';
import {applySideProtectionHandler} from './apply-side-protection.mjs';
import {breakProtectionHandler} from './break-protection.mjs';
import {applyRedirectionHandler} from './apply-redirection.mjs';
import {applyPivotSwitchHandler} from './apply-pivot-switch.mjs';
import {applyForcedSwitchHandler} from './apply-forced-switch.mjs';
import {applyPositionSwapHandler} from './apply-position-swap.mjs';
import {heldDamageBoostHandler,lowHpTypeBoostHandler,receivedTypeDamageReductionHandler} from './passive-damage-modifiers.mjs';
import {megaStoneHandler} from './mega-stone.mjs';
import {applyWeatherHandler} from './apply-weather.mjs';
import {weatherDurationHandler,weatherHealHandler,weatherSpeedHandler} from './passive-weather.mjs';
import {applySideConditionHandler} from './apply-side-condition.mjs';
import {screenDurationHandler} from './passive-side-conditions.mjs';

export const HANDLER_DEFINITIONS=[spendPpHandler,breakProtectionHandler,checkAccuracyHandler,directDamageHandler,multiHitDamageHandler,fixedDamageHandler,variablePowerDamageHandler,applyStatStagesHandler,applyMajorStatusHandler,applyVolatileStatusHandler,applyProtectionHandler,applySideProtectionHandler,applyRedirectionHandler,applyPivotSwitchHandler,applyForcedSwitchHandler,applyPositionSwapHandler,applyWeatherHandler,applySideConditionHandler,lowHpTypeBoostHandler,heldDamageBoostHandler,receivedTypeDamageReductionHandler,weatherSpeedHandler,weatherDurationHandler,weatherHealHandler,screenDurationHandler,megaStoneHandler,applyRecoilHandler,applyDrainHandler];
