import {randomBytes,randomUUID} from 'node:crypto';
import {replacementRequirements,validateReplacements} from '../rules-v3/index.mjs';
import {createV3PvpBattle,publicV3Preview} from './v3-battle-factory.mjs';
import {pvpBattleView,resolvePvpCommands,resolvePvpReplacements} from './pvp-battle-runtime.mjs';
import {normalizeCommands} from './v3-battle-actions.mjs';
import {validateV3Team} from './v3-progression.mjs';
import {recordMissionEvent} from './missions.mjs';
import {protectRankedLoss} from './rank-ticket-settlement.mjs';
import {rankedTier as tierName,rankedTierView} from './ranked-tiers.mjs';
import {PVP_TIMERS,chooseTimeoutCommands,chooseTimeoutReplacements,firstPreviewPicks,markParticipantConnected,markParticipantDisconnected,markPvpActivity,participantDisconnectExpired,pvpTimingView,syncPvpDecisionClock} from './pvp-lifecycle.mjs';

const clone=value=>structuredClone(value),other=side=>side==='A'?'B':'A',SEASON_ID='2026-S1',RATING_VERSION='elo-v1-k32';
const seed32=()=>randomBytes(4).readUInt32LE(0),finiteInt=(value,fallback=0)=>Number.isFinite(Number(value))?Math.trunc(Number(value)):fallback;
export const rankedTier=rating=>tierName(rating);
export function ensureRankedState(state){
 if(!state||typeof state!=='object')return false;let changed=false;if(!state.rankedV1||typeof state.rankedV1!=='object'){state.rankedV1={};changed=true;}
 const ranked=state.rankedV1,defaults={schemaVersion:1,seasonId:SEASON_ID,ratingVersion:RATING_VERSION,rating:1000,peakRating:1000,matches:0,wins:0,losses:0,draws:0,lastDelta:0,lastMatchAt:null,history:[]};
 for(const [key,value] of Object.entries(defaults))if(ranked[key]===undefined){ranked[key]=clone(value);changed=true;}
 if(ranked.seasonId!==SEASON_ID){ranked.seasonId=SEASON_ID;ranked.rating=1000;ranked.peakRating=Math.max(finiteInt(ranked.peakRating,1000),1000);ranked.matches=0;ranked.wins=0;ranked.losses=0;ranked.draws=0;ranked.lastDelta=0;ranked.history=[];changed=true;}
 ranked.rating=Math.max(0,finiteInt(ranked.rating,1000));ranked.peakRating=Math.max(ranked.rating,finiteInt(ranked.peakRating,ranked.rating));ranked.matches=Math.max(0,finiteInt(ranked.matches));ranked.wins=Math.max(0,finiteInt(ranked.wins));ranked.losses=Math.max(0,finiteInt(ranked.losses));ranked.draws=Math.max(0,finiteInt(ranked.draws));if(!Array.isArray(ranked.history)){ranked.history=[];changed=true;}return changed;
}
export function rankedProfileView(state){ensureRankedState(state);const ranked=state.rankedV1;return {seasonId:ranked.seasonId,ratingVersion:ranked.ratingVersion,rating:ranked.rating,peakRating:ranked.peakRating,...rankedTierView(ranked.rating),matches:ranked.matches,wins:ranked.wins,losses:ranked.losses,draws:ranked.draws,lastDelta:ranked.lastDelta,lastMatchAt:ranked.lastMatchAt,history:clone(ranked.history.slice(0,10))};}
function expected(a,b){return 1/(1+10**((b-a)/400));}
export function rankedRatingDelta(ratingA,ratingB,scoreA,k=32){const delta=Math.round(k*(scoreA-expected(ratingA,ratingB)));return {A:delta,B:delta===0?0:-delta};}
function settleProfile(state,{matchId,opponentName,opponentRating,score,delta,now,mode,protected:shielded=false}){ensureRankedState(state);const ranked=state.rankedV1;if(ranked.history.some(entry=>entry.matchId===matchId))return false;ranked.rating=Math.max(0,ranked.rating+delta);ranked.peakRating=Math.max(ranked.peakRating,ranked.rating);ranked.matches++;if(score===1)ranked.wins++;else if(score===0)ranked.losses++;else ranked.draws++;ranked.lastDelta=delta;ranked.lastMatchAt=now;ranked.history.unshift({matchId,mode,opponentName:String(opponentName||'Trainer').slice(0,80),opponentRating,result:score===1?'win':score===0?'loss':'draw',delta,...(shielded?{rankTicketProtected:true}:{}),ratingAfter:ranked.rating,playedAt:now});ranked.history=ranked.history.slice(0,20);recordMissionEvent(state,'battles',1,now);if(score===1)recordMissionEvent(state,'wins',1,now);return true;}
function previewRoster(state,catalog,teamId){const progression=state.progressionV3,team=progression?.teams?.find(entry=>entry.teamId===(teamId||progression.activeTeamId||progression.teams[0]?.teamId));if(!team)return {ok:false,code:'TEAM_NOT_FOUND'};const problems=validateV3Team(team,progression,catalog);if(problems.length)return {ok:false,code:'TEAM_ILLEGAL',details:problems};return {ok:true,team,roster:publicV3Preview(team,progression,catalog)};}
function participantView(participant){return {name:participant.name,rating:participant.rating,...rankedTierView(participant.rating),connected:participant.connected!==false,reconnectDeadlineAt:participant.connected===false?participant.disconnectDeadlineAt||null:null};}
function waitingWindow(ticket,now){return Math.min(700,250+Math.floor(Math.max(0,now-ticket.joinedAt)/15000)*50);}
function queueCompatible(a,b,now){return a.mode===b.mode&&a.regulationId===b.regulationId&&a.catalogVersion===b.catalogVersion&&a.rulesVersion===b.rulesVersion&&Math.abs(a.rating-b.rating)<=Math.max(waitingWindow(a,now),waitingWindow(b,now));}

export class RankedService{
 constructor({catalog,clock={now:()=>Date.now()},getState,persist=async()=>{},notify=()=>{}}){this.catalog=catalog;this.clock=clock;this.getState=getState;this.persist=persist;this.notify=notify;this.queue=[];this.matches=new Map();this.playerMatch=new Map();this.presence=new Map();}
 register(accountId,session){const now=this.clock.now(),current=this.presence.get(accountId)||{};this.presence.set(accountId,{...current,session,connected:true});const match=this.matches.get(this.playerMatch.get(accountId));if(match&&!match.settled){const side=this.sideFor(match,accountId);markParticipantConnected(match.participants[side],now);markPvpActivity(match,now);this.notify([match.participants[other(side)].accountId]);}}
 unregister(accountId){const now=this.clock.now(),current=this.presence.get(accountId);if(current)this.presence.set(accountId,{...current,connected:false});const index=this.queue.findIndex(entry=>entry.accountId===accountId);if(index>=0)this.queue.splice(index,1);const match=this.matches.get(this.playerMatch.get(accountId));if(match&&!match.settled){const side=this.sideFor(match,accountId);markParticipantDisconnected(match.participants[side],now);this.notify([match.participants[other(side)].accountId]);}}
 sideFor(match,accountId){return match.participants.A.accountId===accountId?'A':match.participants.B.accountId===accountId?'B':null;}
 busy(accountId){return this.queue.some(entry=>entry.accountId===accountId)||this.playerMatch.has(accountId);}
 viewFor(accountId,state){
  ensureRankedState(state);const profile=rankedProfileView(state),session=this.presence.get(accountId)?.session,eligible=['google','discord'].includes(session?.provider),match=this.matches.get(this.playerMatch.get(accountId)),now=this.clock.now();
  if(match){const side=this.sideFor(match,accountId),foe=match.participants[other(side)],won=match.settled?(match.battle?.result?.winner||match.forfeitWinner||null):null,battleV3=pvpBattleView(match,side,{kind:'ranked',difficulty:'ranked',participantView,rating:true});if(battleV3)battleV3.timing=pvpTimingView(match,side,now);return {schemaVersion:1,status:match.settled?'finished':match.battle?'battle':'preview',eligible,profile,match:{id:match.id,mode:match.mode,createdAt:match.createdAt,opponent:participantView(foe)},battleV3,...(match.settled?{result:{outcome:won===side?'win':won?'loss':'draw',reason:match.battle?.result?.reason||match.forfeitReason||'completed',ratingDelta:match.ratingDelta?.[side]??0,ratingAfter:match.ratingAfter?.[side]??profile.rating,rankTicketProtected:!!match.rankTicketProtected?.[side]}}:{})};}
  const ticket=this.queue.find(entry=>entry.accountId===accountId);if(ticket)return {schemaVersion:1,status:'queued',eligible,profile,queue:{ticketId:ticket.ticketId,mode:ticket.mode,joinedAt:ticket.joinedAt,position:this.queue.filter(entry=>entry.mode===ticket.mode).indexOf(ticket)+1,ratingWindow:waitingWindow(ticket,now)}};return {schemaVersion:1,status:'idle',eligible,profile};
 }
 async action(accountId,session,action){
  const state=this.getState(accountId);if(!state)return {ok:false,code:'ACCOUNT_STATE_UNAVAILABLE'};ensureRankedState(state);const now=this.clock.now(),type=action?.type;
  if(type==='rankedV1.queue.join'){if(!['google','discord'].includes(session?.provider))return {ok:false,code:'RANKED_ACCOUNT_REQUIRED'};if(this.busy(accountId))return {ok:false,code:'RANKED_ALREADY_ACTIVE'};if(state.battleV3&&state.battleV3.phase!=='FINISHED')return {ok:false,code:'BATTLE_ALREADY_ACTIVE'};if(!['single','double'].includes(action.mode))return {ok:false,code:'INVALID_FORMAT'};const preview=previewRoster(state,this.catalog,action.teamId);if(!preview.ok)return preview;const ticket={ticketId:randomUUID(),accountId,mode:action.mode,joinedAt:now,rating:state.rankedV1.rating,teamId:preview.team.teamId,teamBuildIds:[...preview.team.buildIds],roster:preview.roster,name:session?.name||'Vanguard Trainer',regulationId:this.catalog.regulations[0].id,catalogVersion:this.catalog.metadata.catalogVersion,rulesVersion:this.catalog.metadata.rulesVersion};this.queue.push(ticket);const matched=this.tryMatch(ticket);this.notify(matched?[matched.participants.A.accountId,matched.participants.B.accountId]:[accountId]);return {ok:true};}
  if(type==='rankedV1.queue.leave'){const index=this.queue.findIndex(entry=>entry.accountId===accountId);if(index<0)return {ok:false,code:'NOT_IN_RANKED_QUEUE'};this.queue.splice(index,1);this.notify([accountId]);return {ok:true};}
  const match=this.matches.get(this.playerMatch.get(accountId));if(!match)return {ok:false,code:'NO_RANKED_MATCH'};const side=this.sideFor(match,accountId),foeSide=other(side),participant=match.participants[side],revision=match.battle?.phaseRevision;if(participantDisconnectExpired(participant,now))return {ok:false,code:'DISCONNECT_TIMEOUT'};syncPvpDecisionClock(match,now);
  const actionId=String(action.actionId||'');if(actionId&&match.actionReceipts.includes(`${accountId}:${actionId}`)){this.notify([accountId]);return {ok:true,duplicate:true};}
  if(type==='rankedV1.preview.lock'){if(match.battle||match.settled)return {ok:false,code:'WRONG_PHASE'};const p=participant,pick=this.catalog.regulations[0].pick[match.mode];if(!Array.isArray(action.buildIds)||action.buildIds.length!==pick||new Set(action.buildIds).size!==pick||action.buildIds.some(id=>!p.teamBuildIds.includes(id)))return {ok:false,code:'INVALID_PREVIEW_SELECTION'};p.lockedBuildIds=[...action.buildIds];this.startBattleIfReady(match);}
  else if(type==='rankedV1.commands'){if(match.settled||match.battle?.phase!=='COMMAND'||action.phaseRevision!==revision)return {ok:false,code:'STALE_PHASE'};const validated=normalizeCommands(match.battle,side,action.commands,this.catalog);if(!validated.ok)return validated;match.pending.commands[revision]??={};match.pending.commands[revision][side]=clone(action.commands);const resolved=resolvePvpCommands(match,this.catalog);if(!resolved.ok)return resolved;}
  else if(type==='rankedV1.replacements'){if(match.settled||match.battle?.phase!=='REPLACE'||action.phaseRevision!==revision)return {ok:false,code:'STALE_PHASE'};const required=replacementRequirements(match.battle,side);if(!required.slots.length)return {ok:false,code:'NO_REPLACEMENT_REQUIRED'};const validated=validateReplacements(match.battle,side,action.replacements);if(!validated.ok)return validated;match.pending.replacements[revision]??={};match.pending.replacements[revision][side]=clone(action.replacements);const resolved=resolvePvpReplacements(match,this.catalog);if(!resolved.ok)return resolved;}
  else if(type==='rankedV1.surrender'){if(match.settled)return {ok:false,code:'WRONG_PHASE'};await this.finishForfeit(match,side,match.battle?'surrender':'preview-forfeit');}
  else if(type==='rankedV1.dismiss'){if(!match.settled)return {ok:false,code:'MATCH_NOT_FINISHED'};this.playerMatch.delete(accountId);match.dismissed.add(accountId);if(match.dismissed.size===2)this.matches.delete(match.id);this.notify([accountId]);return {ok:true};}
  else return {ok:false,code:'UNKNOWN_RANKED_ACTION'};
  markPvpActivity(match,now);syncPvpDecisionClock(match,now);if(actionId)match.actionReceipts.push(`${accountId}:${actionId}`);match.actionReceipts=match.actionReceipts.slice(-200);if(match.battle?.phase==='FINISHED'&&!match.settled)await this.settle(match);this.notify([match.participants.A.accountId,match.participants.B.accountId]);return {ok:true};
 }
 startBattleIfReady(match){if(match.battle||!match.participants.A.lockedBuildIds||!match.participants.B.lockedBuildIds)return false;const aState=this.getState(match.participants.A.accountId),bState=this.getState(match.participants.B.accountId);match.battle=createV3PvpBattle({id:match.id,mode:match.mode,seed:match.seed,buildIdsA:match.participants.A.lockedBuildIds,progressionA:aState.progressionV3,buildIdsB:match.participants.B.lockedBuildIds,progressionB:bState.progressionV3,catalog:this.catalog});match.lastEvents=clone(match.battle.events);return true;}
 adminOverview(){const queue=this.queue.map(entry=>({kind:'ranked-queue',id:entry.ticketId,accountId:entry.accountId,name:entry.name,mode:entry.mode,rating:entry.rating,joinedAt:entry.joinedAt})),matches=[...this.matches.values()].filter(match=>!match.settled).map(match=>({kind:'ranked-match',id:match.id,mode:match.mode,status:match.battle?match.battle.phase:'PREVIEW',createdAt:match.createdAt,decisionDeadlineAt:match.decisionClock?.deadlineAt||null,players:[match.participants.A,match.participants.B].map(p=>({accountId:p.accountId,name:p.name,rating:p.rating,connected:p.connected!==false,reconnectDeadlineAt:p.disconnectDeadlineAt||null}))}));return {queue,matches};}
 async adminStopForPlayer(accountId,reason='admin-stop'){const queueIndex=this.queue.findIndex(entry=>entry.accountId===accountId);if(queueIndex>=0){const [ticket]=this.queue.splice(queueIndex,1);this.notify([accountId]);return {ok:true,kind:'ranked-queue',id:ticket.ticketId,accounts:[accountId]};}const match=this.matches.get(this.playerMatch.get(accountId));if(!match||match.settled)return {ok:false,code:'NO_RANKED_ACTIVITY'};await this.finishNoContest(match,reason);const accounts=[match.participants.A.accountId,match.participants.B.accountId];this.notify(accounts);return {ok:true,kind:'ranked-match',id:match.id,accounts};}
 tryMatch(ticket){const now=this.clock.now(),candidates=this.queue.filter(entry=>entry.accountId!==ticket.accountId&&queueCompatible(ticket,entry,now)).sort((a,b)=>Math.abs(a.rating-ticket.rating)-Math.abs(b.rating-ticket.rating)||a.joinedAt-b.joinedAt),opponent=candidates[0];if(!opponent)return null;this.queue=this.queue.filter(entry=>entry!==ticket&&entry!==opponent);const ordered=ticket.joinedAt<=opponent.joinedAt?[ticket,opponent]:[opponent,ticket],participant=entry=>({...entry,connected:this.presence.get(entry.accountId)?.connected!==false,lockedBuildIds:null,disconnectedAt:null,disconnectDeadlineAt:null,disconnectExpired:false}),match={id:`ranked-${randomUUID()}`,mode:ticket.mode,seed:seed32(),createdAt:now,updatedAt:now,lastActivityAt:now,participants:{A:participant(ordered[0]),B:participant(ordered[1])},battle:null,pending:{commands:{},replacements:{}},lastEvents:[],lastTurnRaw:null,actionReceipts:[],settled:false,ratingDelta:null,ratingAfter:null,dismissed:new Set(),decisionClock:null};syncPvpDecisionClock(match,now);this.matches.set(match.id,match);this.playerMatch.set(ordered[0].accountId,match.id);this.playerMatch.set(ordered[1].accountId,match.id);return match;}
 async finishForfeit(match,loserSide,reason){const winner=other(loserSide);if(match.battle){const battle=clone(match.battle);battle.phase='FINISHED';battle.phaseRevision++;battle.result={winner,reason,turn:battle.turn,receiptId:`${battle.id}:ranked-${reason}:${loserSide}`};match.battle=battle;match.lastEvents=[{kind:'battleEnded',winner,reason}];}else{match.forfeitWinner=winner;match.forfeitReason=reason;}await this.settle(match);}
 async finishNoContest(match,reason){if(match.settled)return;if(match.battle){const battle=clone(match.battle);battle.phase='FINISHED';battle.phaseRevision=(battle.phaseRevision||0)+1;battle.result={winner:null,reason,turn:battle.turn||0,receiptId:`${battle.id}:${reason}`};match.battle=battle;match.lastEvents=[{kind:'battleEnded',winner:null,reason}];}else{match.forfeitWinner=null;match.forfeitReason=reason;}match.ratingDelta={A:0,B:0};match.ratingAfter={A:this.getState(match.participants.A.accountId)?.rankedV1?.rating??match.participants.A.rating,B:this.getState(match.participants.B.accountId)?.rankedV1?.rating??match.participants.B.rating};match.settled=true;match.settledAt=this.clock.now();match.decisionClock=null;}
 async settle(match){if(match.settled)return;const winner=match.battle?.result?.winner||match.forfeitWinner||null,a=match.participants.A,b=match.participants.B,aState=this.getState(a.accountId),bState=this.getState(b.accountId);if(!aState||!bState)throw new Error('Ranked settlement state unavailable');ensureRankedState(aState);ensureRankedState(bState);const scoreA=winner==='A'?1:winner==='B'?0:.5,delta=rankedRatingDelta(aState.rankedV1.rating,bState.rankedV1.rating,scoreA),now=this.clock.now(),aBefore=aState.rankedV1.rating,bBefore=bState.rankedV1.rating;
 const shieldA=protectRankedLoss(aState,match.id,delta.A),shieldB=protectRankedLoss(bState,match.id,delta.B);
 settleProfile(aState,{matchId:match.id,opponentName:b.name,opponentRating:bBefore,score:scoreA,delta:shieldA.delta,now,mode:match.mode,protected:shieldA.protected});
 settleProfile(bState,{matchId:match.id,opponentName:a.name,opponentRating:aBefore,score:1-scoreA,delta:shieldB.delta,now,mode:match.mode,protected:shieldB.protected});
 match.rankTicketProtected={A:shieldA.protected,B:shieldB.protected};match.ratingDelta={A:shieldA.delta,B:shieldB.delta};match.ratingAfter={A:aState.rankedV1.rating,B:bState.rankedV1.rating};match.settled=true;match.settledAt=now;match.decisionClock=null;await Promise.all([this.persist(a.accountId,aState),this.persist(b.accountId,bState)]);}
 cleanupMatch(match){for(const p of [match.participants.A,match.participants.B])if(this.playerMatch.get(p.accountId)===match.id)this.playerMatch.delete(p.accountId);this.matches.delete(match.id);}
 async applyDecisionTimeout(match,now){const decision=syncPvpDecisionClock(match,now);if(!decision||now<decision.deadlineAt||match.settled)return false;const sides=['A','B'];
  if(decision.kind==='preview'){const pick=this.catalog.regulations[0].pick[match.mode];for(const side of sides)if(!match.participants[side].lockedBuildIds)match.participants[side].lockedBuildIds=firstPreviewPicks(match,side,pick);this.startBattleIfReady(match);}
  else if(decision.kind==='command'){const revision=match.battle.phaseRevision;match.pending.commands[revision]??={};for(const side of sides)if(!match.pending.commands[revision][side]){const commands=chooseTimeoutCommands(match.battle,this.catalog,side);if(!commands){await this.finishNoContest(match,'action-timeout-no-legal-action');return true;}match.pending.commands[revision][side]=commands;}const resolved=resolvePvpCommands(match,this.catalog);if(!resolved.ok){await this.finishNoContest(match,'action-timeout-resolution-error');return true;}}
  else if(decision.kind==='replacement'){const revision=match.battle.phaseRevision;match.pending.replacements[revision]??={};for(const side of sides){const required=replacementRequirements(match.battle,side);if(required.slots.length&&!match.pending.replacements[revision][side])match.pending.replacements[revision][side]=chooseTimeoutReplacements(match.battle,side);}const resolved=resolvePvpReplacements(match,this.catalog);if(!resolved.ok){await this.finishNoContest(match,'replacement-timeout-resolution-error');return true;}}
  markPvpActivity(match,now);match.lastAutoAction={kind:decision.kind,at:now};syncPvpDecisionClock(match,now);if(match.battle?.phase==='FINISHED'&&!match.settled)await this.settle(match);this.notify([match.participants.A.accountId,match.participants.B.accountId]);return true;
 }
 async tick(){const now=this.clock.now();for(const match of [...this.matches.values()]){if(match.settled){if(now-(match.settledAt||now)>=PVP_TIMERS.resultRetentionMs){const accounts=[match.participants.A.accountId,match.participants.B.accountId];this.cleanupMatch(match);this.notify(accounts);}continue;}const expired=['A','B'].filter(side=>participantDisconnectExpired(match.participants[side],now));if(expired.length===2){await this.finishNoContest(match,'both-disconnected');this.notify([match.participants.A.accountId,match.participants.B.accountId]);continue;}if(expired.length===1){const foe=match.participants[other(expired[0])];if(foe.connected!==false){await this.finishForfeit(match,expired[0],'disconnect-timeout');this.notify([match.participants.A.accountId,match.participants.B.accountId]);continue;}}
   if(now-(match.lastActivityAt||match.createdAt)>=PVP_TIMERS.hardIdleMs){await this.finishNoContest(match,'match-expired');this.notify([match.participants.A.accountId,match.participants.B.accountId]);continue;}await this.applyDecisionTimeout(match,now);}}
}
