import {randomUUID} from 'node:crypto';
const clone=value=>structuredClone(value),UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const trimName=value=>String(value||'Vanguard Trainer').replace(/[\u0000-\u001f\u007f]/g,'').slice(0,80)||'Vanguard Trainer';
export function friendCodeFor(accountId){if(!UUID.test(accountId||''))return null;const hex=accountId.replaceAll('-','').toUpperCase();return `PV-${hex.slice(0,8)}-${hex.slice(8,16)}-${hex.slice(16,24)}-${hex.slice(24)}`;}
export function accountIdFromFriendCode(code){const hex=String(code||'').trim().toUpperCase().replace(/^PV-/,'').replaceAll('-','');if(!/^[0-9A-F]{32}$/.test(hex))return null;const lower=hex.toLowerCase(),uuid=`${lower.slice(0,8)}-${lower.slice(8,12)}-${lower.slice(12,16)}-${lower.slice(16,20)}-${lower.slice(20)}`;return UUID.test(uuid)?uuid:null;}
export function ensureSocialState(state){if(!state.socialV1||typeof state.socialV1!=='object')state.socialV1={};const s=state.socialV1;s.schemaVersion=1;if(!Array.isArray(s.friends))s.friends=[];if(!Array.isArray(s.incomingRequests))s.incomingRequests=[];if(!Array.isArray(s.outgoingRequests))s.outgoingRequests=[];if(!s.conversations||typeof s.conversations!=='object'||Array.isArray(s.conversations))s.conversations={};return s;}
const friendOf=(state,id)=>ensureSocialState(state).friends.find(entry=>entry.accountId===id);
export class SocialService{
 constructor({clock={now:()=>Date.now()},getState=()=>null,loadState=async()=>null,persist=async()=>{},setLiveState=()=>{},notify=()=>{}}={}){this.clock=clock;this.getState=getState;this.loadState=loadState;this.persist=persist;this.setLiveState=setLiveState;this.notify=notify;this.presence=new Map();this.lastMessageAt=new Map();}
 register(accountId,session){this.presence.set(accountId,{session,connected:true});}
 unregister(accountId){const p=this.presence.get(accountId);if(p)this.presence.set(accountId,{...p,connected:false});}
 isFriend(a,b){const state=this.getState(a);return !!state&&!!friendOf(state,b);}
 async stateFor(id){return this.getState(id)||await this.loadState(id);}
 viewFor(accountId,state){const social=ensureSocialState(state),online=id=>this.presence.get(id)?.connected===true;return {schemaVersion:1,eligible:UUID.test(accountId||''),friendCode:friendCodeFor(accountId),friends:social.friends.map(entry=>({...clone(entry),online:online(entry.accountId)})),incomingRequests:clone(social.incomingRequests),outgoingRequests:clone(social.outgoingRequests),conversations:Object.fromEntries(Object.entries(social.conversations).map(([id,list])=>[id,clone((list||[]).slice(-100))]))};}
 profile(accountId,fallback={}){const p=this.presence.get(accountId)?.session||fallback;return {accountId,name:trimName(p?.name),avatar:p?.avatar||null,provider:p?.provider||null};}
 async savePair(aId,aState,bId,bState){await Promise.all([this.persist(aId,aState),this.persist(bId,bState)]);this.setLiveState(aId,aState);this.setLiveState(bId,bState);this.notify([aId,bId]);}
 async action(accountId,session,action){if(!UUID.test(accountId||'')||!['google','discord'].includes(session?.provider))return {ok:false,code:'ACCOUNT_REQUIRED'};const state=await this.stateFor(accountId);if(!state)return {ok:false,code:'ACCOUNT_STATE_UNAVAILABLE'};const social=ensureSocialState(state),type=action?.type,now=this.clock.now();
  if(type==='socialV1.friend.request'){const targetId=accountIdFromFriendCode(action.friendCode);if(!targetId)return {ok:false,code:'INVALID_FRIEND_CODE'};if(targetId===accountId)return {ok:false,code:'CANNOT_ADD_SELF'};if(friendOf(state,targetId))return {ok:false,code:'ALREADY_FRIENDS'};if(social.outgoingRequests.some(entry=>entry.accountId===targetId))return {ok:false,code:'REQUEST_ALREADY_SENT'};if(social.friends.length>=100||social.outgoingRequests.length>=100)return {ok:false,code:'SOCIAL_LIMIT_REACHED'};const target=await this.stateFor(targetId);if(!target)return {ok:false,code:'TRAINER_NOT_FOUND'};const targetSocial=ensureSocialState(target);if(targetSocial.friends.length>=100||targetSocial.incomingRequests.length>=100)return {ok:false,code:'SOCIAL_LIMIT_REACHED'};const me=this.profile(accountId,session),them=this.profile(targetId);social.outgoingRequests.push({...them,requestedAt:now});targetSocial.incomingRequests.push({...me,requestedAt:now});await this.savePair(accountId,state,targetId,target);return {ok:true};}
  const targetId=String(action.accountId||'');if(!UUID.test(targetId))return {ok:false,code:'INVALID_TRAINER'};const target=await this.stateFor(targetId);if(!target)return {ok:false,code:'TRAINER_NOT_FOUND'};const targetSocial=ensureSocialState(target);
  if(type==='socialV1.friend.accept'){const request=social.incomingRequests.find(entry=>entry.accountId===targetId);if(!request)return {ok:false,code:'REQUEST_NOT_FOUND'};const me=this.profile(accountId,session),them=this.profile(targetId,request);social.incomingRequests=social.incomingRequests.filter(entry=>entry.accountId!==targetId);targetSocial.outgoingRequests=targetSocial.outgoingRequests.filter(entry=>entry.accountId!==accountId);if(!friendOf(state,targetId))social.friends.push({...them,since:now});if(!friendOf(target,accountId))targetSocial.friends.push({...me,since:now});await this.savePair(accountId,state,targetId,target);return {ok:true};}
  if(type==='socialV1.friend.reject'){social.incomingRequests=social.incomingRequests.filter(entry=>entry.accountId!==targetId);targetSocial.outgoingRequests=targetSocial.outgoingRequests.filter(entry=>entry.accountId!==accountId);await this.savePair(accountId,state,targetId,target);return {ok:true};}
  if(type==='socialV1.friend.cancel'){social.outgoingRequests=social.outgoingRequests.filter(entry=>entry.accountId!==targetId);targetSocial.incomingRequests=targetSocial.incomingRequests.filter(entry=>entry.accountId!==accountId);await this.savePair(accountId,state,targetId,target);return {ok:true};}
  if(type==='socialV1.friend.remove'){social.friends=social.friends.filter(entry=>entry.accountId!==targetId);targetSocial.friends=targetSocial.friends.filter(entry=>entry.accountId!==accountId);delete social.conversations[targetId];delete targetSocial.conversations[accountId];await this.savePair(accountId,state,targetId,target);return {ok:true};}
  if(type==='socialV1.chat.send'){if(!friendOf(state,targetId)||!friendOf(target,accountId))return {ok:false,code:'FRIEND_REQUIRED'};const last=this.lastMessageAt.get(accountId)||0;if(now-last<750)return {ok:false,code:'CHAT_RATE_LIMITED'};const text=String(action.text||'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g,'').trim().slice(0,500);if(!text)return {ok:false,code:'EMPTY_MESSAGE'};this.lastMessageAt.set(accountId,now);const message={id:randomUUID(),fromAccountId:accountId,toAccountId:targetId,text,sentAt:now};for(const [owner,s,id] of [[accountId,social,targetId],[targetId,targetSocial,accountId]]){s.conversations[id]??=[];s.conversations[id].push(message);s.conversations[id]=s.conversations[id].slice(-100);}await this.savePair(accountId,state,targetId,target);return {ok:true};}
  return {ok:false,code:'UNKNOWN_SOCIAL_ACTION'};
 }
}
