import {randomBytes,randomUUID} from 'node:crypto';
import {replacementRequirements,validateReplacements} from '../rules-v3/index.mjs';
import {createV3PvpBattle,publicV3Preview} from './v3-battle-factory.mjs';
import {normalizeCommands} from './v3-battle-actions.mjs';
import {pvpBattleView,resolvePvpCommands,resolvePvpReplacements} from './pvp-battle-runtime.mjs';
import {validateV3Team} from './v3-progression.mjs';
import {PVP_TIMERS,chooseTimeoutCommands,chooseTimeoutReplacements,firstPreviewPicks,markParticipantConnected,markParticipantDisconnected,markPvpActivity,participantDisconnectExpired,pvpTimingView,syncPvpDecisionClock} from './pvp-lifecycle.mjs';
import {validRankedActionId,rankedActionFingerprint} from './ranked-action-identity.mjs';

const clone=value=>structuredClone(value),other=side=>side==='A'?'B':'A',CODE_ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const roomCode=()=>{const bytes=randomBytes(6);return [...bytes].map(value=>CODE_ALPHABET[value%CODE_ALPHABET.length]).join('');},seed32=()=>randomBytes(4).readUInt32LE(0);
const participantView=p=>({name:p.name,connected:p.connected!==false,reconnectDeadlineAt:p.connected===false?p.disconnectDeadlineAt||null:null});
function teamPreview(state,catalog,teamId){const progression=state?.progressionV3,team=progression?.teams?.find(entry=>entry.teamId===teamId);if(!team)return {ok:false,code:'TEAM_NOT_FOUND'};const problems=validateV3Team(team,progression,catalog);if(problems.length)return {ok:false,code:'TEAM_ILLEGAL',details:problems};return {ok:true,team,roster:publicV3Preview(team,progression,catalog)};}

export class TrainingPvpService{
 constructor({catalog,clock={now:()=>Date.now()},getState,notify=()=>{},isFriend=()=>false}){this.catalog=catalog;this.clock=clock;this.getState=getState;this.notify=notify;this.isFriend=isFriend;this.rooms=new Map();this.playerRoom=new Map();this.invites=new Map();this.presence=new Map();this.sessionReceipts=new Map();}
 register(accountId,session){const now=this.clock.now();this.presence.set(accountId,{session,connected:true});const room=this.roomFor(accountId);if(!room||room.finished)return;const side=this.sideFor(room,accountId);if(side&&room.participants[side]){markParticipantConnected(room.participants[side],now);markPvpActivity(room,now);this.notify(this.accounts(room));}}
 unregister(accountId){const now=this.clock.now(),current=this.presence.get(accountId);if(current)this.presence.set(accountId,{...current,connected:false});const room=this.roomFor(accountId);if(!room||room.finished)return;const side=this.sideFor(room,accountId);if(side&&room.participants[side])markParticipantDisconnected(room.participants[side],now);this.notify(this.accounts(room));}
 sideFor(room,accountId){if(room.participants.A?.accountId===accountId)return 'A';if(room.participants.B?.accountId===accountId)return 'B';return null;}
 accounts(room){return Object.values(room.participants).filter(Boolean).map(p=>p.accountId);}
 roomFor(accountId){const code=this.playerRoom.get(accountId);return code?this.rooms.get(code):null;}
 accountIdsForAction(accountId,action){const joinCode=action?.type==='trainingPvpV1.room.join'?String(action.code||'').trim().toUpperCase():null,room=joinCode?this.rooms.get(joinCode):this.roomFor(accountId),ids=[accountId,...(room?this.accounts(room):[])];if(action?.type==='trainingPvpV1.room.invite')ids.push(String(action.accountId||''));return [...new Set(ids.filter(Boolean))];}
 busy(accountId){return this.playerRoom.has(accountId);}
 revokeInvites(code){const affected=[];for(const [accountId,list] of this.invites){const next=list.filter(invite=>invite.code!==code);if(next.length===list.length)continue;affected.push(accountId);if(next.length)this.invites.set(accountId,next);else this.invites.delete(accountId);}return affected;}
 destroyRoom(room,{notify=true}={}){const accounts=this.accounts(room),inviteTargets=this.revokeInvites(room.code),targets=[...new Set([...accounts,...inviteTargets])];for(const id of accounts)this.playerRoom.delete(id);this.rooms.delete(room.code);if(notify&&targets.length)this.notify(targets);}
 leaveBeforeBattle(room,accountId){const side=this.sideFor(room,accountId);if(!side)return {ok:false,code:'NO_TRAINING_ROOM'};if(side==='A'){this.destroyRoom(room);return {ok:true,closed:true};}this.playerRoom.delete(accountId);room.participants.B=null;room.participants.A.lockedBuildIds=null;room.pending={commands:{},replacements:{}};room.actionReceipts=[];room.decisionClock=null;markPvpActivity(room,this.clock.now());this.notify([accountId,room.participants.A.accountId]);return {ok:true,left:true};}
 viewFor(accountId){const now=this.clock.now(),room=this.roomFor(accountId),incoming=(this.invites.get(accountId)||[]).filter(invite=>invite.expiresAt>now).map(clone);if(!room)return {schemaVersion:1,status:'idle',incomingInvites:incoming};const side=this.sideFor(room,accountId);if(!side){this.playerRoom.delete(accountId);return {schemaVersion:1,status:'idle',incomingInvites:incoming};}const foe=room.participants[other(side)]||null,status=room.finished?'finished':!foe?'waiting':room.battle?'battle':'preview',battleV3=foe?pvpBattleView(room,side,{kind:'training-pvp',difficulty:'trainer',participantView}):null;if(battleV3)battleV3.timing=pvpTimingView(room,side,now);return {schemaVersion:1,status,room:{code:room.code,mode:room.mode,host:participantView(room.participants.A),opponent:foe?participantView(foe):null,createdAt:room.createdAt},battleV3,incomingInvites:incoming};}
 createParticipant(accountId,session,team){return {accountId,name:session?.name||'Vanguard Trainer',teamId:team.team.teamId,teamBuildIds:[...team.team.buildIds],roster:team.roster,lockedBuildIds:null,connected:true,disconnectedAt:null,disconnectDeadlineAt:null,disconnectExpired:false};}
 startBattleIfReady(room){if(room.battle||!room.participants.A?.lockedBuildIds||!room.participants.B?.lockedBuildIds)return false;const aState=this.getState(room.participants.A.accountId),bState=this.getState(room.participants.B.accountId);room.battle=createV3PvpBattle({id:room.id,mode:room.mode,seed:room.seed,buildIdsA:room.participants.A.lockedBuildIds,progressionA:aState.progressionV3,buildIdsB:room.participants.B.lockedBuildIds,progressionB:bState.progressionV3,catalog:this.catalog});room.lastEvents=clone(room.battle.events);return true;}
 async action(accountId,session,action){
  const actionId=action?.actionId;if(actionId!==undefined&&!validRankedActionId(actionId))return {ok:false,code:'INVALID_TRAINING_PVP_ACTION_ID'};
  const key=actionId?`${accountId}:${actionId}`:null,fingerprint=key?rankedActionFingerprint(accountId,action):null,previous=key?this.sessionReceipts.get(key):null;
  if(previous){if(previous.fingerprint!==fingerprint)return {ok:false,code:'TRAINING_PVP_ACTION_ID_CONFLICT'};this.notify([accountId]);return {...previous.result,duplicate:true};}
  const result=await this.actionOnce(accountId,session,action);if(!result.ok||!key)return result;
  const room=this.roomFor(accountId),recorded={...result,...(Number.isSafeInteger(room?.battle?.phaseRevision)?{authoritativeRevision:room.battle.phaseRevision}:{})};
  this.sessionReceipts.set(key,{fingerprint,result:recorded});while(this.sessionReceipts.size>1000)this.sessionReceipts.delete(this.sessionReceipts.keys().next().value);
  return recorded;
 }
 async actionOnce(accountId,session,action){
  const state=this.getState(accountId),type=action?.type,now=this.clock.now();if(!state)return {ok:false,code:'ACCOUNT_STATE_UNAVAILABLE'};if(!['google','discord'].includes(session?.provider))return {ok:false,code:'ACCOUNT_REQUIRED'};
  if(type==='trainingPvpV1.room.create')return this.createRoom(accountId,session,state,action);if(type==='trainingPvpV1.room.join')return this.joinRoom(accountId,session,state,action);if(type==='trainingPvpV1.room.invite')return this.invite(accountId,session,action);
  if(type==='trainingPvpV1.room.leave'){const room=this.roomFor(accountId);if(!room)return {ok:false,code:'NO_TRAINING_ROOM'};if(room.battle&&!room.finished)return this.finishByForfeit(room,accountId,'left-room');if(!room.battle&&!room.finished)return this.leaveBeforeBattle(room,accountId);this.removeParticipant(room,accountId);return {ok:true};}
  const room=this.roomFor(accountId);if(!room)return {ok:false,code:'NO_TRAINING_ROOM'};const side=this.sideFor(room,accountId);if(!side)return {ok:false,code:'NO_TRAINING_ROOM'};if(participantDisconnectExpired(room.participants[side],now))return {ok:false,code:'DISCONNECT_TIMEOUT'};const foeSide=other(side),foe=room.participants[foeSide];if(!foe)return {ok:false,code:'WAITING_FOR_OPPONENT'};syncPvpDecisionClock(room,now);const revision=room.battle?.phaseRevision;
  if(type==='trainingPvpV1.preview.lock'){if(room.battle||room.finished)return {ok:false,code:'WRONG_PHASE'};const p=room.participants[side],pick=this.catalog.regulations[0].pick[room.mode];if(!Array.isArray(action.buildIds)||action.buildIds.length!==pick||new Set(action.buildIds).size!==pick||action.buildIds.some(id=>!p.teamBuildIds.includes(id)))return {ok:false,code:'INVALID_PREVIEW_SELECTION'};p.lockedBuildIds=[...action.buildIds];this.startBattleIfReady(room);}
  else if(type==='trainingPvpV1.commands'){if(room.finished||room.battle?.phase!=='COMMAND'||action.phaseRevision!==revision)return {ok:false,code:'STALE_PHASE'};const validated=normalizeCommands(room.battle,side,action.commands,this.catalog);if(!validated.ok)return validated;room.pending.commands[revision]??={};room.pending.commands[revision][side]=clone(action.commands);const resolved=resolvePvpCommands(room,this.catalog);if(!resolved.ok)return resolved;}
  else if(type==='trainingPvpV1.replacements'){if(room.finished||room.battle?.phase!=='REPLACE'||action.phaseRevision!==revision)return {ok:false,code:'STALE_PHASE'};const required=replacementRequirements(room.battle,side);if(!required.slots.length)return {ok:false,code:'NO_REPLACEMENT_REQUIRED'};const validated=validateReplacements(room.battle,side,action.replacements);if(!validated.ok)return validated;room.pending.replacements[revision]??={};room.pending.replacements[revision][side]=clone(action.replacements);const resolved=resolvePvpReplacements(room,this.catalog);if(!resolved.ok)return resolved;}
  else if(type==='trainingPvpV1.surrender')this.finishByForfeit(room,accountId,'surrender');else if(type==='trainingPvpV1.dismiss'){if(!room.finished)return {ok:false,code:'MATCH_NOT_FINISHED'};this.removeParticipant(room,accountId);return {ok:true};}else return {ok:false,code:'UNKNOWN_TRAINING_PVP_ACTION'};
  markPvpActivity(room,now);syncPvpDecisionClock(room,now);if(room.battle?.phase==='FINISHED'&&!room.finished){room.finished=true;room.finishedAt=now;room.decisionClock=null;}this.notify(this.accounts(room));return {ok:true};
 }
 adminOverview(){return {rooms:[...this.rooms.values()].filter(room=>!room.finished).map(room=>({kind:'friendly-room',id:room.id,code:room.code,mode:room.mode,status:!room.participants.B?'WAITING':room.battle?room.battle.phase:'PREVIEW',createdAt:room.createdAt,decisionDeadlineAt:room.decisionClock?.deadlineAt||null,players:this.accounts(room).map(accountId=>{const side=this.sideFor(room,accountId),p=room.participants[side];return {accountId,name:p.name,connected:p.connected!==false,reconnectDeadlineAt:p.disconnectDeadlineAt||null};})}))};}
 adminStopForPlayer(accountId,reason='admin-stop'){const room=this.roomFor(accountId);if(!room||room.finished)return {ok:false,code:'NO_TRAINING_ROOM'};const accounts=this.accounts(room);if(!room.battle){const id=room.id;this.destroyRoom(room);return {ok:true,kind:'friendly-room',id,accounts};}this.finishNoContest(room,reason);this.notify(accounts);return {ok:true,kind:'friendly-match',id:room.id,accounts};}
 createRoom(accountId,session,state,action){if(this.busy(accountId))return {ok:false,code:'TRAINING_ROOM_ACTIVE'};if(state.battleV3&&state.battleV3.phase!=='FINISHED')return {ok:false,code:'BATTLE_ALREADY_ACTIVE'};if(!['single','double'].includes(action.mode))return {ok:false,code:'INVALID_FORMAT'};const preview=teamPreview(state,this.catalog,action.teamId);if(!preview.ok)return preview;let code;do code=roomCode();while(this.rooms.has(code));const now=this.clock.now(),room={id:`training-${randomUUID()}`,code,mode:action.mode,seed:seed32(),createdAt:now,updatedAt:now,lastActivityAt:now,participants:{A:this.createParticipant(accountId,session,preview),B:null},battle:null,pending:{commands:{},replacements:{}},lastEvents:[],lastTurnRaw:null,actionReceipts:[],finished:false,finishedAt:null,dismissed:new Set(),decisionClock:null};this.rooms.set(code,room);this.playerRoom.set(accountId,code);this.notify([accountId]);return {ok:true};}
 joinRoom(accountId,session,state,action){if(this.busy(accountId))return {ok:false,code:'TRAINING_ROOM_ACTIVE'};if(state.battleV3&&state.battleV3.phase!=='FINISHED')return {ok:false,code:'BATTLE_ALREADY_ACTIVE'};const code=String(action.code||'').trim().toUpperCase(),room=this.rooms.get(code);if(!room)return {ok:false,code:'ROOM_NOT_FOUND'};if(room.participants.B)return {ok:false,code:'ROOM_FULL'};if(room.participants.A.accountId===accountId)return {ok:false,code:'ALREADY_HOST'};const preview=teamPreview(state,this.catalog,action.teamId);if(!preview.ok)return preview;room.participants.B=this.createParticipant(accountId,session,preview);this.playerRoom.set(accountId,code);markPvpActivity(room,this.clock.now());syncPvpDecisionClock(room,this.clock.now());const inviteTargets=this.revokeInvites(code);this.notify([...new Set([accountId,room.participants.A.accountId,...inviteTargets])]);return {ok:true};}
 invite(accountId,session,action){const room=this.roomFor(accountId);if(!room||room.participants.A.accountId!==accountId||room.participants.B)return {ok:false,code:'ROOM_NOT_INVITABLE'};const targetId=String(action.accountId||'');if(!this.isFriend(accountId,targetId))return {ok:false,code:'FRIEND_REQUIRED'};if(!this.presence.get(targetId)?.connected)return {ok:false,code:'FRIEND_OFFLINE'};const now=this.clock.now(),invite={id:randomUUID(),code:room.code,mode:room.mode,fromAccountId:accountId,fromName:session?.name||'Vanguard Trainer',createdAt:now,expiresAt:now+15*60_000};const list=(this.invites.get(targetId)||[]).filter(entry=>entry.expiresAt>now&&entry.code!==room.code);list.unshift(invite);this.invites.set(targetId,list.slice(0,10));this.notify([targetId,accountId]);return {ok:true};}
 finishByForfeit(room,accountId,reason){const side=this.sideFor(room,accountId);if(!side)return {ok:false,code:'NO_TRAINING_ROOM'};const winner=other(side);if(!room.battle){this.destroyRoom(room);return {ok:true};}const battle=clone(room.battle);battle.phase='FINISHED';battle.phaseRevision++;battle.result={winner,reason,turn:battle.turn,receiptId:`${battle.id}:training-forfeit:${side}`};room.battle=battle;room.lastEvents=[{kind:'battleEnded',winner,reason}];room.finished=true;room.finishedAt=this.clock.now();room.decisionClock=null;this.notify(this.accounts(room));return {ok:true};}
 finishNoContest(room,reason){if(room.finished)return;const battle=clone(room.battle);battle.phase='FINISHED';battle.phaseRevision=(battle.phaseRevision||0)+1;battle.result={winner:null,reason,turn:battle.turn||0,receiptId:`${battle.id}:${reason}`};room.battle=battle;room.lastEvents=[{kind:'battleEnded',winner:null,reason}];room.finished=true;room.finishedAt=this.clock.now();room.decisionClock=null;}
 removeParticipant(room,accountId){this.playerRoom.delete(accountId);room.dismissed.add(accountId);if(room.finished&&room.dismissed.size>=this.accounts(room).length){this.destroyRoom(room);return;}this.notify(this.accounts(room));}
 applyDecisionTimeout(room,now){const decision=syncPvpDecisionClock(room,now);if(!decision||now<decision.deadlineAt||room.finished)return false;const sides=['A','B'];if(decision.kind==='preview'){const pick=this.catalog.regulations[0].pick[room.mode];for(const side of sides)if(!room.participants[side].lockedBuildIds)room.participants[side].lockedBuildIds=firstPreviewPicks(room,side,pick);this.startBattleIfReady(room);}
  else if(decision.kind==='command'){const revision=room.battle.phaseRevision;room.pending.commands[revision]??={};for(const side of sides)if(!room.pending.commands[revision][side]){const commands=chooseTimeoutCommands(room.battle,this.catalog,side);if(!commands){this.finishNoContest(room,'action-timeout-no-legal-action');return true;}room.pending.commands[revision][side]=commands;}const resolved=resolvePvpCommands(room,this.catalog);if(!resolved.ok){this.finishNoContest(room,'action-timeout-resolution-error');return true;}}
  else if(decision.kind==='replacement'){const revision=room.battle.phaseRevision;room.pending.replacements[revision]??={};for(const side of sides){const required=replacementRequirements(room.battle,side);if(required.slots.length&&!room.pending.replacements[revision][side])room.pending.replacements[revision][side]=chooseTimeoutReplacements(room.battle,side);}const resolved=resolvePvpReplacements(room,this.catalog);if(!resolved.ok){this.finishNoContest(room,'replacement-timeout-resolution-error');return true;}}
  markPvpActivity(room,now);room.lastAutoAction={kind:decision.kind,at:now};syncPvpDecisionClock(room,now);if(room.battle?.phase==='FINISHED'&&!room.finished){room.finished=true;room.finishedAt=now;room.decisionClock=null;}this.notify(this.accounts(room));return true;
 }
 tick(){const now=this.clock.now();for(const [accountId,list] of this.invites){const next=list.filter(entry=>entry.expiresAt>now);if(next.length)this.invites.set(accountId,next);else this.invites.delete(accountId);}for(const room of [...this.rooms.values()]){if(room.finished){if(now-(room.finishedAt||now)>=PVP_TIMERS.resultRetentionMs)this.destroyRoom(room);continue;}const foe=room.participants.B;if(!foe){const host=room.participants.A;if(participantDisconnectExpired(host,now)||now-room.createdAt>=PVP_TIMERS.friendlyWaitingRoomMs){this.destroyRoom(room);continue;}continue;}
   const expired=['A','B'].filter(side=>participantDisconnectExpired(room.participants[side],now));if(!room.battle&&expired.length){if(expired.includes('A')){this.destroyRoom(room);continue;}this.leaveBeforeBattle(room,room.participants.B.accountId);continue;}if(room.battle&&expired.length===2){this.finishNoContest(room,'both-disconnected');this.notify(this.accounts(room));continue;}if(room.battle&&expired.length===1&&room.participants[other(expired[0])].connected!==false){this.finishByForfeit(room,room.participants[expired[0]].accountId,'disconnect-timeout');continue;}if(now-(room.lastActivityAt||room.createdAt)>=PVP_TIMERS.hardIdleMs){if(room.battle){this.finishNoContest(room,'match-expired');this.notify(this.accounts(room));}else this.destroyRoom(room);continue;}this.applyDecisionTimeout(room,now);}}
}
