import {clone,unitById} from '../rules-v3/battle-state.mjs';
import {calculateDamage} from '../rules-v3/damage.mjs';
import {stagedStat} from '../rules-v3/stats.mjs';
import {passiveDamageModifiers,receivedDamageModifiers} from './passive-effects.mjs';
import {defenseWithWeather,weatherDamageModifier} from './weather.mjs';
import {sideConditionDamageModifiers} from './side-conditions.mjs';
import {abilityIgnoresOpponentStage} from './ability-stage-change.mjs';
import {terrainDamageModifiers} from './terrain.mjs';
import {wonderRoomDefenseBase} from './rooms.mjs';
import {applySemiInvulnerabilityHitEffect,semiInvulnerabilityInteraction} from './semi-invulnerability.mjs';
import {abilityCriticalRatioStages,abilityForcesCritical,abilityIgnoresBurnAttackPenalty,abilityPowerModifiers,abilityPreventsCritical,abilityProtectionPierce,abilityStabModifier,abilityStatModifiers,allyReceivedDamageModifiers} from './ability-hooks.mjs';
import {resolveContactAbilityResponses} from './ability-contact.mjs';
import {applyLethalHitSurvivalAbility,resolveDamageResponseAbilities,resolveKoAbilityEffects} from './ability-damage-response.mjs';
import {resolveAllyFaintAbilityCopies} from './ability-replacement.mjs';
import {applyResistanceBerryToMoveDamage,applySurvivalItemToMoveDamage,criticalChanceWithHeldItems,resolveContactDamageItems,resolvePostDamageItems,statWithHeldItems,typeEffectivenessWithHeldItems} from './item-hooks.mjs';
import {opponentAbilitiesIgnoredFor} from './ability-targeting.mjs';
import {applyDisguiseShield} from './ability-form.mjs';
import {applySubstituteDamage,substituteBypassed} from './substitute.mjs';
import {breakIllusionOnDamage} from './ability-transform.mjs';
import {resolvePreparedContactResponse} from './prepared-contact.mjs';
import {resolveDestinyBondKo} from './destiny-bond.mjs';

const pokeRound=value=>value%1>.5?Math.ceil(value):Math.floor(value);
const activeRef=(battle,actorId)=>{for(const side of ['A','B']){const slot=battle.sides?.[side]?.active?.indexOf(actorId)??-1;if(slot>=0)return {sourceSide:side,sourceSlot:slot};}return {sourceSide:null,sourceSlot:null};};

export function applyDamageHit(battle,{actorId,targetId,move,mechanics=null,spread=false,hit=null,ignoreBurn=false,moveItemMultiplier=1,moveItemId=null,allowFaintedActor=false,damageMultiplier=1},runtime){
 if(typeof runtime?.nextRandom!=='function')throw new Error('damage hit requires seeded nextRandom');
 let next=clone(battle);const actor=unitById(next,actorId),defender=unitById(next,targetId),sourceRef=activeRef(next,actorId);
 if(!actor||(!allowFaintedActor&&actor.hp<=0)||!defender||defender.hp<=0)return {battle:next,amount:0,events:[]};
 const ignoreTargetAbility=opponentAbilitiesIgnoredFor(next,actorId,targetId,mechanics),physical=move.category==='physical',categoryAttackKey=physical?'atk':'spa',profile=mechanics?.damageProfile||{},offensiveStatKey=profile.offensiveStat||categoryAttackKey,offensiveSource=profile.offensiveSource||'user',defenseKey=profile.defensiveStat||(physical?'def':'spd'),primaryEffectiveness=typeEffectivenessWithHeldItems(move.type,defender,next,{attacker:actor,ignoreDefenderAbility:ignoreTargetAbility,typeEffectivenessOverrides:profile.typeEffectivenessOverrides}),secondaryEffectiveness=profile.secondaryAttackType?typeEffectivenessWithHeldItems(profile.secondaryAttackType,defender,next,{attacker:actor,ignoreDefenderAbility:ignoreTargetAbility}):1,effectiveness=primaryEffectiveness*secondaryEffectiveness,weatherModifier=weatherDamageModifier(next,move.type,actor);
 if(effectiveness===0){
  const breakdown=calculateDamage({level:next.level||50,power:move.power,attack:(offensiveSource==='target'?defender:actor).stats[offensiveStatKey],defense:wonderRoomDefenseBase(next,defender,defenseKey),moveType:move.type,attackerTypes:actor.types,defenderTypes:defender.types,randomRoll:100,weatherModifier,physical,typeModifier:effectiveness});
  return {battle:next,amount:0,events:[damageEvent(actor,defender,move,0,effectiveness,{...breakdown,randomApplied:false},hit,defender.hp,sourceRef)]};
 }
 const hitsSubstitute=Boolean(defender.volatiles?.substitute&&!substituteBypassed(actor,mechanics));
 const resistance=hitsSubstitute?{battle:next,multiplier:1,events:[]} : applyResistanceBerryToMoveDamage(next,{targetId:defender.actorId,moveType:move.type,effectiveness,moveId:move.id,hit});next=resistance.battle;
 const liveActor=unitById(next,actorId),liveTarget=unitById(next,targetId),criticalRoll=runtime.nextRandom(),moveCriticalRatioStages=Number.isInteger(mechanics?.criticalRatioStages)?mechanics.criticalRatioStages:0,volatileCriticalRatioStages=Object.values(liveActor.volatiles||{}).reduce((sum,state)=>sum+(Number.isInteger(state?.criticalRatioStages)?state.criticalRatioStages:0),0),volatileAlwaysCritical=Object.values(liveActor.volatiles||{}).some(state=>state?.alwaysCritical===true),critical=!(ignoreTargetAbility?false:abilityPreventsCritical(liveTarget))&&(mechanics?.alwaysCritical===true||volatileAlwaysCritical||abilityForcesCritical(liveActor,liveTarget)||criticalRoll<criticalChanceWithHeldItems(liveActor,next,{baseStage:moveCriticalRatioStages+volatileCriticalRatioStages+abilityCriticalRatioStages(liveActor)})),randomRoll=85+Math.floor(runtime.nextRandom()*16);
 const liveOffensive=offensiveSource==='target'?liveTarget:liveActor,rawAttackStage=critical&&liveOffensive.stages?.[offensiveStatKey]<0?0:liveOffensive.stages?.[offensiveStatKey]||0,rawDefenseStage=profile.ignoreDefensiveStages?0:critical&&liveTarget.stages?.[defenseKey]>0?0:liveTarget.stages?.[defenseKey]||0,attackStage=offensiveSource==='user'&&!ignoreTargetAbility&&abilityIgnoresOpponentStage(liveTarget,offensiveStatKey,'defending')?0:rawAttackStage,defenseStage=profile.ignoreDefensiveStages?0:abilityIgnoresOpponentStage(liveActor,defenseKey,'attacking')?0:rawDefenseStage;
 const passive=passiveDamageModifiers(liveActor,move,next,{critical,effectiveness}),received=receivedDamageModifiers(liveTarget,move,next,{effectiveness,ignoreAbility:ignoreTargetAbility,mechanics}),allyReceived=allyReceivedDamageModifiers(next,liveTarget,liveActor,{ignoreAbilities:ignoreTargetAbility}),sideConditions=sideConditionDamageModifiers(next,liveTarget,move,critical,liveActor),terrain=terrainDamageModifiers(next,liveActor,liveTarget,move),semi=semiInvulnerabilityInteraction(liveTarget,move.id),volatileDamageMultiplier=Object.values(liveActor.volatiles||{}).reduce((value,state)=>value*(Number.isFinite(state?.damageMultiplier)?state.damageMultiplier:Number.isFinite(state?.damageMultiplierByType?.[move.type])?state.damageMultiplierByType[move.type]:1),1),abilityPower=abilityPowerModifiers(liveActor,move,mechanics,{battle:next,runtime,target:liveTarget}),abilityStat=abilityStatModifiers(liveActor,offensiveStatKey,next,move),abilityDefense=abilityStatModifiers(liveTarget,defenseKey,next,move,{ignoreAbility:ignoreTargetAbility}),abilityPowerValue=abilityPower.apply(move.power),itemPowerValue=moveItemMultiplier===1?abilityPowerValue:Math.max(1,pokeRound(abilityPowerValue*moveItemMultiplier)),power=Math.max(1,Math.floor(itemPowerValue*terrain.powerModifier)),stagedAttack=stagedStat(liveOffensive.stats[offensiveStatKey],attackStage),attack=statWithHeldItems(abilityStat.apply(stagedAttack),liveActor,offensiveStatKey,next),baseDefense=stagedStat(wonderRoomDefenseBase(next,liveTarget,defenseKey),defenseStage),abilityDefenseValue=abilityDefense.apply(baseDefense),defense=defenseWithWeather(abilityDefenseValue,liveTarget,defenseKey,next),damage=calculateDamage({level:next.level||50,power,attack,defense,moveType:move.type,attackerTypes:liveActor.types,defenderTypes:liveTarget.types,typeModifier:effectiveness,randomRoll,spread,weatherModifier,critical,burned:!ignoreBurn&&!abilityIgnoresBurnAttackPenalty(liveActor)&&(liveActor.status?.id||liveActor.status)==='burn',physical,stabModifier:abilityStabModifier(liveActor,move),otherModifiers:[...passive.values,...received.values,...allyReceived.values,...sideConditions.values,...terrain.values,semi.multiplier,resistance.multiplier,volatileDamageMultiplier,damageMultiplier,(liveTarget.volatiles?.protect&&abilityProtectionPierce(liveActor,mechanics)?.multiplier)||1]});
 damage.damageProfile={offensiveStat:offensiveStatKey,offensiveSource,defensiveStat:defenseKey,ignoreDefensiveStages:profile.ignoreDefensiveStages===true,...(Number.isInteger(profile.minTargetHp)?{minTargetHp:profile.minTargetHp}:{}),...(profile.typeEffectivenessOverrides?{typeEffectivenessOverrides:{...profile.typeEffectivenessOverrides}}:{}),...(profile.secondaryAttackType?{secondaryAttackType:profile.secondaryAttackType,secondaryEffectiveness}: {})};damage.passiveModifiers=[...passive.applied,...received.applied,...allyReceived.applied];damage.abilityPowerModifiers=abilityPower.applied;damage.abilityStatModifiers=[...abilityStat.applied,...abilityDefense.applied];damage.abilityDefenseModifiers=abilityDefense.applied;damage.sideConditionModifiers=sideConditions.applied;damage.terrainModifiers=terrain.applied;if(defense!==abilityDefenseValue)damage.weatherDefenseModifier={weather:next.field?.weather?.id,stat:defenseKey,multiplier:defense/abilityDefenseValue};if(terrain.powerModifier!==1)damage.terrainPowerModifier=terrain.powerModifier;if(semi.multiplier!==1)damage.semiInvulnerabilityModifier={mode:semi.mode,multiplier:semi.multiplier};if(volatileDamageMultiplier!==1)damage.volatileDamageMultiplier=volatileDamageMultiplier;if(damageMultiplier!==1)damage.explicitDamageMultiplier=damageMultiplier;const protectPierce=liveTarget.volatiles?.protect&&abilityProtectionPierce(liveActor,mechanics);if(protectPierce)damage.protectionPierce={sourceKind:'ability',sourceId:protectPierce.sourceId,multiplier:protectPierce.multiplier};if(resistance.itemId)damage.itemResistance={sourceKind:'item',sourceId:resistance.itemId,multiplier:resistance.multiplier};if(moveItemId&&moveItemMultiplier!==1)damage.itemMovePowerModifier={sourceKind:'item',sourceId:moveItemId,multiplier:moveItemMultiplier};
 if(hitsSubstitute){const sub=applySubstituteDamage(next,{actorId,targetId,damage:damage.damage,moveId:move.id,mechanics,hit});return {battle:sub.battle,amount:sub.amount,substituteAbsorbed:sub.absorbed,events:[...sub.events]};}
 const disguise=applyDisguiseShield(next,{targetId,damage:damage.damage,moveId:move.id,hit,ignored:ignoreTargetAbility});if(disguise.shielded)return {battle:disguise.battle,amount:0,disguiseShielded:true,events:disguise.events};next=disguise.battle;
 const targetBeforeSurvival=unitById(next,targetId);if(!targetBeforeSurvival||targetBeforeSurvival.hp<=0)return {battle:next,amount:0,disguiseShielded:true,events:disguise.events};
 const hpBefore=targetBeforeSurvival.hp,minTargetHp=Number.isInteger(profile.minTargetHp)?profile.minTargetHp:0,profileDamage=Math.min(damage.damage,Math.max(0,hpBefore-minTargetHp));if(profileDamage!==damage.damage)damage.nonLethalFloor={minTargetHp,originalDamage:damage.damage,adjustedDamage:profileDamage};
 const endureActive=Boolean(targetBeforeSurvival.volatiles?.endure),endureDamage=endureActive&&profileDamage>=hpBefore?Math.max(0,hpBefore-1):profileDamage,endureEvents=endureDamage!==profileDamage?[{kind:'endureActivated',actorId:targetBeforeSurvival.actorId,targetId:targetBeforeSurvival.actorId,moveId:move.id,originalDamage:profileDamage,adjustedDamage:endureDamage}]:[];
 const abilitySurvival=applyLethalHitSurvivalAbility(next,{targetId:targetBeforeSurvival.actorId,damage:endureDamage,moveId:move.id,hit,ignoreAbility:ignoreTargetAbility});next=abilitySurvival.battle;
 const survival=applySurvivalItemToMoveDamage(next,{targetId:targetBeforeSurvival.actorId,damage:abilitySurvival.damage,moveId:move.id,hit,runtime});next=survival.battle;const liveDefender=unitById(next,targetBeforeSurvival.actorId),amount=Math.min(hpBefore,survival.damage);liveDefender.hp-=amount;
 if(abilitySurvival.abilityId)damage.abilitySurvival={sourceKind:'ability',sourceId:abilitySurvival.abilityId,originalDamage:damage.damage,adjustedDamage:abilitySurvival.damage};
 if(survival.itemId)damage.itemSurvival={sourceKind:'item',sourceId:survival.itemId,originalDamage:abilitySurvival.damage,adjustedDamage:amount};
 let events=[...resistance.events,...endureEvents,...abilitySurvival.events,...survival.events,damageEvent(liveActor,{...liveDefender,hp:hpBefore},move,amount,damage.type,damage,hit,liveDefender.hp,sourceRef)];
 if(amount>0){const illusion=breakIllusionOnDamage(next,{targetId:liveDefender.actorId,sourceId:liveActor.actorId,moveId:move.id});next=illusion.battle;events.push(...illusion.events);}
 if(amount>0){
  const response=resolveDamageResponseAbilities(next,{actorId:liveActor.actorId,targetId:liveDefender.actorId,move,damage:amount,hpBefore,hpAfter:liveDefender.hp,breakdown:damage,ignoreTargetAbility},runtime);next=response.battle;events.push(...response.events);
  const currentDefender=unitById(next,liveDefender.actorId);
  if(currentDefender?.hp>0){const aftermath=applySemiInvulnerabilityHitEffect(next,{targetId:currentDefender.actorId,moveId:move.id});next=aftermath.battle;events.push(...aftermath.events);}
  const preparedContact=resolvePreparedContactResponse(next,{attackerId:liveActor.actorId,targetId:liveDefender.actorId,moveId:move.id,mechanics},runtime);next=preparedContact.battle;events.push(...preparedContact.events);
  const abilityContact=resolveContactAbilityResponses(next,{attackerId:liveActor.actorId,targetId:liveDefender.actorId,moveId:move.id,mechanics,damage:amount,hit,ignoreTargetAbility},runtime);next=abilityContact.battle;events.push(...abilityContact.events);
  const contact=resolveContactDamageItems(next,{attackerId:liveActor.actorId,targetId:liveDefender.actorId,moveId:move.id,mechanics,damage:amount,hit});next=contact.battle;events.push(...contact.events);
 }
 if(amount>0){const item=resolvePostDamageItems(next,{targetId:liveDefender.actorId,moveId:move.id,damage:amount});next=item.battle;events.push(...item.events);}
 const finalDefender=unitById(next,liveDefender.actorId);
 if(finalDefender?.hp===0){const ko=resolveKoAbilityEffects(next,{actorId:liveActor.actorId,targetId:finalDefender.actorId,moveId:move.id});next=ko.battle;events.push(...ko.events);if(runtime?.abilityManifests){const copied=resolveAllyFaintAbilityCopies(next,{faintedId:finalDefender.actorId,manifests:runtime.abilityManifests});next=copied.battle;events.push(...copied.events);}events.push({kind:'fainted',targetId:finalDefender.actorId,source:move.id});const bond=resolveDestinyBondKo(next,{attackerId:liveActor.actorId,targetId:finalDefender.actorId,moveId:move.id});next=bond.battle;events.push(...bond.events);if(bond.triggered&&runtime?.abilityManifests){const copied=resolveAllyFaintAbilityCopies(next,{faintedId:liveActor.actorId,manifests:runtime.abilityManifests});next=copied.battle;events.push(...copied.events);}}
 return {battle:next,amount,events};
}

function damageEvent(actor,defender,move,amount,effectiveness,breakdown,hit,hpAfter=defender.hp,sourceRef={}){
 return {kind:'damage',actorId:actor.actorId,targetId:defender.actorId,moveId:move.id,category:move.category,sourceSide:sourceRef.sourceSide??null,sourceSlot:Number.isInteger(sourceRef.sourceSlot)?sourceRef.sourceSlot:null,hpBefore:defender.hp,hpAfter,amount,effectiveness,breakdown,...(hit===null?{}:{hit})};
}
