// GENERATED by scripts/compile-logic.mjs from logic-src/manifest.json.
// Source hash: c30f87e6ef2e17ba83bef68a9e646340faa463745c75ac7db7cdd4c889dc1a5c
// Do not edit this file directly; edit logic-src fragments and run npm run compile:logic.

// ---- 10-v2-builds.js ----
const V2_STAT_KEYS=['hp','atk','def','spa','spd','spe'];
function V2_validateBuild(build,species,catalog){
 const errors=[];
 if(!build||typeof build!=='object')return ['build must be an object'];
 const points=build.points||{};let total=0;
 for(const key of V2_STAT_KEYS){const value=points[key];if(!Number.isInteger(value)||value<0||value>32)errors.push(`${key} points must be an integer from 0 to 32`);else total+=value;}
 if(total>66)errors.push('stat points total cannot exceed 66');
 const up=build.alignment?.up??null,down=build.alignment?.down??null,aligned=V2_STAT_KEYS.filter(key=>key!=='hp');
 if((up===null)!==(down===null)||up===down&&up!==null||up!==null&&!aligned.includes(up)||down!==null&&!aligned.includes(down))errors.push('alignment must be neutral or use two different non-HP stats');
 if(!Array.isArray(build.moveIds)||build.moveIds.length!==4||new Set(build.moveIds).size!==4)errors.push('build must contain four different moves');
 else if(build.moveIds.some(id=>!species.moveIds.includes(id)||!catalog.moveIds.includes(id)))errors.push('build contains a move outside the species movepool');
 if(!species.abilityIds.includes(build.abilityId)||!catalog.abilityIds.includes(build.abilityId))errors.push('build contains an unsupported ability');
 if(!catalog.itemIds.includes(build.itemId))errors.push('build contains an unsupported item');
 return errors;
}
function V2_calculateStats(baseStats,points,alignment={up:null,down:null}){
 const result={hp:100+baseStats.hp+2*points.hp};
 for(const key of V2_STAT_KEYS.slice(1)){const multiplier=alignment.up===key?1.1:alignment.down===key?.9:1;result[key]=Math.floor((baseStats[key]+20+2*points[key])*multiplier);}
 return result;
}
function V2_createBattleMon({battleMonId,ownerSide,build,species,moves,catalog}){
 const errors=V2_validateBuild(build,species,catalog);if(errors.length)throw new Error(errors.join('; '));
 const stats=V2_calculateStats(species.baseStats,build.points,build.alignment);
 return {battleMonId,ownerSide,speciesId:species.id,types:[...species.types],buildSnapshot:JSON.parse(JSON.stringify(build)),stats,hp:stats.hp,pp:Object.fromEntries(build.moveIds.map(id=>[id,moves[id].maxPP])),status:null,stages:{atk:0,def:0,spa:0,spd:0,spe:0},volatiles:{},itemState:{used:false},formId:null};
}

// ---- 20-v2-damage.js ----
const V2_STRONG={Flame:['Bloom','Frost','Steel'],Tide:['Flame','Stone'],Bloom:['Tide','Stone'],Volt:['Tide','Gale'],Frost:['Bloom','Gale'],Stone:['Flame','Volt'],Gale:['Bloom','Venom'],Shadow:['Astral','Light'],Light:['Shadow','Venom'],Venom:['Bloom','Light'],Steel:['Frost','Light'],Astral:['Venom','Steel']};
const V2_RESIST={Flame:['Flame','Tide','Stone'],Tide:['Tide','Bloom'],Bloom:['Flame','Bloom','Gale','Steel'],Volt:['Volt','Bloom'],Frost:['Flame','Frost','Steel'],Stone:['Bloom','Steel'],Gale:['Volt','Steel'],Shadow:['Shadow','Steel'],Light:['Light','Steel'],Venom:['Venom','Stone'],Steel:['Flame','Tide','Steel'],Astral:['Astral']};
const V2_IMMUNE={Volt:['Stone'],Venom:['Steel'],Astral:['Shadow']};
function V2_effectiveness(type,targetTypes){return targetTypes.reduce((value,targetType)=>value*(V2_IMMUNE[type]?.includes(targetType)?0:V2_STRONG[type]?.includes(targetType)?2:V2_RESIST[type]?.includes(targetType)?.5:1),1);}
function V2_stageMultiplier(stage){const value=Math.max(-6,Math.min(6,stage||0));return value>=0?(2+value)/2:2/(2-value);}
function V2_calculateDamage({move,attacker,defender,field={},outgoing=1,incoming=1,spread=1}){
 const physical=move.category==='physical',attackKey=physical?'atk':'spa',defenseKey=physical?'def':'spd';
 const attack=Math.floor(attacker.stats[attackKey]*V2_stageMultiplier(attacker.stages?.[attackKey]));
 let defense=Math.floor(defender.stats[defenseKey]*V2_stageMultiplier(defender.stages?.[defenseKey]));defense=Math.max(1,defense);
 const base=Math.floor(22*move.power*attack/defense/50)+2,type=V2_effectiveness(move.type,defender.types),stab=attacker.types.includes(move.type)?1.5:1;
 if(type===0)return {damage:0,base,attack,defense,stab,type};
 let fieldModifier=1;
 const weather=field.weather?.id||field.weather,terrain=field.terrain?.id||field.terrain;
 if(weather==='sun')fieldModifier*=move.type==='Flame'?1.5:move.type==='Tide'?.5:1;
 if(weather==='rain')fieldModifier*=move.type==='Tide'?1.5:move.type==='Flame'?.5:1;
 if(terrain==='meadow'&&move.type==='Bloom')fieldModifier*=1.3;
 if(terrain==='storm'&&move.type==='Volt')fieldModifier*=1.3;
 const burn=physical&&attacker.status==='burn'?.5:1;
 return {damage:Math.max(1,Math.floor(base*stab*type*fieldModifier*outgoing*incoming*spread*burn)),base,attack,defense,stab,type,fieldModifier,burn};
}
function V2_spendPp(mon,moveId){if(!Number.isInteger(mon.pp?.[moveId])||mon.pp[moveId]<=0)return {ok:false,mon};const next=JSON.parse(JSON.stringify(mon));next.pp[moveId]--;return {ok:true,mon:next};}
function V2_allMovesEmpty(mon,moveIds){return moveIds.every(id=>(mon.pp?.[id]||0)<=0);}
function V2_nextRandom(state){const next=(Math.imul(state>>>0,1664525)+1013904223)>>>0;return {state:next,value:next/4294967296};}
function V2_accuracyCheck(accuracy,state){const roll=V2_nextRandom(state);return {hit:accuracy>=100||roll.value<accuracy/100,rngState:roll.state,roll:roll.value};}
const V2_STRUGGLE={id:'struggle',type:null,category:'physical',power:50,accuracy:100,maxPP:null,targetMode:'foe',recoilFraction:.25};
function V2_moveGate({mon,move,targetTypes,guarded=false,rngState}){
 const spent=V2_spendPp(mon,move.id);if(!spent.ok)return {outcome:'noPP',mon,rngState};
 if(guarded)return {outcome:'guarded',mon:spent.mon,rngState};
 if(move.type&&V2_effectiveness(move.type,targetTypes)===0)return {outcome:'immune',mon:spent.mon,rngState};
 const accuracy=V2_accuracyCheck(move.accuracy,rngState);return {outcome:accuracy.hit?'hit':'missed',mon:spent.mon,rngState:accuracy.rngState,roll:accuracy.roll};
}
function V2_struggleRecoil(actualDamage){return actualDamage>0?Math.max(1,Math.floor(actualDamage*V2_STRUGGLE.recoilFraction)):0;}

// ---- 30-v2-phases.js ----
const V2_PHASES=['CREATED','PREVIEW','ENTRY','COMMAND','RESOLVE','END_TURN','REPLACE','FINISHED'];
const V2_PHASE_NEXT={CREATED:['PREVIEW'],PREVIEW:['ENTRY'],ENTRY:['COMMAND','REPLACE','FINISHED'],COMMAND:['RESOLVE'],RESOLVE:['END_TURN','FINISHED'],END_TURN:['COMMAND','REPLACE','FINISHED'],REPLACE:['ENTRY'],FINISHED:[]};
function V2_transition(battle,next){
 if(!V2_PHASE_NEXT[battle.phase]?.includes(next))return {ok:false,code:'WRONG_PHASE'};
 return {ok:true,battle:{...battle,phase:next,phaseRevision:(battle.phaseRevision||0)+1}};
}
function V2_monById(battle,id){for(const side of ['A','B']){const mon=battle.sides[side].roster.find(entry=>entry.battleMonId===id);if(mon)return mon;}return null;}
function V2_activeEntries(battle,side){return battle.sides[side].active.map((id,slot)=>({mon:id?V2_monById(battle,id):null,slot})).filter(entry=>entry.mon&&entry.mon.hp>0);}
function V2_reserves(battle,side){const active=new Set(battle.sides[side].active.filter(Boolean));return battle.sides[side].roster.filter(mon=>mon.hp>0&&!active.has(mon.battleMonId));}
function V2_resolveTargets(battle,side,actorId,move,target){
 const foe=side==='A'?'B':'A',actor=V2_monById(battle,actorId),at=(targetSide,slot)=>{const id=battle.sides[targetSide].active[slot];const mon=id?V2_monById(battle,id):null;return mon?.hp>0?{side:targetSide,slot,battleMonId:id}:null;};
 if(move.targetMode==='self')return [{side,slot:battle.sides[side].active.indexOf(actorId),battleMonId:actorId}];
 if(move.targetMode==='ownSide'||move.targetMode==='field')return [];
 if(move.targetMode==='allFoes')return V2_activeEntries(battle,foe).map(entry=>({side:foe,slot:entry.slot,battleMonId:entry.mon.battleMonId}));
 if(move.targetMode==='ally'){const found=target&&target.side===side?at(side,target.slot):null;return found&&found.battleMonId!==actorId?[found]:[];}
 if(move.targetMode==='foe'){
  const redirects=V2_activeEntries(battle,foe).filter(entry=>entry.mon.volatiles.redirect).sort((a,b)=>(b.mon.volatiles.redirectOrder||0)-(a.mon.volatiles.redirectOrder||0));
  if(redirects[0])return [{side:foe,slot:redirects[0].slot,battleMonId:redirects[0].mon.battleMonId}];
  let found=target&&target.side===foe?at(foe,target.slot):null;
  if(!found){const first=V2_activeEntries(battle,foe)[0];found=first?{side:foe,slot:first.slot,battleMonId:first.mon.battleMonId}:null;}
  return found?[found]:[];
 }
 return actor?[]:[];
}
function V2_validateCommands(battle,side,commands,moves){
 if(battle.phase!=='COMMAND')return {ok:false,code:'WRONG_PHASE'};
 if(battle.pending?.[side])return {ok:false,code:'ALREADY_SUBMITTED'};
 const active=V2_activeEntries(battle,side),actors=new Set(active.map(entry=>entry.mon.battleMonId));
 if(!Array.isArray(commands)||commands.length!==actors.size)return {ok:false,code:'INVALID_COMMAND_COUNT'};
 const seen=new Set(),switches=new Set(),normalized=[];
 for(const command of commands){
  if(!command||!actors.has(command.actorId)||seen.has(command.actorId))return {ok:false,code:'INVALID_ACTOR'};seen.add(command.actorId);
  const mon=V2_monById(battle,command.actorId);
  if(command.kind==='switch'){
   if(!V2_reserves(battle,side).some(entry=>entry.battleMonId===command.toId)||switches.has(command.toId))return {ok:false,code:'INVALID_SWITCH'};
   switches.add(command.toId);normalized.push({...command});continue;
  }
  if(command.kind!=='move')return {ok:false,code:'INVALID_COMMAND'};
  const allEmpty=V2_allMovesEmpty(mon,mon.buildSnapshot.moveIds),struggle=command.moveId==='struggle';
  if(struggle&&!allEmpty)return {ok:false,code:'INVALID_MOVE'};
  if(!struggle&&(!mon.buildSnapshot.moveIds.includes(command.moveId)||!moves[command.moveId]))return {ok:false,code:'INVALID_MOVE'};
  if(!struggle&&(mon.pp[command.moveId]||0)<=0)return {ok:false,code:'NO_PP'};
  const move=struggle?V2_STRUGGLE:moves[command.moveId],targets=V2_resolveTargets(battle,side,command.actorId,move,command.target);
  if(['foe','ally'].includes(move.targetMode)&&targets.length===0)return {ok:false,code:'INVALID_TARGET'};
  normalized.push({...command,target:targets[0]?{side:targets[0].side,slot:targets[0].slot}:command.target});
 }
 return {ok:true,commands:normalized};
}
function V2_buildQueue(battle,commandSets,moves){
 let rngState=battle.rngState>>>0;
 const entries=[];
 for(const side of ['A','B'])for(const command of commandSets[side]||[]){
  const mon=V2_monById(battle,command.actorId);if(!mon)continue;
  const roll=V2_nextRandom(rngState);rngState=roll.state;
  const move=command.kind==='move'?(command.moveId==='struggle'?V2_STRUGGLE:moves[command.moveId]):null;
  entries.push({side,command,actorId:command.actorId,switchRank:command.kind==='switch'?1:0,priority:move?.priority||0,speed:typeof V2_effectiveStat==='function'?V2_effectiveStat(mon,'spe',battle,side):mon.stats.spe,tieKey:roll.value});
 }
 entries.sort((a,b)=>b.switchRank-a.switchRank||b.priority-a.priority||b.speed-a.speed||b.tieKey-a.tieKey||a.actorId.localeCompare(b.actorId));
 return {queue:entries,rngState};
}
function V2_submitCommands(battle,side,commands,moves){
 const valid=V2_validateCommands(battle,side,commands,moves);if(!valid.ok)return valid;
 const next=JSON.parse(JSON.stringify(battle));next.pending=next.pending||{};next.pending[side]=valid.commands;
 if(!next.pending.A||!next.pending.B)return {ok:true,battle:next,ready:false};
 const built=V2_buildQueue(next,next.pending,moves);next.queue=built.queue;next.rngState=built.rngState;next.pending={};next.phase='RESOLVE';next.phaseRevision=(next.phaseRevision||0)+1;return {ok:true,battle:next,ready:true};
}
function V2_applySwitch(battle,side,actorId,toId){
 const slot=battle.sides[side].active.indexOf(actorId),reserve=V2_reserves(battle,side).find(mon=>mon.battleMonId===toId);
 if(slot<0||!reserve)return {ok:false,code:'INVALID_SWITCH'};
 const next=JSON.parse(JSON.stringify(battle)),out=V2_monById(next,actorId);out.stages={atk:0,def:0,spa:0,spd:0,spe:0};out.volatiles={};next.sides[side].active[slot]=toId;
 return {ok:true,battle:next,events:[{kind:'switchOut',actorId},{kind:'switchIn',actorId:toId,side,slot}]};
}

// ---- 40-v2-effect-catalog.js ----
const V2_ABILITY_IDS=['dawnbringer','raincaller','wild-growth','static-field','snowglobe','sandstream','tailwind','night-hunter','radiance','venom-touch','ironhide','mind-link','quick-start','keen-focus','sturdy-heart','rain-swimmer','clean-entry','water-shell','sun-runner','thorn-coat','healer','calm-mind','intimidator','steady-body'];
const V2_ITEM_IDS=['vital-seed','power-lens','aegis-plate','swift-feather','cure-berry','focus-crystal','healing-berry','clear-charm','weather-rock','terrain-root','special-lens','physical-band'];
const V2_ABILITY_HOOKS={dawnbringer:'onEntry',raincaller:'onEntry','wild-growth':'onEntry','static-field':'onEntry',snowglobe:'onEntry',sandstream:'onEntry',tailwind:'modifyStat','night-hunter':'modifyOutgoingDamage',radiance:'endTurn','venom-touch':'afterDamage',ironhide:'modifyIncomingDamage','mind-link':'modifyOutgoingDamage','quick-start':'modifyStat','keen-focus':'modifyAccuracy','sturdy-heart':'beforeDamage','rain-swimmer':'modifyStat','clean-entry':'onEntry','water-shell':'modifyIncomingDamage','sun-runner':'modifyStat','thorn-coat':'afterDamage',healer:'endTurn','calm-mind':'modifyStat',intimidator:'onEntry','steady-body':'onStatChange'};
const V2_ITEM_HOOKS={'vital-seed':'endTurn','power-lens':'modifyOutgoingDamage','aegis-plate':'modifyIncomingDamage','swift-feather':'modifyStat','cure-berry':'onStatusApplied','focus-crystal':'beforeDamage','healing-berry':'afterDamage','clear-charm':'onStatChange','weather-rock':'onFieldSet','terrain-root':'onFieldSet','special-lens':'modifyStat','physical-band':'modifyStat'};
function V2_clone(value){return JSON.parse(JSON.stringify(value));}

function V2_assertEffectCatalog(){const abilities=Object.keys(V2_ABILITY_HOOKS).sort(),items=Object.keys(V2_ITEM_HOOKS).sort();if(new Set(V2_ABILITY_IDS).size!==24||new Set(V2_ITEM_IDS).size!==12||abilities.join('|')!==[...V2_ABILITY_IDS].sort().join('|')||items.join('|')!==[...V2_ITEM_IDS].sort().join('|'))throw new Error('invalid effect catalog');return true;}

// ---- 41-v2-conditions.js ----
function V2_fieldDuration(mon,kind){return kind==='weather'&&mon.buildSnapshot.itemId==='weather-rock'||kind==='terrain'&&mon.buildSnapshot.itemId==='terrain-root'?7:5;}
function V2_setField(battle,kind,id,source){const next=V2_clone(battle),mon=V2_monById(next,source),remaining=V2_fieldDuration(mon,kind);next.field[kind]={id,remaining};return {battle:next,events:[{kind:'fieldChanged',field:kind,value:id,remaining,sourceId:source}]};}
function V2_setSideCondition(battle,side,id,remaining){const next=V2_clone(battle);next.field.sides[side][id]=remaining;return {battle:next,events:[{kind:'fieldChanged',field:'side',side,value:id,remaining}]};}
function V2_statusImmunity(mon,status){return status==='burn'&&mon.types.includes('Flame')||status==='poison'&&(mon.types.includes('Venom')||mon.types.includes('Steel'));}
function V2_applyStatus(mon,status,{fromFoe=true}={}){
 if(mon.hp<=0||mon.status||V2_statusImmunity(mon,status))return {applied:false,mon,events:[]};
 const next=V2_clone(mon);next.status=status==='sleep'?{id:'sleep',remainingActions:2}:status;
 const events=[{kind:'statusApplied',targetId:mon.battleMonId,status}];
 if(next.buildSnapshot.itemId==='cure-berry'&&!next.itemState.used){next.status=null;next.itemState.used=true;events.push({kind:'itemTriggered',sourceId:mon.battleMonId,itemId:'cure-berry'},{kind:'statusCured',targetId:mon.battleMonId,status});}
 return {applied:true,mon:next,events};
}
function V2_changeStage(mon,stat,amount,{fromFoe=true}={}){
 if(amount<0&&fromFoe&&(mon.buildSnapshot.abilityId==='steady-body'||mon.buildSnapshot.itemId==='clear-charm'))return {changed:false,mon};
 const next=V2_clone(mon),before=next.stages[stat]||0;next.stages[stat]=Math.max(-6,Math.min(6,before+amount));return {changed:next.stages[stat]!==before,mon:next};
}
function V2_sleepGate(mon){
 if(mon.status?.id!=='sleep')return {canAct:true,mon};
 const next=V2_clone(mon);if(next.status.remainingActions>0){next.status.remainingActions--;return {canAct:false,mon:next};}next.status=null;return {canAct:true,mon:next,woke:true};
}
function V2_guardAttempt(mon,rngState){
 const chain=mon.volatiles.guardChain||0,denominator=Math.min(81,3**chain),roll=V2_nextRandom(rngState),success=roll.value<1/denominator,next=V2_clone(mon);next.volatiles.guardChain=Math.min(4,chain+1);next.volatiles.guarded=success;return {success,mon:next,rngState:roll.state,denominator};
}
function V2_resetGuard(mon){const next=V2_clone(mon);next.volatiles.guardChain=0;next.volatiles.guarded=false;return next;}

// ---- 42-v2-modifiers.js ----
function V2_effectiveStat(mon,stat,battle,side){
 let value=mon.stats[stat]*V2_stageMultiplier(mon.stages?.[stat]);const ability=mon.buildSnapshot.abilityId,item=mon.buildSnapshot.itemId;
 if(stat==='def'&&battle.field.weather?.id==='snow'&&mon.types.includes('Frost'))value*=1.5;
 if(stat==='spe'){
  if(mon.status==='slow')value*=.5;if(battle.field.sides[side]?.tailwind>0)value*=2;
  if(ability==='tailwind')value*=1.3;if(ability==='quick-start'&&mon.hp===mon.stats.hp)value*=1.2;
  if(ability==='rain-swimmer'&&battle.field.weather?.id==='rain')value*=1.5;if(ability==='sun-runner'&&battle.field.weather?.id==='sun')value*=1.5;
  if(item==='swift-feather')value*=1.25;
 }
 if(stat==='spd'&&ability==='calm-mind')value*=1.2;if(stat==='spa'&&item==='special-lens')value*=1.15;if(stat==='atk'&&item==='physical-band')value*=1.15;
 return Math.max(1,Math.floor(value));
}
function V2_damageModifiers({attacker,defender,battle,attackerSide,defenderSide,move,allies=[]}){
 let outgoing=1,incoming=1,accuracy=move.accuracy;
 if(attacker.buildSnapshot.abilityId==='night-hunter'&&defender.hp*2<defender.stats.hp)outgoing*=1.25;
 if(attacker.buildSnapshot.abilityId==='keen-focus')accuracy=Math.min(100,accuracy+5);
 if(attacker.buildSnapshot.itemId==='power-lens')outgoing*=1.2;
 if(allies.some(mon=>mon.hp>0&&mon.battleMonId!==attacker.battleMonId&&mon.buildSnapshot.abilityId==='mind-link'))outgoing*=1.15;
 if(defender.buildSnapshot.abilityId==='ironhide')incoming*=.8;
 if(defender.buildSnapshot.abilityId==='water-shell'&&move.type==='Flame')incoming*=.5;
 if(defender.buildSnapshot.itemId==='aegis-plate')incoming*=.8;
 if(battle.field.sides[defenderSide]?.barrier>0)incoming*=.75;
 return {outgoing,incoming,accuracy};
}
function V2_surviveLethal(mon,damage,{residual=false}={}){
 if(residual||damage<mon.hp||mon.hp!==mon.stats.hp)return {damage,mon,trigger:null};
 const next=V2_clone(mon);
 if(next.buildSnapshot.abilityId==='sturdy-heart'&&!next.volatiles.sturdyUsed){next.volatiles.sturdyUsed=true;return {damage:mon.hp-1,mon:next,trigger:'sturdy-heart'};}
 if(next.buildSnapshot.itemId==='focus-crystal'&&!next.itemState.used){next.itemState.used=true;return {damage:mon.hp-1,mon:next,trigger:'focus-crystal'};}
 return {damage,mon,trigger:null};
}
function V2_afterDamage({attacker,defender,damage,move,rngState,moveTriedPoison=false,skipHealing=false,skipReactions=false}){
 let nextAttacker=V2_clone(attacker),nextDefender=V2_clone(defender),state=rngState,events=[];
 if(!skipHealing&&damage>0&&nextDefender.hp>0&&nextDefender.buildSnapshot.itemId==='healing-berry'&&!nextDefender.itemState.used&&nextDefender.hp*4<=nextDefender.stats.hp){const amount=Math.min(nextDefender.stats.hp-nextDefender.hp,Math.floor(nextDefender.stats.hp/4));nextDefender.hp+=amount;nextDefender.itemState.used=true;events.push({kind:'itemTriggered',itemId:'healing-berry',sourceId:nextDefender.battleMonId},{kind:'heal',targetId:nextDefender.battleMonId,amount,hpAfter:nextDefender.hp});}
 if(!skipReactions&&damage>0&&nextDefender.hp>0&&nextAttacker.buildSnapshot.abilityId==='venom-touch'&&!moveTriedPoison){const roll=V2_nextRandom(state);state=roll.state;if(roll.value<.3){const applied=V2_applyStatus(nextDefender,'poison');nextDefender=applied.mon;events.push(...applied.events);}}
 if(!skipReactions&&damage>0&&move.contact&&nextDefender.hp>0&&nextDefender.buildSnapshot.abilityId==='thorn-coat'){const amount=Math.min(nextAttacker.hp,Math.max(1,Math.floor(nextAttacker.stats.hp/16)));const hpBefore=nextAttacker.hp;nextAttacker.hp-=amount;events.push({kind:'abilityTriggered',abilityId:'thorn-coat',sourceId:nextDefender.battleMonId},{kind:'damage',targetId:nextAttacker.battleMonId,amount,hpBefore,hpAfter:nextAttacker.hp,source:'thorn-coat'});}
 return {attacker:nextAttacker,defender:nextDefender,rngState:state,events};
}

// ---- 43-v2-entry-effects.js ----
function V2_entryAbility(battle,side,monId){
 const mon=V2_monById(battle,monId),ability=mon.buildSnapshot.abilityId,weather={dawnbringer:'sun',raincaller:'rain',snowglobe:'snow',sandstream:'sand'},terrain={'wild-growth':'meadow','static-field':'storm'};
 if(weather[ability])return V2_setField(battle,'weather',weather[ability],monId);if(terrain[ability])return V2_setField(battle,'terrain',terrain[ability],monId);
 const next=V2_clone(battle),source=V2_monById(next,monId),events=[];
 if(ability==='clean-entry'&&source.status){const old=source.status?.id||source.status;source.status=null;events.push({kind:'abilityTriggered',abilityId:ability,sourceId:monId},{kind:'statusCured',targetId:monId,status:old});}
 if(ability==='intimidator')for(const target of V2_activeEntries(next,side==='A'?'B':'A')){const changed=V2_changeStage(target.mon,'atk',-1);Object.assign(target.mon,changed.mon);if(changed.changed)events.push({kind:'statChanged',targetId:target.mon.battleMonId,stat:'atk',amount:-1});}
 return {battle:next,events};
}
function V2_resolveEntry(battle,entries){
 let rngState=battle.rngState>>>0;const ordered=[];
 for(const entry of entries){const mon=V2_monById(battle,entry.monId),roll=V2_nextRandom(rngState);rngState=roll.state;if(mon)ordered.push({...entry,speed:V2_effectiveStat(mon,'spe',battle,entry.side),tieKey:roll.value});}
 ordered.sort((a,b)=>b.speed-a.speed||b.tieKey-a.tieKey||a.monId.localeCompare(b.monId));let current=V2_clone(battle),events=[];
 for(const entry of ordered){const result=V2_entryAbility(current,entry.side,entry.monId);current=result.battle;events.push(...result.events);}
 current.rngState=rngState;return {battle:current,events,order:ordered.map(entry=>entry.monId)};
}

// ---- 44-v2-move-effects.js ----
function V2_effectTargetIds(battle, entry, move, effect, hitTargetId) {
  if (effect.target === 'self') return [entry.actorId];
  if (effect.target === 'hitTarget') {
    if (hitTargetId) return [hitTargetId];
    return V2_resolveTargets(battle, entry.side, entry.actorId, move, entry.command.target).map(target => target.battleMonId);
  }
  if (effect.target === 'ally') {
    const targets = V2_resolveTargets(battle, entry.side, entry.actorId, {targetMode: 'ally'}, entry.command.target);
    return targets.map(target => target.battleMonId);
  }
  return [];
}

function V2_effectChance(chance, rngState) {
  if (chance === undefined || chance >= 1) return {passed: true, rngState};
  const roll = V2_nextRandom(rngState);
  return {passed: roll.value < chance, rngState: roll.state};
}

function V2_applyMoveEffects(battle, entry, move, timing, hitTargetId = null) {
  let current = V2_clone(battle);
  let rngState = current.rngState >>> 0;
  const events = [];
  for (const effect of (move.effects || []).filter(item => item.timing === timing)) {
    const chance = V2_effectChance(effect.chance, rngState);
    rngState = chance.rngState;
    if (!chance.passed) continue;
    const params = effect.params || {};
    if (effect.kind === 'setWeather') {
      const result = V2_setField(current, 'weather', params.id || params.weather, entry.actorId);
      current = result.battle; events.push(...result.events); continue;
    }
    if (effect.kind === 'setTerrain') {
      const result = V2_setField(current, 'terrain', params.id || params.terrain, entry.actorId);
      current = result.battle; events.push(...result.events); continue;
    }
    if (effect.kind === 'setSideCondition') {
      const result = V2_setSideCondition(current, entry.side, params.id, params.remaining);
      current = result.battle; events.push(...result.events); continue;
    }
    for (const targetId of V2_effectTargetIds(current, entry, move, effect, hitTargetId)) {
      let target = V2_monById(current, targetId);
      if (!target || target.hp <= 0 || (target.volatiles.guarded && target.ownerSide !== entry.side)) continue;
      if (effect.kind === 'applyStatus') {
        const result = V2_applyStatus(target, params.status);
        current = V2_setMon(current, result.mon); events.push(...result.events);
      } else if (effect.kind === 'changeStage') {
        const result = V2_changeStage(target, params.stat, params.amount, {fromFoe: target.ownerSide !== entry.side});
        current = V2_setMon(current, result.mon);
        if (result.changed) events.push({kind: 'statChanged', actorId: entry.actorId, targetId, stat: params.stat, amount: params.amount});
      } else if (effect.kind === 'heal') {
        const amount = Math.min(target.stats.hp - target.hp, Math.floor(target.stats.hp * params.fraction));
        target = V2_clone(target); target.hp += amount; current = V2_setMon(current, target);
        if (amount > 0) events.push({kind: 'heal', actorId: entry.actorId, targetId, amount, hpAfter: target.hp});
      } else if (effect.kind === 'redirect') {
        target = V2_clone(target); target.volatiles.redirect = true; target.volatiles.redirectOrder = current.eventSequence || 0;
        current = V2_setMon(current, target);
      }
    }
  }
  current.rngState = rngState;
  return {battle: current, events};
}

// ---- 50-v2-lifecycle.js ----
function V2_replaceMon(battle,updated){for(const side of ['A','B']){const index=battle.sides[side].roster.findIndex(mon=>mon.battleMonId===updated.battleMonId);if(index>=0){battle.sides[side].roster[index]=updated;return;}}}
function V2_applyHpGroup(battle,changes,source){
 const next=V2_clone(battle),events=[];
 for(const change of changes){const mon=V2_monById(next,change.monId);if(!mon||mon.hp<=0)continue;const before=mon.hp,after=Math.max(0,Math.min(mon.stats.hp,before+change.delta));mon.hp=after;const amount=Math.abs(after-before);if(!amount)continue;events.push({kind:change.delta<0?'damage':'heal',targetId:mon.battleMonId,hpBefore:before,hpAfter:after,amount,source});if(after===0)events.push({kind:'fainted',targetId:mon.battleMonId});}
 return {battle:next,events};
}
function V2_livingCount(battle,side){return battle.sides[side].roster.filter(mon=>mon.hp>0).length;}
function V2_finishBattle(battle,winner,reason){
 if(battle.result)return {battle,events:[]};const next=V2_clone(battle),receiptId=`${next.id}:result`;next.phase='FINISHED';next.phaseRevision=(next.phaseRevision||0)+1;next.result={winner,reason,turn:next.turn,receiptId};next.rewardReceipts=next.rewardReceipts||[];if(!next.rewardReceipts.some(entry=>entry.receiptId===receiptId))next.rewardReceipts.push({receiptId,battleId:next.id,winner,reason});return {battle:next,events:[{kind:'battleEnded',winner,reason,receiptId}]};
}
function V2_checkResult(battle,{turnCap=100}={}){const a=V2_livingCount(battle,'A'),b=V2_livingCount(battle,'B');if(!a&&!b)return V2_finishBattle(battle,null,'draw-ko');if(!a)return V2_finishBattle(battle,'B','all-fainted');if(!b)return V2_finishBattle(battle,'A','all-fainted');if(battle.turn>=turnCap)return V2_finishBattle(battle,null,'turn-cap');return {battle,events:[]};}
function V2_expireConditions(battle){
 const next=V2_clone(battle),events=[];
 for(const kind of ['weather','terrain']){const effect=next.field[kind];if(effect){effect.remaining--;if(effect.remaining<=0){events.push({kind:'effectExpired',field:kind,value:effect.id});next.field[kind]=null;}}}
 for(const side of ['A','B'])for(const id of ['tailwind','barrier'])if(next.field.sides[side][id]>0){next.field.sides[side][id]--;if(next.field.sides[side][id]===0)events.push({kind:'effectExpired',field:'side',side,value:id});}
 for(const side of ['A','B'])for(const {mon} of V2_activeEntries(next,side)){mon.volatiles.guarded=false;mon.volatiles.redirect=false;}
 return {battle:next,events};
}
function V2_endTurn(battle){
 if(battle.phase!=='END_TURN')return {ok:false,code:'WRONG_PHASE'};let current=V2_clone(battle),events=[];
 const active=()=>['A','B'].flatMap(side=>V2_activeEntries(current,side).map(entry=>({...entry,side})));
 let changes=active().flatMap(({mon})=>{const status=mon.status?.id||mon.status;if(status==='burn')return [{monId:mon.battleMonId,delta:-Math.max(1,Math.floor(mon.stats.hp/16))}];if(status==='poison')return [{monId:mon.battleMonId,delta:-Math.max(1,Math.floor(mon.stats.hp/8))}];return [];});let group=V2_applyHpGroup(current,changes,'major-status');current=group.battle;events.push(...group.events);
 if(current.field.weather?.id==='sand'){changes=active().filter(({mon})=>!mon.types.includes('Stone')&&!mon.types.includes('Steel')).map(({mon})=>({monId:mon.battleMonId,delta:-Math.max(1,Math.floor(mon.stats.hp/16))}));group=V2_applyHpGroup(current,changes,'sand');current=group.battle;events.push(...group.events);}
 changes=active().filter(({mon})=>mon.buildSnapshot.itemId==='vital-seed').map(({mon})=>({monId:mon.battleMonId,delta:Math.max(1,Math.floor(mon.stats.hp*.08))}));group=V2_applyHpGroup(current,changes,'vital-seed');current=group.battle;events.push(...group.events);
 changes=[];for(const {mon,side} of active())if(mon.buildSnapshot.abilityId==='radiance')changes.push({monId:mon.battleMonId,delta:Math.max(1,Math.floor(mon.stats.hp*.05))});else if(mon.buildSnapshot.abilityId==='healer'){const allies=V2_activeEntries(current,side).filter(entry=>entry.mon.battleMonId!==mon.battleMonId&&entry.mon.hp>0&&entry.mon.hp<entry.mon.stats.hp).sort((a,b)=>a.mon.hp/a.mon.stats.hp-b.mon.hp/b.mon.stats.hp||a.slot-b.slot);if(allies[0])changes.push({monId:allies[0].mon.battleMonId,delta:Math.max(1,Math.floor(allies[0].mon.stats.hp*.05))});}group=V2_applyHpGroup(current,changes,'ability');current=group.battle;events.push(...group.events);
 if(current.field.terrain?.id==='meadow'){changes=active().filter(({mon})=>!mon.types.includes('Gale')).map(({mon})=>({monId:mon.battleMonId,delta:Math.max(1,Math.floor(mon.stats.hp/16))}));group=V2_applyHpGroup(current,changes,'meadow');current=group.battle;events.push(...group.events);}
 const expired=V2_expireConditions(current);current=expired.battle;events.push(...expired.events,{kind:'turnEnded',turn:battle.turn});const result=V2_checkResult(current);current=result.battle;events.push(...result.events);
 if(current.phase!=='FINISHED'){const needs=['A','B'].some(side=>current.sides[side].active.some(id=>!id||V2_monById(current,id)?.hp<=0)&&V2_reserves(current,side).length);current.phase=needs?'REPLACE':'COMMAND';current.phaseRevision=(current.phaseRevision||0)+1;if(!needs)current.turn++;}
 return {ok:true,battle:current,events};
}
function V2_validateReplacements(battle,side,replacements){
 if(battle.phase!=='REPLACE')return {ok:false,code:'WRONG_PHASE'};const empty=battle.sides[side].active.map((id,slot)=>({id,slot})).filter(entry=>!entry.id||V2_monById(battle,entry.id)?.hp<=0),reserves=V2_reserves(battle,side),count=Math.min(empty.length,reserves.length);
 if(!Array.isArray(replacements)||replacements.length!==count)return {ok:false,code:'INVALID_REPLACEMENT_COUNT'};const slots=new Set(),ids=new Set();for(const choice of replacements)if(!empty.some(entry=>entry.slot===choice.slot)||!reserves.some(mon=>mon.battleMonId===choice.monId)||slots.has(choice.slot)||ids.has(choice.monId))return {ok:false,code:'INVALID_REPLACEMENT'};else{slots.add(choice.slot);ids.add(choice.monId);}return {ok:true,replacements:V2_clone(replacements)};
}
function V2_applyReplacements(battle,choicesBySide){
 const next=V2_clone(battle),events=[];for(const side of ['A','B']){const valid=V2_validateReplacements(next,side,choicesBySide[side]||[]);if(!valid.ok)return valid;for(const choice of valid.replacements){next.sides[side].active[choice.slot]=choice.monId;events.push({kind:'switchIn',actorId:choice.monId,side,slot:choice.slot,replacement:true});}}
 next.phase='ENTRY';next.phaseRevision=(next.phaseRevision||0)+1;next.turn++;return {ok:true,battle:next,events};
}

// ---- 55-v2-turn-resolution.js ----
function V2_setMon(battle, mon) {
  const next = V2_clone(battle);
  V2_replaceMon(next, mon);
  return next;
}

function V2_combatStats(mon, battle, side) {
  const copy = V2_clone(mon);
  for (const stat of ['atk', 'def', 'spa', 'spd']) {
    copy.stats[stat] = V2_effectiveStat(mon, stat, battle, side);
    copy.stages[stat] = 0;
  }
  return copy;
}

function V2_resolveAttack(battle, entry, move) {
  let current = V2_clone(battle);
  let rngState = current.rngState >>> 0;
  const rawEvents = [];
  const actor = V2_monById(current, entry.actorId);
  const spent = move.id === 'struggle' ? {ok: true, mon: actor} : V2_spendPp(actor, move.id);
  if (!spent.ok) return {battle: current, events: [{kind: 'moveFailed', actorId: entry.actorId, reason: 'noPP'}]};
  current = V2_setMon(current, spent.mon);
  rawEvents.push({kind: 'moveStarted', actorId: entry.actorId, moveId: move.id});

  const targets = V2_resolveTargets(current, entry.side, entry.actorId, move, entry.command.target);
  if (!targets.length) return {battle: current, events: [...rawEvents, {kind: 'moveFailed', actorId: entry.actorId, moveId: move.id, reason: 'noTarget'}]};
  const spread = move.targetMode === 'allFoes' && targets.length > 1 ? 0.75 : 1;
  let totalDamage = 0;

  for (const targetRef of targets.sort((a, b) => a.slot - b.slot)) {
    let attacker = V2_monById(current, entry.actorId);
    let defender = V2_monById(current, targetRef.battleMonId);
    if (!attacker || attacker.hp <= 0 || !defender || defender.hp <= 0) continue;
    if (defender.volatiles.guarded) {
      rawEvents.push({kind: 'guarded', actorId: entry.actorId, targetId: defender.battleMonId, moveId: move.id});
      continue;
    }
    const effectiveness = move.type ? V2_effectiveness(move.type, defender.types) : 1;
    if (effectiveness === 0) {
      rawEvents.push({kind: 'damage', actorId: entry.actorId, targetId: defender.battleMonId, moveId: move.id, hpBefore: defender.hp, hpAfter: defender.hp, amount: 0, effectiveness});
      continue;
    }
    const defenderSide = entry.side === 'A' ? 'B' : 'A';
    const allies = V2_activeEntries(current, entry.side).map(item => item.mon);
    const modifiers = V2_damageModifiers({attacker, defender, battle: current, attackerSide: entry.side, defenderSide, move, allies});
    const accuracy = V2_accuracyCheck(modifiers.accuracy, rngState);
    rngState = accuracy.rngState;
    if (!accuracy.hit) {
      rawEvents.push({kind: 'moveMissed', actorId: entry.actorId, targetId: defender.battleMonId, moveId: move.id});
      continue;
    }
    const damageInfo = move.id === 'struggle'
      ? V2_calculateDamage({...{move: {...move, type: null}}, attacker: V2_combatStats(attacker, current, entry.side), defender: V2_combatStats(defender, current, defenderSide), field: {}, spread})
      : V2_calculateDamage({move, attacker: V2_combatStats(attacker, current, entry.side), defender: V2_combatStats(defender, current, defenderSide), field: current.field, outgoing: modifiers.outgoing, incoming: modifiers.incoming, spread});
    const survived = V2_surviveLethal(defender, damageInfo.damage);
    defender = survived.mon;
    const hpBefore = defender.hp;
    const actual = Math.min(hpBefore, survived.damage);
    defender.hp -= actual;
    current = V2_setMon(current, defender);
    totalDamage += actual;
    if (survived.trigger) rawEvents.push({kind: survived.trigger === 'focus-crystal' ? 'itemTriggered' : 'abilityTriggered', sourceId: defender.battleMonId, effectId: survived.trigger});
    rawEvents.push({kind: 'damage', actorId: entry.actorId, targetId: defender.battleMonId, moveId: move.id, hpBefore, hpAfter: defender.hp, amount: actual, effectiveness});
    if (defender.hp === 0) rawEvents.push({kind: 'fainted', targetId: defender.battleMonId});

    const healed = V2_afterDamage({attacker: V2_monById(current, entry.actorId), defender: V2_monById(current, defender.battleMonId), damage: actual, move, rngState, skipReactions: true});
    rngState = healed.rngState; current = V2_setMon(V2_setMon(current, healed.attacker), healed.defender); rawEvents.push(...healed.events);
    if (actual > 0 && V2_monById(current, defender.battleMonId).hp > 0) {
      current.rngState = rngState;
      const secondary = V2_applyMoveEffects(current, entry, move, 'afterDamage', defender.battleMonId);
      current = secondary.battle; rngState = current.rngState; rawEvents.push(...secondary.events);
    }
    const triedPoison = (move.effects || []).some(effect => effect.timing === 'afterDamage' && effect.kind === 'applyStatus' && effect.params?.status === 'poison');
    const reacted = V2_afterDamage({attacker: V2_monById(current, entry.actorId), defender: V2_monById(current, defender.battleMonId), damage: actual, move, rngState, moveTriedPoison: triedPoison, skipHealing: true});
    rngState = reacted.rngState; current = V2_setMon(V2_setMon(current, reacted.attacker), reacted.defender); rawEvents.push(...reacted.events);
  }
  if (move.id === 'struggle' && totalDamage > 0) {
    const recoil = V2_struggleRecoil(totalDamage);
    const source = V2_monById(current, entry.actorId);
    const hpBefore = source.hp;
    source.hp = Math.max(0, source.hp - recoil);
    current = V2_setMon(current, source);
    rawEvents.push({kind: 'damage', actorId: entry.actorId, targetId: entry.actorId, moveId: move.id, hpBefore, hpAfter: source.hp, amount: hpBefore - source.hp, source: 'recoil'});
    if (source.hp === 0) rawEvents.push({kind: 'fainted', targetId: source.battleMonId});
  }
  current.rngState = rngState;
  return {battle: current, events: rawEvents};
}

function V2_resolveUtility(battle, entry, move) {
  let current = V2_clone(battle);
  const actor = V2_monById(current, entry.actorId);
  const spent = V2_spendPp(actor, move.id);
  if (!spent.ok) return {battle: current, events: [{kind: 'moveFailed', actorId: entry.actorId, reason: 'noPP'}]};
  current = V2_setMon(current, spent.mon);
  const events = [{kind: 'moveStarted', actorId: entry.actorId, moveId: move.id}];
  if (move.id === 'guard') {
    const guarded = V2_guardAttempt(V2_monById(current, entry.actorId), current.rngState);
    current = V2_setMon(current, guarded.mon);
    current.rngState = guarded.rngState;
    events.push({kind: guarded.success ? 'guarded' : 'moveFailed', actorId: entry.actorId, moveId: move.id, reason: guarded.success ? undefined : 'guardChain'});
    return {battle: current, events};
  }
  current = V2_setMon(current, V2_resetGuard(V2_monById(current, entry.actorId)));
  return V2_mergeResolution(current, events, V2_applyMoveEffects(current, entry, move, 'onUse'));
}

function V2_mergeResolution(battle, events, result) {
  return {battle: result.battle || battle, events: [...events, ...(result.events || [])]};
}

function V2_resolveTurn(battle, moves) {
  if (battle.phase !== 'RESOLVE') return {ok: false, code: 'WRONG_PHASE'};
  const input = JSON.stringify(battle);
  let current = V2_clone(battle);
  let rawEvents = [{kind: 'turnStarted', turn: current.turn}];
  for (const entry of current.queue || []) {
    const actor = V2_monById(current, entry.actorId);
    if (!actor || actor.hp <= 0 || !current.sides[entry.side].active.includes(entry.actorId)) {
      rawEvents.push({kind: 'moveFailed', actorId: entry.actorId, reason: 'actorUnavailable'});
      continue;
    }
    if (entry.command.kind === 'switch') {
      const switched = V2_applySwitch(current, entry.side, entry.actorId, entry.command.toId);
      if (!switched.ok) continue;
      current = switched.battle; rawEvents.push(...switched.events);
      const entered = V2_entryAbility(current, entry.side, entry.command.toId);
      current = entered.battle; rawEvents.push(...entered.events);
    } else {
      const sleep = V2_sleepGate(actor);
      current = V2_setMon(current, sleep.mon);
      if (!sleep.canAct) { rawEvents.push({kind: 'moveFailed', actorId: entry.actorId, reason: 'asleep'}); continue; }
      if (sleep.woke) rawEvents.push({kind: 'statusCured', targetId: entry.actorId, status: 'sleep'});
      const move = entry.command.moveId === 'struggle' ? V2_STRUGGLE : moves[entry.command.moveId];
      const result = move.category === 'status' ? V2_resolveUtility(current, entry, move) : V2_resolveAttack(current, entry, move);
      current = result.battle; rawEvents.push(...result.events);
    }
    const result = V2_checkResult(current);
    current = result.battle; rawEvents.push(...result.events);
    if (current.phase === 'FINISHED') break;
  }
  if (current.phase !== 'FINISHED') {
    current.phase = 'END_TURN'; current.phaseRevision = (current.phaseRevision || 0) + 1;
    const ended = V2_endTurn(current); current = ended.battle; rawEvents.push(...ended.events);
  }
  const committed = V2_commitEvents(current, rawEvents.map(event => ({...event, turn: event.turn ?? battle.turn})));
  if (JSON.stringify(battle) !== input) throw new Error('V2_resolveTurn mutated its input');
  return {ok: true, battle: committed.battle, events: committed.events};
}

// ---- 60-v2-events.js ----
const V2_EVENT_KINDS = new Set([
  'turnStarted', 'switchOut', 'switchIn', 'abilityTriggered', 'itemTriggered',
  'formChanged', 'moveStarted', 'moveFailed', 'moveMissed', 'guarded', 'damage',
  'heal', 'statusApplied', 'statusCured', 'statChanged', 'fieldChanged',
  'effectExpired', 'fainted', 'turnEnded', 'battleEnded'
]);

function V2_validateEvent(event) {
  if (!event || !V2_EVENT_KINDS.has(event.kind)) return {ok: false, reason: 'unknownKind'};
  if (event.kind === 'damage') {
    if (typeof event.targetId !== 'string' || !Number.isFinite(event.amount) || event.amount < 0) return {ok: false, reason: 'invalidDamage'};
    if (event.hpBefore !== undefined && (!Number.isFinite(event.hpBefore) || !Number.isFinite(event.hpAfter) || event.hpBefore - event.hpAfter !== event.amount)) return {ok: false, reason: 'invalidHpDelta'};
  }
  if (event.kind === 'heal' && (typeof event.targetId !== 'string' || !Number.isFinite(event.amount) || event.amount < 0)) return {ok: false, reason: 'invalidHeal'};
  return {ok: true};
}

function V2_commitEvents(battle, rawEvents, {depth = 0} = {}) {
  if (depth > 8) throw new Error('event dispatch depth exceeded');
  if (rawEvents.length > 256) throw new Error('event limit exceeded');
  const next = V2_clone(battle);
  let sequence = next.eventSequence || 0;
  const events = rawEvents.map(raw => {
    const valid = V2_validateEvent(raw);
    if (!valid.ok) throw new Error(`invalid event: ${valid.reason}`);
    return {...V2_clone(raw), id: `event-${++sequence}`, turn: raw.turn ?? next.turn};
  });
  next.eventSequence = sequence;
  next.events = [...(next.events || []), ...events];
  return {battle: next, events};
}

function V2_eventLogLine(event, names = {}) {
  const actor = names[event.actorId] || event.actorId || 'Battlefield';
  const target = names[event.targetId] || event.targetId || '';
  const messages = {
    turnStarted: `Turn ${event.turn} started`,
    switchOut: `${actor} withdrew`,
    switchIn: `${actor} entered the field`,
    abilityTriggered: `${names[event.sourceId] || event.sourceId}'s ${event.effectId || event.abilityId} activated`,
    itemTriggered: `${names[event.sourceId] || event.sourceId} used ${event.effectId || event.itemId}`,
    moveStarted: `${actor} used ${names[event.moveId] || event.moveId}`,
    moveFailed: `${actor}'s action failed: ${event.reason}`,
    moveMissed: `${actor} missed ${target}`,
    guarded: `${target || actor} guarded the attack`,
    damage: `${target} lost ${event.amount ?? Math.max(0,(event.hpPercentBefore||0)-(event.hpPercentAfter||0))+'%'} HP`,
    heal: `${target} recovered ${event.amount ?? Math.max(0,(event.hpPercentAfter||0)-(event.hpPercentBefore||0))+'%'} HP`,
    statusApplied: `${target} became ${event.status}`,
    statusCured: `${target} recovered from ${event.status}`,
    statChanged: `${target}'s ${event.stat} changed by ${event.amount}`,
    fieldChanged: `${event.field} became ${event.value}`,
    effectExpired: `${event.value} expired`,
    fainted: `${target} fainted`,
    turnEnded: `Turn ${event.turn} ended`,
    battleEnded: event.winner ? `${event.winner} won the battle` : 'The battle ended in a draw'
  };
  return messages[event.kind] || `[${event.kind}]`;
}

function V2_logPage(events, page = 0, pageSize = 20, names = {}) {
  const turns = [...new Set(events.map(event => event.turn))].sort((a, b) => b - a);
  const selected = new Set(turns.slice(page * pageSize, (page + 1) * pageSize));
  return events.filter(event => selected.has(event.turn)).map(event => ({id: event.id, turn: event.turn, text: V2_eventLogLine(event, names)}));
}

function V2_projectEvent(event, battle, viewerSide) {
  const projected = V2_clone(event);
  if (event.kind !== 'damage' && event.kind !== 'heal') return projected;
  const target = V2_monById(battle, event.targetId);
  if (!target || target.ownerSide === viewerSide) return projected;
  const max = target.stats.hp;
  projected.hpPercentBefore = Math.round((event.hpBefore ?? target.hp) / max * 100);
  projected.hpPercentAfter = Math.round((event.hpAfter ?? target.hp) / max * 100);
  delete projected.hpBefore; delete projected.hpAfter; delete projected.amount;
  return projected;
}

function V2_animationFrame(battle, viewerSide) {
  const frame = {};
  for (const side of ['A', 'B']) {
    const key = side === viewerSide ? 'allies' : 'enemies';
    frame[key] = battle.sides[side].active.map(id => {
      const mon = id ? V2_monById(battle, id) : null;
      return mon ? {id: mon.battleMonId, hp: mon.hp, max: mon.stats.hp, energy: 0, status: mon.status?.id || mon.status || null} : {id: null, hp: 0, max: 1, energy: 0, status: null};
    });
  }
  return frame;
}

function V2_toAnimationEvents(initialBattle, events, moves, viewerSide = 'A') {
  const state = V2_clone(initialBattle), result = [], activeMoves = new Map();
  const sideKey = side => side === viewerSide ? 'allies' : 'enemies';
  for (const event of events) {
    if (event.kind === 'moveStarted') { activeMoves.set(event.actorId, event.moveId); continue; }
    const target = event.targetId ? V2_monById(state, event.targetId) : null;
    if (target && Number.isFinite(event.hpAfter)) target.hp = event.hpAfter;
    if (target && event.kind === 'statusApplied') target.status = event.status;
    if (target && event.kind === 'statusCured') target.status = null;
    if (event.kind === 'switchIn') state.sides[event.side].active[event.slot] = event.actorId;
    if (event.kind === 'switchIn') {
      const mon = V2_monById(state, event.actorId);
      result.push({kind: event.replacement ? 'entry' : 'switch', side: sideKey(event.side), actor: event.slot, incoming: event.slot, name: mon?.speciesId || event.actorId, frame: V2_animationFrame(state, viewerSide)});
    } else if (event.kind === 'heal' && target) {
      const targetSlot = state.sides[target.ownerSide].active.indexOf(event.targetId);
      result.push({kind: 'upkeep', side: sideKey(target.ownerSide), actor: Math.max(0, targetSlot), name: target.speciesId || event.targetId, change: event.amount, frame: V2_animationFrame(state, viewerSide)});
    } else if (event.kind === 'fieldChanged') {
      const source = event.sourceId ? V2_monById(state, event.sourceId) : null;
      const sourceSide = source?.ownerSide || viewerSide;
      const sourceSlot = source ? state.sides[sourceSide].active.indexOf(source.battleMonId) : 0;
      const moveId = source ? activeMoves.get(source.battleMonId) : null;
      const move = moves[moveId] || {id: moveId || event.value, name: moveId || event.value, type: 'Astral', power: 0};
      result.push({kind: 'move', side: sideKey(sourceSide), actor: Math.max(0, sourceSlot), name: source?.speciesId || 'Battlefield', move: {name: move.name || move.id, type: move.type, power: 0, effect: 'weather', weather: event.value}, targets: [], frame: V2_animationFrame(state, viewerSide)});
    } else if (event.kind === 'damage' && target) {
      const actor = V2_monById(state, event.actorId), actorSide = actor?.ownerSide || target.ownerSide;
      const actorSlot = state.sides[actorSide].active.indexOf(event.actorId);
      const targetSlot = state.sides[target.ownerSide].active.indexOf(event.targetId);
      const move = moves[event.moveId] || {id: event.moveId || event.source, name: event.moveId || event.source, type: 'Venom', power: 0};
      result.push({kind: event.source && !event.moveId ? 'upkeep' : 'move', side: sideKey(actorSide), actor: Math.max(0, actorSlot), name: actor?.speciesId || event.actorId, move: {name: move.name || move.id, type: move.type, power: move.power, effect: move.targetMode === 'allFoes' ? 'spread' : 'damage'}, targets: [{side: sideKey(target.ownerSide), index: Math.max(0, targetSlot), damage: event.amount, effectiveness: event.effectiveness ?? 1, fainted: event.hpAfter === 0}], change: -event.amount, condition: event.source, frame: V2_animationFrame(state, viewerSide)});
    }
  }
  return result;
}

// ---- 65-v2-invariants.js ----
function V2_assertBattleInvariants(battle) {
  const occupied = new Set();
  for (const side of ['A', 'B']) {
    const rosterIds = new Set(battle.sides[side].roster.map(mon => mon.battleMonId));
    for (const id of battle.sides[side].active.filter(Boolean)) {
      if (!rosterIds.has(id)) throw new Error(`active mon ${id} is outside ${side} roster`);
      if (occupied.has(id)) throw new Error(`active mon ${id} occupies multiple slots`);
      occupied.add(id);
    }
    for (const mon of battle.sides[side].roster) {
      if (!Number.isFinite(mon.hp) || mon.hp < 0 || mon.hp > mon.stats.hp) throw new Error(`invalid HP for ${mon.battleMonId}`);
      for (const value of Object.values(mon.pp)) if (!Number.isInteger(value) || value < 0) throw new Error(`invalid PP for ${mon.battleMonId}`);
      for (const value of Object.values(mon.stages)) if (!Number.isInteger(value) || value < -6 || value > 6) throw new Error(`invalid stage for ${mon.battleMonId}`);
    }
  }
  const inspect = value => {
    if (value === undefined) throw new Error('battle contains undefined');
    if (typeof value === 'number' && !Number.isFinite(value)) throw new Error('battle contains a non-finite number');
    if (Array.isArray(value)) value.forEach(inspect);
    else if (value && typeof value === 'object') Object.values(value).forEach(inspect);
  };
  inspect(battle);
  const encoded = JSON.stringify(battle);
  if (JSON.stringify(JSON.parse(encoded)) !== encoded) throw new Error('battle is not JSON stable');
  return true;
}

// ---- 90-public-api.js ----

export const meta={game:"Pokémon Vanguard",minPlayers:1,maxPlayers:1};
const TYPES=["Flame","Tide","Bloom","Volt","Frost","Stone","Gale","Shadow","Light","Venom","Steel","Astral"];
const COLORS=["#ff9361","#5bd9ef","#9ee59c","#f3d76c","#b3e8ff","#d2b49a","#94dccf","#ac9fee","#ffe2a1","#d398e6","#a7bfd5","#faadda"];
const NAMES=["Emberlyn","Cindrake","Volcaram","Tideray","Coralisk","Shellure","Mossprout","Thornox","Florawisp","Voltkit","Stormaw","Ampillo","Frostowl","Glacirn","Snowmelt","Pebblit","Obsidon","Dunewyrm","Zephyroo","Galesong","Cyclopup","Gloomoth","Noctalon","Umbrawolf","Solmane","Aurorix","Lumifin","Venomble","Toxipede","Mirecap","Ironcub","Gearaptor","Chromantis","Astralyn","Runelisk","Orbitail"];
const SECOND=[6,5,10,6,9,10,6,5,8,7,6,10,6,8,1,1,10,7,5,8,3,9,6,11,0,11,1,1,5,2,5,6,2,7,5,1];
const ABILITIES=[
{name:"Dawnbringer",desc:"On entry, sets Sun for 5 turns. Flame damage ×1.5; Tide ×0.5.",weather:"Sun"},
{name:"Raincaller",desc:"On entry, sets Rain for 5 turns. Tide damage ×1.5; Flame ×0.5.",weather:"Rain"},
{name:"Wild Growth",desc:"On entry, sets Meadow for 5 turns. Bloom damage ×1.3; all active monsters heal 6% each turn.",weather:"Meadow"},
{name:"Static Field",desc:"On entry, sets Storm for 5 turns. Volt damage ×1.5.",weather:"Storm"},
{name:"Snowglobe",desc:"On entry, sets Snow for 5 turns. Frost defense ×1.5.",weather:"Snow"},
{name:"Sandstream",desc:"On entry, sets Sand for 5 turns. Non-Stone/Steel monsters lose 5% HP each turn.",weather:"Sand"},
{name:"Tailwind",desc:"Speed increases by 30%."},
{name:"Night Hunter",desc:"Deals 25% more damage to opponents below half HP."},
{name:"Radiance",desc:"Restores 5% of maximum HP at the end of each turn."},
{name:"Venom Touch",desc:"Damaging moves poison targets for 3 turns; Venom and Steel are immune."},
{name:"Ironhide",desc:"Reduces incoming damage by 20%."},
{name:"Mind Link",desc:"Your active partner deals 15% more damage in doubles."}
];
const ITEMS=[
{name:"None",desc:"No held item."},{name:"Vital Seed",desc:"Restore 8% HP at the end of each turn."},
{name:"Power Lens",desc:"Deal 20% more damage."},{name:"Aegis Plate",desc:"Receive 20% less damage."},
{name:"Swift Feather",desc:"Increase speed by 25%."},{name:"Cure Berry",desc:"Cures the first burn or poison each battle."},
{name:"Focus Crystal",desc:"Once per battle, survive a lethal hit at 1 HP if starting at full HP."}
];
const STRONG={Flame:["Bloom","Frost","Steel"],Tide:["Flame","Stone"],Bloom:["Tide","Stone"],Volt:["Tide","Gale"],Frost:["Bloom","Gale"],Stone:["Flame","Volt"],Gale:["Bloom","Venom"],Shadow:["Astral","Light"],Light:["Shadow","Venom"],Venom:["Bloom","Light"],Steel:["Frost","Light"],Astral:["Venom","Steel"]};
const RESIST={Flame:["Flame","Tide","Stone"],Tide:["Tide","Bloom"],Bloom:["Flame","Bloom","Gale","Steel"],Volt:["Volt","Bloom"],Frost:["Flame","Frost","Steel"],Stone:["Bloom","Steel"],Gale:["Volt","Steel"],Shadow:["Shadow","Steel"],Light:["Light","Steel"],Venom:["Venom","Stone"],Steel:["Flame","Tide","Steel"],Astral:["Astral"]};
const IMMUNE={Volt:["Stone"],Venom:["Steel"],Astral:["Shadow"]};
const MOVENAMES=["Ember Fang","Tidal Pulse","Vine Lash","Arc Bolt","Ice Shard","Stone Hammer","Wind Cutter","Night Slash","Solar Beam","Toxic Sting","Iron Claw","Mind Burst"];
const WEATHER=["Sun","Rain","Meadow","Storm","Snow","Sand"];
function species(id){
 const t=Math.floor(id/3), r=id%3;
 return {id,name:NAMES[id],types:[TYPES[t],TYPES[SECOND[id]]],color:COLORS[t],rarity:id>=32?"Legendary":r===2?"Epic":r===1?"Rare":"Common",ability:ABILITIES[t],hp:108+(id*7%29),attack:47+(id*11%22),defense:42+(id*13%22),speed:40+(id*17%45),moves:[
 {name:MOVENAMES[t],type:TYPES[t],power:55,cost:0,effect:t===0?"burn":t===9?"poison":t===4?"slow":"damage",desc:"Reliable single-target strike."},
 {name:TYPES[SECOND[id]]+" Lance",type:TYPES[SECOND[id]],power:80,cost:2,effect:"damage",desc:"Heavy single-target strike."},
 {name:t<6?WEATHER[t]+" Call":r===0?"Mend":r===1?"Guard":"Rally",type:TYPES[t],power:0,cost:2,effect:t<6?"weather":r===0?"heal":r===1?"guard":"boost",weather:t<6?WEATHER[t]:null,desc:t<6?"Sets "+WEATHER[t]+" for 5 turns.":r===0?"Restores 35% maximum HP.":r===1?"Blocks damage this turn. Acts first.":"Raises your attack 25% for this battle."},
 {name:TYPES[t]+" Tempest",type:TYPES[t],power:45,cost:3,effect:"spread",desc:"Hits every active opponent."}]};
}
function effectiveness(type,types){return types.reduce((v,t)=>v*(IMMUNE[type]?.includes(t)?0:STRONG[type]?.includes(t)?2:RESIST[type]?.includes(t)?.5:1),1);}
function rand(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function owned(id){return {id,level:5,item:0,xp:0};}
export function setup(players){
 let seed=982451653; for(const c of String(players[0]||"aether")) seed=(Math.imul(seed,31)+c.charCodeAt(0))>>>0;
 return {owner:players[0],seed,version:1,coins:2400,gems:1800,pity:0,summons:0,wins:0,badges:[],collection:[0,3,6,9,12,15].map(owned),team:[0,3,6,9],mail:[],battle:null,reveal:[],notice:"Welcome, Challenger. Your first six companions are ready."};
}
function active(b,side){return b[side].map((m,i)=>({m,i})).filter(x=>x.m.hp>0&&x.m.slot>=0);}
function unit(id,level,item,slot){const d=species(id); const max=d.hp+level*6; return {id,level,item,slot,hp:max,max,energy:5,status:null,statusTurns:0,boost:1,guard:false,used:false};}
function stat(m,key){let v=species(m.id)[key]+m.level*2;if(key==="speed"){if(Math.floor(m.id/3)===6)v*=1.3;if(m.item===4)v*=1.25;if(m.status==="slow")v*=.6;}return v;}
function entry(b,m){let a=species(m.id).ability;if(a.weather){b.weather=a.weather;b.weatherTurns=5;b.log.push(species(m.id).name+"'s "+a.name+" summoned "+a.weather+".");}}
function int(v,min,max){return Number.isInteger(v)&&v>=min&&v<=max;}
export function validateAction(s,p,a){
 const fail=error=>({ok:false,error});if(p!==s.owner)return fail("This is another player's adventure.");if(!a||typeof a!=="object")return fail("Invalid action.");
 const busy=s.battle&&!s.battle.result;
 if(a.type==="battle"){
 if(busy)return fail("Finish or surrender the current battle.");if(!["single","double"].includes(a.mode))return fail("Choose a battle format.");
 if(a.gym!==undefined&&(!int(a.gym,0,5)||a.gym>s.badges.length))return fail("Clear the previous gym first.");
 if(s.team.length<(a.mode==="double"?2:1))return fail("Add more monsters to your team.");return {ok:true};}
 if(a.type==="turn"){
 const b=s.battle;if(!busy)return fail("No battle in progress.");if(a.round!==b.round)return fail("That turn has already resolved.");
 let actors=active(b,"allies");
 if(!Array.isArray(a.commands)||a.commands.length!==actors.length)return fail("Choose an action for every active monster.");
 let used=[],switches=[];
 for(const c of a.commands){
 if(!c||!actors.some(x=>x.i===c.actor)||used.includes(c.actor))return fail("Invalid active monster.");used.push(c.actor);
 if(c.kind==="switch"){
 if(!int(c.to,0,b.allies.length-1)||b.allies[c.to].hp<=0||b.allies[c.to].slot>=0||switches.includes(c.to))return fail("Choose a healthy reserve.");switches.push(c.to);
 }else{
 if(c.kind!=="move"||!int(c.move,0,3))return fail("Choose a move.");
 const m=b.allies[c.actor],move=species(m.id).moves[c.move];
 if(m.energy<move.cost)return fail("Not enough energy. Use your basic move to recover.");
 if(move.power&&!active(b,"enemies").some(x=>x.i===c.target))return fail("Choose a living opponent.");
 }}
 return {ok:true};}
 if(a.type==="surrender")return busy?{ok:true}:fail("No battle in progress.");
 if(busy)return fail("Finish the battle before changing your roster.");
 if(a.type==="summon")return [1,10].includes(a.count)&&s.gems>=a.count*100?{ok:true}:fail("Summoning costs 100 crystals per pull.");
 if(a.type==="train"){const m=s.collection.find(x=>x.id===a.id);return m&&m.level<30&&s.coins>=m.level*30?{ok:true}:fail("Training needs coins; maximum level is 30.");}
 if(a.type==="equip")return s.collection.some(x=>x.id===a.id)&&int(a.item,0,6)?{ok:true}:fail("Choose an owned monster and valid item.");
 if(a.type==="team")return Array.isArray(a.ids)&&a.ids.length>=1&&a.ids.length<=4&&new Set(a.ids).size===a.ids.length&&a.ids.every(id=>s.collection.some(m=>m.id===id))?{ok:true}:fail("Your team needs 1–4 different owned monsters.");
 if(a.type==="claim")return int(a.id,0,2)&&!s.mail.includes(a.id)&&(a.id!==1||s.wins>=1)&&(a.id!==2||s.badges.length>=1)?{ok:true}:fail("Reward already claimed or milestone not reached.");
 return fail("Unknown action.");
}
function damage(b,m,t,mv,side){
 let multiplier=effectiveness(mv.type,species(t.id).types);
 if(species(m.id).types.includes(mv.type))multiplier*=1.25;
 if(b.weather==="Sun")multiplier*=mv.type==="Flame"?1.5:mv.type==="Tide"?.5:1;
 if(b.weather==="Rain")multiplier*=mv.type==="Tide"?1.5:mv.type==="Flame"?.5:1;
 if(b.weather==="Storm"&&mv.type==="Volt")multiplier*=1.5;
 if(b.weather==="Meadow"&&mv.type==="Bloom")multiplier*=1.3;
 if(b.weather==="Snow"&&species(t.id).types.includes("Frost"))multiplier/=1.5;
 if(m.item===2)multiplier*=1.2;if(t.item===3)multiplier*=.8;
 if(Math.floor(t.id/3)===10)multiplier*=.8;
 if(Math.floor(m.id/3)===7&&t.hp<t.max/2)multiplier*=1.25;
 if(active(b,side).some(x=>x.m!==m&&Math.floor(x.m.id/3)===11))multiplier*=1.15;
 if(m.status==="burn")multiplier*=.75;
 return Math.floor((mv.power*.55*stat(m,"attack")/stat(t,"defense")+8)*multiplier*m.boost);
}
function heal(m,n){m.hp=Math.min(m.max,m.hp+Math.max(1,Math.floor(n)));}
// Presentation events are emitted by the rules, never inferred from the text log.
// Each frame owns its snapshot so later actions cannot change earlier HP/slots.
function recordEvent(b,event){
 b.events.push({...event,frame:JSON.parse(JSON.stringify({allies:b.allies,enemies:b.enemies,weather:b.weather,weatherTurns:b.weatherTurns,log:b.log}))});
}
function execute(b,side,c){
 const other=side==="allies"?"enemies":"allies",m=b[side][c.actor];if(!m||m.hp<=0||m.slot<0)return;
 const name=species(m.id).name;
 if(c.kind==="switch"){const to=b[side][c.to];if(to&&to.hp>0&&to.slot<0){to.slot=m.slot;m.slot=-1;b.log.push(name+" switched to "+species(to.id).name+".");entry(b,to);return {kind:"switch",side,actor:c.actor,incoming:c.to,name:species(to.id).name};}return;}
 const mv=species(m.id).moves[c.move];if(m.energy<mv.cost)return;m.energy-=mv.cost;
 const event={kind:"move",side,actor:c.actor,name,move:{...mv},targets:[]};
 const beforeHp=m.hp;
 b.log.push(name+" used "+mv.name+".");
 if(mv.effect==="weather"){b.weather=mv.weather;b.weatherTurns=5;}
 else if(mv.effect==="heal")heal(m,m.max*.35);
 else if(mv.effect==="guard")m.guard=true;
 else if(mv.effect==="boost")m.boost=Math.min(2,m.boost+.25);
 else{
 let targets=mv.effect==="spread"?active(b,other):[{m:b[other][c.target]?.slot>=0&&b[other][c.target]?.hp>0?b[other][c.target]:active(b,other)[0]?.m}];
 for(const {m:t} of targets){if(!t)continue;const tn=species(t.id).name;
 const target={side:other,index:b[other].indexOf(t),damage:0,effectiveness:effectiveness(mv.type,species(t.id).types),blocked:!!t.guard};
 event.targets.push(target);
 if(t.guard){b.log.push(tn+" blocked the attack.");continue;}
 let d=damage(b,m,t,mv,side);const ef=effectiveness(mv.type,species(t.id).types);
 if(t.item===6&&!t.used&&t.hp===t.max&&d>=t.hp){d=t.hp-1;t.used=true;b.log.push(tn+"'s Focus Crystal activated.");}
 target.damage=Math.min(t.hp,d);
 t.hp=Math.max(0,t.hp-d);b.log.push(tn+" −"+d+" HP"+(ef===0?" · Immune":ef>1?" · Super effective!":ef<1?" · Resisted":"")+".");
 if(d>0&&t.hp>0){const status=Math.floor(m.id/3)===9?"poison":["burn","poison","slow"].includes(mv.effect)?mv.effect:null;
 if(status&&!t.status&&!(status==="poison"&&species(t.id).types.some(t=>["Venom","Steel"].includes(t)))&&!(status==="burn"&&species(t.id).types.includes("Flame"))){
 t.status=status;t.statusTurns=3;
 if(t.item===5&&!t.used){t.status=null;t.statusTurns=0;t.used=true;b.log.push(tn+"'s Cure Berry activated.");}
 }}
 target.status=t.status;target.fainted=t.hp===0;
 if(t.hp===0)b.log.push(tn+" fainted.");
 }}
 event.healing=m.hp-beforeHp;
 return event;
}
function finish(s){
 const b=s.battle;let win=b.enemies.every(m=>m.hp<=0),lose=b.allies.every(m=>m.hp<=0);
 if(!win&&!lose&&b.round<=80)return;
 const result=win?"Victory":lose?"Defeat":"Draw";b.result=result;
 let coins=win?180:60,gems=win?80:20;
 if(win&&b.gym!==null&&!s.badges.includes(b.gym)){s.badges.push(b.gym);coins+=500;gems+=300;}
 s.coins+=coins;s.gems+=gems;if(win)s.wins++;
 b.reward={coins,gems};s.notice=result+" · +"+coins+" coins · +"+gems+" crystals";
}

export function applyAction(state,p,a){
 if(!validateAction(state,p,a).ok)return state;
 const s=JSON.parse(JSON.stringify(state));s.reveal=[];
 if(a.type==="battle"){
 s.battleSerial=(s.battleSerial||0)+1;
 const gym=a.gym??null,level=gym!==null?5+gym*3:Math.max(4,Math.round(s.team.reduce((v,id)=>v+s.collection.find(m=>m.id===id).level,0)/s.team.length));
 let ids=gym!==null?[gym*6,gym*6+1,gym*6+2,gym*6+3]:Array.from({length:4},()=>Math.floor(rand(s)*36));
 const n=a.mode==="double"?2:1;
 s.battle={id:s.battleSerial,events:[],mode:a.mode,gym,round:1,weather:"Clear",weatherTurns:0,allies:s.team.map((id,i)=>{const m=s.collection.find(x=>x.id===id);return unit(id,m.level,m.item,i<n?i:-1);}),enemies:ids.map((id,i)=>unit(id,level,gym!==null?1+gym%6:0,i<n?i:-1)),log:["Battle begins. Choose your moves."],result:null};
 for(const side of ["enemies","allies"])for(const x of active(s.battle,side))entry(s.battle,x.m);
 }else if(a.type==="turn"){
 const b=s.battle;b.events=[];b.eventsRound=b.round;b.log=["Turn "+b.round];for(const side of ["allies","enemies"])for(const m of b[side])m.guard=false;
 let queue=a.commands.map(c=>({side:"allies",c}));
 for(const {m,i} of active(b,"enemies")){
 let best={score:-1,move:0,target:active(b,"allies")[0].i};
 species(m.id).moves.forEach((mv,k)=>{if(mv.cost>m.energy)return;for(const t of active(b,"allies")){let score=mv.power?damage(b,m,t.m,mv,"enemies")*(mv.effect==="spread"?active(b,"allies").length:1):mv.effect==="heal"&&m.hp<m.max*.45?m.max*.4:0;if(score>best.score)best={score,move:k,target:t.i};}});
 queue.push({side:"enemies",c:{kind:"move",actor:i,move:best.move,target:best.target}});
 }
 const priority=q=>q.c.kind==="switch"?10000:species(b[q.side][q.c.actor].id).moves[q.c.move].effect==="guard"?9000:stat(b[q.side][q.c.actor],"speed");
 queue.sort((x,y)=>priority(y)-priority(x));
 for(const q of queue){const event=execute(b,q.side,q.c);if(event)recordEvent(b,event);}
 for(const side of ["allies","enemies"]){
 for(const {m,i} of active(b,side)){
 const hpBefore=m.hp,condition=m.status;
 if(m.status==="poison"||m.status==="burn"){let loss=Math.max(1,Math.floor(m.max*.07));m.hp=Math.max(0,m.hp-loss);b.log.push(species(m.id).name+" −"+loss+" HP ("+m.status+").");}
 if(m.hp>0&&b.weather==="Sand"&&!species(m.id).types.some(t=>["Stone","Steel"].includes(t)))m.hp=Math.max(0,m.hp-Math.floor(m.max*.05));
 if(m.hp>0){if(m.item===1)heal(m,m.max*.08);if(Math.floor(m.id/3)===8)heal(m,m.max*.05);if(b.weather==="Meadow")heal(m,m.max*.06);}
 if(m.status&&--m.statusTurns<=0)m.status=null;
 m.energy=Math.min(5,m.energy+1);
 if(m.hp!==hpBefore)recordEvent(b,{kind:"upkeep",side,actor:i,name:species(m.id).name,condition:condition||b.weather,change:m.hp-hpBefore});
 }
 for(const m of b[side])if(m.hp<=0&&m.slot>=0){const slot=m.slot;m.slot=-1;const next=b[side].find(v=>v.hp>0&&v.slot<0);if(next){next.slot=slot;b.log.push(species(next.id).name+" entered the battle.");entry(b,next);recordEvent(b,{kind:"entry",side,actor:b[side].indexOf(next),name:species(next.id).name});}}
 }
 if(b.weatherTurns>0&&--b.weatherTurns===0){b.weather="Clear";b.log.push("The field returned to clear weather.");}
 b.round++;finish(s);
 }else if(a.type==="surrender"){s.battle.result="Surrendered";s.battle.reward={coins:0,gems:0};s.notice="Battle ended. Your team has recovered.";}
 else if(a.type==="summon"){
 s.gems-=a.count*100;
 for(let k=0;k<a.count;k++){
 s.pity++;s.summons++;const roll=rand(s);
 const rarity=s.pity>=50||roll<.02?"Legendary":s.summons%10===0||roll<.10?"Epic":roll<.40?"Rare":"Common";
 const pool=Array.from({length:36},(_,i)=>species(i)).filter(m=>m.rarity===rarity);let id=pool[Math.floor(rand(s)*pool.length)].id;if(rarity==="Legendary")s.pity=0;
 const duplicate=s.collection.some(m=>m.id===id);if(duplicate)s.coins+=150;else s.collection.push(owned(id));s.reveal.push({id,duplicate});
 }s.notice="Summoning complete. Duplicates convert to 150 coins.";
 }else if(a.type==="train"){const m=s.collection.find(x=>x.id===a.id);s.coins-=m.level*30;m.level++;s.notice=species(m.id).name+" reached level "+m.level+".";}
 else if(a.type==="equip"){s.collection.find(x=>x.id===a.id).item=a.item;s.notice=ITEMS[a.item].name+" equipped.";}
 else if(a.type==="team"){s.team=a.ids;s.notice="Battle team updated.";}
 else if(a.type==="claim"){s.mail.push(a.id);s.coins+=[500,400,800][a.id];s.gems+=[500,300,500][a.id];s.notice="Mailbox rewards claimed.";}
 return s;
}
export function isGameOver(){return {over:false};}
export function viewFor(s,p){
 if(p!==s.owner)return {spectator:true};
 const {seed,owner,...v}=s;
 return {...v,catalog:Array.from({length:36},(_,i)=>species(i)),items:ITEMS,types:TYPES,colors:COLORS,typeChart:TYPES.map(t=>TYPES.map(d=>effectiveness(t,[d])))};
}

export {V2_createBattleMon,V2_transition,V2_monById,V2_activeEntries,V2_reserves,V2_resolveTargets,V2_validateCommands,V2_submitCommands,V2_resolveEntry,V2_resolveTurn,V2_validateReplacements,V2_applyReplacements,V2_calculateDamage,V2_damageModifiers,V2_effectiveness,V2_effectiveStat,V2_logPage,V2_projectEvent,V2_toAnimationEvents,V2_assertBattleInvariants};
