import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {assetReleaseLocations,deploySupabaseAssetRelease,readLocalAssetRelease,verifyRemoteAssetRelease} from '../scripts/asset-release-lib.mjs';

const digest=body=>createHash('sha256').update(body).digest('hex');
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'pv-assets-b45-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'assets'));const body=Buffer.from('project-owned-fixture');await writeFile(path.join(root,'assets','icon.png'),body);const entry={id:'/assets/icon.png',path:'/assets/icon.png',sha256:digest(body),bytes:body.length,mime:'image/png',group:'shell',essential:true},release='sha256-'+digest(Buffer.from(`${entry.path}\0${entry.sha256}\0${entry.bytes}`)),manifest={schemaVersion:1,release,totals:{files:1,bytes:body.length},entries:[entry]},serialized=Buffer.from(JSON.stringify(manifest,null,2)+'\n');await writeFile(path.join(root,'asset-manifest.json'),serialized);return {root,body,serialized,release:await readLocalAssetRelease({publicDir:root})};}

test('release plan uses immutable encoded Supabase public paths and rejects unsafe configuration',()=>{const locations=assetReleaseLocations({supabaseUrl:'https://project.supabase.co',bucket:'pokemon-vanguard-assets',release:'sha256-'+'a'.repeat(64)});assert.equal(locations.prefix,'releases/sha256-'+'a'.repeat(64));assert.match(locations.publicBase,/\/storage\/v1\/object\/public\/pokemon-vanguard-assets\/releases\/sha256-/);assert.throws(()=>assetReleaseLocations({supabaseUrl:'http://project.supabase.co',bucket:'ok-name',release:'sha256-'+'a'.repeat(64)}),/HTTPS/);assert.throws(()=>assetReleaseLocations({supabaseUrl:'https://secret@project.supabase.co',bucket:'ok-name',release:'sha256-'+'a'.repeat(64)}),/credentials/);});

test('local release verification rejects changed bytes and a stale release identity',async t=>{const data=await fixture(t);await writeFile(path.join(data.root,'assets','icon.png'),'tampered');await assert.rejects(readLocalAssetRelease({publicDir:data.root}),/does not match manifest/);const parsed=JSON.parse(data.serialized);parsed.release='sha256-'+'b'.repeat(64);await writeFile(path.join(data.root,'asset-manifest.json'),JSON.stringify(parsed));await assert.rejects(readLocalAssetRelease({publicDir:data.root}),/release hash is stale/);});

test('Supabase deploy is immutable, keeps the secret off public reads, uploads manifest last, and verifies every hash',async t=>{const data=await fixture(t),uploads=[],publicReads=[],objects=new Map([['assets/icon.png',data.body],['asset-manifest.json',data.serialized]]),secret='server-secret';const fetchImpl=async(url,options={})=>{if(url.includes('/storage/v1/bucket/'))return new Response(JSON.stringify({public:true}),{status:200,headers:{'content-type':'application/json'}});if(options.method==='POST'){uploads.push({url,headers:options.headers,body:Buffer.from(options.body)});return new Response('{}',{status:200});}const key=[...objects.keys()].find(value=>url.endsWith(value));publicReads.push({url,headers:options.headers||{}});const body=objects.get(key);return new Response(body,{status:200,headers:{'content-length':String(body.length)}});};const result=await deploySupabaseAssetRelease({release:data.release,supabaseUrl:'https://project.supabase.co',bucket:'pokemon-vanguard-assets',secretKey:secret,fetchImpl,concurrency:2});assert.equal(result.files,2);assert.equal(uploads.length,2);assert.ok(uploads.at(-1).url.endsWith('/asset-manifest.json'));assert.equal(uploads[0].headers['x-upsert'],'false');assert.equal(uploads[0].headers['Cache-Control'],'max-age=31536000');assert.ok(uploads.every(call=>call.headers.Authorization===`Bearer ${secret}`));assert.ok(publicReads.every(call=>!JSON.stringify(call).includes(secret)));});

test('remote verification fails closed on tampered CDN bytes and accepts an exact duplicate release',async t=>{const data=await fixture(t),correct=new Map([['assets/icon.png',data.body],['asset-manifest.json',data.serialized]]),responseFor=url=>{const key=[...correct.keys()].find(value=>url.endsWith(value)),body=correct.get(key);return new Response(body,{status:200,headers:{'content-length':String(body.length)}});};await assert.rejects(verifyRemoteAssetRelease({release:data.release,supabaseUrl:'https://project.supabase.co',bucket:'pokemon-vanguard-assets',fetchImpl:async url=>url.endsWith('icon.png')?new Response('wrong',{status:200}):responseFor(url)}),/mismatch/);const duplicateFetch=async(url,options={})=>url.includes('/storage/v1/bucket/')?new Response(JSON.stringify({public:true}),{status:200,headers:{'content-type':'application/json'}}):options.method==='POST'?new Response('',{status:409}):responseFor(url);const result=await deploySupabaseAssetRelease({release:data.release,supabaseUrl:'https://project.supabase.co',bucket:'pokemon-vanguard-assets',secretKey:'server-secret',fetchImpl:duplicateFetch});assert.equal(result.files,2);});
