import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {RankedService,ensureRankedState} from '../server/ranked-v1.mjs';
import {TrainingPvpService} from '../server/training-pvp-v1.mjs';
import {PVP_TIMERS,chooseTimeoutCommands} from '../server/pvp-lifecycle.mjs';
import {createV3BetaProgression} from '../server/v3-progression.mjs';
import {v3Catalog} from '../server/v3-catalog.mjs';
import {createClientStateReceiver} from '../public/js/client-state-receiver.js';

const makeState=()=>({schemaVersion:3,seed:11,wins:0,badges:[],wallet:{coins:0,crystals:0,recruitmentTickets:0},progressionV3:createV3BetaProgression(v3Catalog)});
const linked=name=>({name,provider:'discord'});
const activeTeam=state=>state.progressionV3.teams.find(team=>team.teamId===state.progressionV3.activeTeamId);
function rankedHarness(){let now=1_000_000;const states=new Map([['a',makeState()],['b',makeState()]]);for(const state of states.values())ensureRankedState(state);const service=new RankedService({catalog:v3Catalog,clock:{now:()=>now},getState:id=>states.get(id),persist:async()=>{},notify:()=>{}});service.register('a',linked('Alpha'));service.register('b',linked('Bravo'));return {service,states,get now(){return now;},set now(value){now=value;}};}
async function matchRanked(ctx,{lock=true}={}){await ctx.service.action('a',linked('Alpha'),{type:'rankedV1.queue.join',mode:'single'});await ctx.service.action('b',linked('Bravo'),{type:'rankedV1.queue.join',mode:'single'});if(!lock)return;for(const [id,name] of [['a','Alpha'],['b','Bravo']]){const team=activeTeam(ctx.states.get(id));await ctx.service.action(id,linked(name),{type:'rankedV1.preview.lock',buildIds:team.buildIds.slice(0,3)});}}

test('PvP decision clock auto-submits a legal move after 45 seconds',async()=>{const ctx=rankedHarness();await matchRanked(ctx);const match=ctx.service.matches.get(ctx.service.playerMatch.get('a')),startRevision=match.battle.phaseRevision,commands=chooseTimeoutCommands(match.battle,v3Catalog,'A');assert.ok(commands?.length);assert.equal(ctx.service.viewFor('a',ctx.states.get('a')).battleV3.timing.decision.remainingMs,PVP_TIMERS.decisionMs);ctx.now+=PVP_TIMERS.decisionMs;await ctx.service.tick();assert.equal(match.lastAutoAction.kind,'command');assert.ok(match.lastTurnRaw);assert.notEqual(match.battle.phaseRevision,startRevision);});

test('two PvP clients render immediately while asset warming remains pending and server deadline keeps running',async()=>{const ctx=rankedHarness();await matchRanked(ctx);const received=[];for(const id of ['a','b']){const accept=createClientStateReceiver({root:{},warm:()=>new Promise(()=>{}),receive:view=>received.push([id,view.battleV3.timing.decision.deadlineAt])});accept(ctx.service.viewFor(id,ctx.states.get(id)));}assert.equal(received.length,2);assert.equal(received[0][1],received[1][1]);const match=ctx.service.matches.get(ctx.service.playerMatch.get('a')),revision=match.battle.phaseRevision;ctx.now+=PVP_TIMERS.decisionMs;await ctx.service.tick();assert.notEqual(match.battle.phaseRevision,revision);});

test('Ranked disconnect grace is 90 seconds and awards the connected trainer a normal win',async()=>{const ctx=rankedHarness();await matchRanked(ctx);const beforeA=ctx.states.get('a').rankedV1.rating,beforeB=ctx.states.get('b').rankedV1.rating;ctx.service.unregister('b');const match=ctx.service.matches.get(ctx.service.playerMatch.get('a')),lostSide=ctx.service.sideFor(match,'b');assert.equal(match.participants[lostSide].disconnectDeadlineAt,ctx.now+PVP_TIMERS.disconnectGraceMs);ctx.now+=PVP_TIMERS.disconnectGraceMs;await ctx.service.tick();assert.equal(match.settled,true);assert.equal(match.battle.result.winner,ctx.service.sideFor(match,'a'));assert.equal(match.battle.result.reason,'disconnect-timeout');assert.ok(ctx.states.get('a').rankedV1.rating>beforeA);assert.ok(ctx.states.get('b').rankedV1.rating<beforeB);});

test('Ranked simultaneous disconnect expiry becomes no-contest with no rating or record changes',async()=>{const ctx=rankedHarness();await matchRanked(ctx);const before={a:structuredClone(ctx.states.get('a').rankedV1),b:structuredClone(ctx.states.get('b').rankedV1)};ctx.service.unregister('a');ctx.service.unregister('b');const match=ctx.service.matches.get(ctx.service.playerMatch.get('a'));ctx.now+=PVP_TIMERS.disconnectGraceMs;await ctx.service.tick();assert.equal(match.settled,true);assert.equal(match.battle.result.winner,null);assert.equal(match.battle.result.reason,'both-disconnected');assert.equal(ctx.states.get('a').rankedV1.rating,before.a.rating);assert.equal(ctx.states.get('b').rankedV1.rating,before.b.rating);assert.equal(ctx.states.get('a').rankedV1.matches,before.a.matches);assert.equal(ctx.states.get('b').rankedV1.matches,before.b.matches);});

test('Friendly rooms expire when abandoned and active battles forfeit after disconnect grace',async()=>{let now=5_000_000;const states=new Map([['a',makeState()],['b',makeState()]]),service=new TrainingPvpService({catalog:v3Catalog,clock:{now:()=>now},getState:id=>states.get(id),notify:()=>{},isFriend:()=>true});service.register('a',linked('Alpha'));service.register('b',linked('Bravo'));const teamA=activeTeam(states.get('a')),teamB=activeTeam(states.get('b'));await service.action('a',linked('Alpha'),{type:'trainingPvpV1.room.create',mode:'single',teamId:teamA.teamId});const staleCode=service.viewFor('a').room.code;now+=PVP_TIMERS.friendlyWaitingRoomMs;service.tick();assert.equal(service.rooms.has(staleCode),false);
 await service.action('a',linked('Alpha'),{type:'trainingPvpV1.room.create',mode:'single',teamId:teamA.teamId});const code=service.viewFor('a').room.code;await service.action('b',linked('Bravo'),{type:'trainingPvpV1.room.join',code,teamId:teamB.teamId});await service.action('a',linked('Alpha'),{type:'trainingPvpV1.preview.lock',buildIds:teamA.buildIds.slice(0,3)});await service.action('b',linked('Bravo'),{type:'trainingPvpV1.preview.lock',buildIds:teamB.buildIds.slice(0,3)});service.unregister('b');now+=PVP_TIMERS.disconnectGraceMs;service.tick();const room=service.roomFor('a');assert.equal(room.finished,true);assert.equal(room.battle.result.winner,'A');assert.equal(room.battle.result.reason,'disconnect-timeout');});


test('PvP battle UI surfaces server deadlines and reconnect grace without owning the timer',async()=>{
 const screen=await readFile(new URL('../public/js/v3-battle-screen.js',import.meta.url),'utf8'),preview=await readFile(new URL('../public/js/v3-battle-preview.js',import.meta.url),'utf8'),clock=await readFile(new URL('../public/js/battle-clock.js',import.meta.url),'utf8'),css=await readFile(new URL('../public/pokemon-battle-shell.css',import.meta.url),'utf8');
 assert.match(screen,/renderBattleTiming\(view\)/);assert.match(preview,/renderBattleTiming\(view,\{preview:true\}\)/);assert.match(clock,/data-battle-deadline/);assert.match(clock,/RECONNECT/);assert.match(css,/battle-clock\.urgent/);
});
