import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {V3OverviewView} from '../public/js/v3-overview-view.js';
import {V3RecruitmentView} from '../public/js/v3-recruitment-view.js';
import {v3Catalog} from '../server/v3-catalog.mjs';
import {createV3BetaProgression} from '../server/v3-progression.mjs';
import {prepareV3RecruitmentState,v3RecruitmentView} from '../server/v3-recruitment-state.mjs';
import {applyV3RecruitmentAction} from '../server/v3-recruitment.mjs';

const art=id=>`<div class="art">${id}</div>`;
const makeState=(serverNow=100000000)=>{const raw={schemaVersion:3,seed:97,coins:5000,gems:0,recruitmentTickets:1,progressionV3:createV3BetaProgression(v3Catalog)};prepareV3RecruitmentState(raw,v3Catalog,serverNow);return {view:{trainingV3:raw.progressionV3,recruitmentV3:v3RecruitmentView(raw,v3Catalog,{serverNow}),coins:raw.coins,recruitmentTickets:raw.recruitmentTickets},raw};};

test('R3-98 Pokédex archive renders all 213 canonical non-Mega M-A entries with selector and detail pane',()=>{const {view}=makeState(),ui=new V3OverviewView(),html=ui.renderArchive(view,v3Catalog,{art});assert.equal((html.match(/data-v3-archive="select"/g)||[]).length,213);assert.match(html,/REGULATION M-A · POKÉDEX/);assert.match(html,/data-v3-archive-input="search"/);assert.match(html,/data-v3-archive-input="type"/);assert.match(html,/data-v3-archive-input="ownership"/);assert.match(html,/data-ui-scroll-key="pokedex-grid"/);assert.match(html,/pokedex-detail/);assert.equal(new Set(v3Catalog.species.map(entry=>entry.id)).size,213);});

test('R3-98 Pokédex filters search, type and ownership without mutating catalog scope',()=>{const {view}=makeState(),ui=new V3OverviewView();ui.archive.search='rotom';let entries=ui.filteredArchiveEntries(view,v3Catalog);assert.equal(entries.length,6);assert.ok(entries.every(entry=>entry.species.id.includes('rotom')));ui.archive.search='';ui.archive.type='electric';entries=ui.filteredArchiveEntries(view,v3Catalog);assert.ok(entries.length>0);assert.ok(entries.every(entry=>entry.species.types.includes('electric')));ui.archive.type='all';ui.archive.ownership='permanent';entries=ui.filteredArchiveEntries(view,v3Catalog);assert.equal(entries.length,view.trainingV3.mons.filter(mon=>mon.ownership==='permanent').length);assert.equal(v3Catalog.species.length,213);});

test('R3-98 Pokédex can update search state without replacing the active filter input',()=>{let changes=0;const ui=new V3OverviewView({onChange:()=>changes++});assert.equal(ui.handleArchiveInput({dataset:{v3ArchiveInput:'search'},value:'steel'},{notify:false}),true);assert.equal(ui.archive.search,'steel');assert.equal(changes,0);const client=fs.readFileSync(new URL('../public/client.js',import.meta.url),'utf8');assert.match(client,/function updateV3ArchiveInput/);assert.match(client,/currentResults\.replaceWith\(nextResults\)/);});

test('Pokédex card selection can update its detail pane without redrawing the scrollable list',()=>{const {view}=makeState();let changes=0;const ui=new V3OverviewView({onChange:()=>changes++});assert.equal(ui.handleArchiveClick({dataset:{v3Archive:'select',speciesId:'steelix'}},view,v3Catalog,{notify:false}),true);assert.equal(ui.archive.selectedId,'steelix');assert.equal(changes,0);const client=fs.readFileSync(new URL('../public/client.js',import.meta.url),'utf8');assert.match(client,/function updateV3ArchiveSelection/);assert.match(client,/currentDetail\.replaceWith\(nextDetail\)/);assert.match(fs.readFileSync(new URL('../public/js/client-shell-layout.js',import.meta.url),'utf8'),/data-ui-scroll-key="page-content"/);assert.match(client,/focus\(\{preventScroll:true\}\)/);});

test('Pokédex keeps every status filter available in its empty state and opens the selected owned build',()=>{const {view}=makeState(),ui=new V3OverviewView();ui.archive.ownership='trial-expired';ui.archive.search='definitely-no-such-pokemon';let html=ui.renderArchive(view,v3Catalog,{art});assert.match(html,/value="trial-expired" selected>Expired/);ui.archive.ownership='all';ui.archive.search='blastoise';html=ui.renderArchive(view,v3Catalog,{art});const build=view.trainingV3.builds.find(entry=>entry.monId===view.trainingV3.mons.find(mon=>mon.speciesId==='blastoise').monId);assert.match(html,new RegExp(`data-action="training:${build.buildId}"`));});

test('R3-98 Pokédex form tray groups canonical forms and legal Mega transformations',()=>{const {view}=makeState(),ui=new V3OverviewView();ui.archive.selectedId='charizard';const charizard=ui.archiveSelection(view,v3Catalog).entry,forms=ui.archiveForms(charizard,v3Catalog);assert.deepEqual(forms.map(form=>form.id),['charizard','charizard-mega-x','charizard-mega-y']);ui.archive.selectedId='lycanroc-midday';ui.archive.displayFormId=null;const lycanroc=ui.archiveSelection(view,v3Catalog).entry,lycanrocForms=ui.archiveForms(lycanroc,v3Catalog);assert.deepEqual(new Set(lycanrocForms.map(form=>form.id)),new Set(['lycanroc-midday','lycanroc-dusk','lycanroc-midnight']));});

test('R3-98 Pokédex page actions cycle forms and cancel clears filters before leaving the screen',()=>{const {view}=makeState(),ui=new V3OverviewView();ui.archive.selectedId='charizard';ui.renderArchive(view,v3Catalog,{art});const before=ui.archive.displayFormId;assert.equal(ui.handleArchiveUiAction('PAGE_RIGHT',view,v3Catalog),true);assert.notEqual(ui.archive.displayFormId,before);ui.archive.search='char';assert.equal(ui.handleArchiveCancel(),true);assert.equal(ui.archive.displayFormId,null);assert.equal(ui.handleArchiveCancel(),true);assert.equal(ui.archive.search,'');});

test('R3-98 Roster Ranch renders ten offer selectors and only the selected offer action panel',()=>{const {view}=makeState(),changes=[],sent=[],ui=new V3RecruitmentView({onChange:()=>changes.push('change'),sendAction:action=>sent.push(action),createActionId:kind=>`id:${kind}`});let html=ui.render(view,v3Catalog,{art});assert.equal((html.match(/data-v3-recruit="select"/g)||[]).length,10);assert.equal((html.match(/data-v3-recruit="trial"/g)||[]).length,1);const second=view.recruitmentV3.offers[1];assert.equal(ui.handleClick({dataset:{v3Recruit:'select',speciesId:second.speciesId}},view),true);assert.equal(ui.selectedId,second.speciesId);assert.equal(changes.length,1);html=ui.render(view,v3Catalog,{art});assert.match(html,new RegExp(`ranch-offer-${second.speciesId}`));assert.match(html,/SAMPLE BUILD/);assert.equal(sent.length,0);});

test('Recruitment card selection can update its detail pane without redrawing the scrollable list',()=>{const {view}=makeState(),changes=[],ui=new V3RecruitmentView({onChange:()=>changes.push('change')});const offer=view.recruitmentV3.offers[1];assert.equal(ui.handleClick({dataset:{v3Recruit:'select',speciesId:offer.speciesId}},view,{notify:false}),true);assert.equal(ui.selectedId,offer.speciesId);assert.equal(changes.length,0);const client=fs.readFileSync(new URL('../public/client.js',import.meta.url),'utf8');assert.match(client,/function updateV3RecruitmentSelection/);assert.match(client,/current\.querySelector\('\.ranch-offer\.selected'\)/);});

test('R3-98 Roster Ranch keeps revision-safe authoritative recruitment actions and client management integration',()=>{const {view}=makeState(),sent=[],ui=new V3RecruitmentView({sendAction:action=>sent.push(action),createActionId:kind=>`id:${kind}`}),offer=view.recruitmentV3.offers.find(entry=>entry.ownership==='locked')||view.recruitmentV3.offers[0];ui.handleClick({dataset:{v3Recruit:'permanent',speciesId:offer.speciesId,payment:'ticket'}},view);assert.deepEqual(sent[0],{type:'recruitV3.permanent',actionId:'id:recruitV3.permanent',expectedRevision:view.recruitmentV3.revision,cycleId:view.recruitmentV3.cycleId,speciesId:offer.speciesId,payment:'ticket'});const client=fs.readFileSync(new URL('../public/client.js',import.meta.url),'utf8');for(const route of ['training','teams','collection','recruitment'])assert.match(client,new RegExp(`page==='${route}'`));assert.match(client,/data-v3-archive/);});

test('Roster Ranch updates only its countdown text and requests an authoritative sync at a deadline',()=>{const {view}=makeState(),sent=[];let mono=1000,redraws=0;view.recruitmentV3.cycleEndsAt=view.recruitmentV3.effectiveNow+5000;const countdown={dataset:{ranchCountdown:String(view.recruitmentV3.cycleEndsAt),ranchCountdownPrefix:'Cycle ends in '},textContent:''},previousDocument=globalThis.document;globalThis.document={querySelectorAll:()=>[countdown]};try{const ui=new V3RecruitmentView({onChange:()=>redraws++,sendAction:action=>sent.push(action),createActionId:kind=>`id:${kind}`,monotonicNow:()=>mono});ui.startTicker=()=>{};ui.render(view,v3Catalog,{art});assert.equal(ui.now(),view.recruitmentV3.effectiveNow);mono+=4000;assert.equal(ui.now(),view.recruitmentV3.effectiveNow+4000);ui.tick();assert.match(countdown.textContent,/^Cycle ends in /);assert.equal(redraws,0);assert.equal(sent.length,0);mono+=1001;ui.tick();assert.deepEqual(sent,[{type:'recruitV3.sync',actionId:'id:recruitV3.sync'}]);ui.tick();assert.equal(sent.length,1);}finally{if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument;}});

test('authoritative Recruitment sync rolls an elapsed cycle without charging currency',()=>{const {raw}=makeState(),beforeCoins=raw.wallet.coins,oldCycle=raw.recruitmentV3.cycleId,serverNow=(oldCycle+1)*v3Catalog.economy.recruitment.cycleDurationMs+1,result=applyV3RecruitmentAction(raw,{type:'recruitV3.sync',actionId:'sync:rollover'},v3Catalog,{serverNow});assert.equal(result.ok,true);assert.equal(result.state.wallet.coins,beforeCoins);assert.ok(result.state.recruitmentV3.cycleId>oldCycle);assert.equal(result.state.recruitmentV3.refreshCount,0);});
