import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {HANDLER_DEFINITIONS,activateHeldItem,compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,effectiveBattleSpeed,heldItemId,resolveEndTurnAbilityBerryRestores,resolveEndTurnItemAbilityLifecycle,resolveHpThresholdItems,resolvePostMoveItemTransferAbilities,transferHeldItem,validateMechanicManifest} from '../mechanics-v3/index.mjs';

const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['cud-chew','gluttony','magician','pickpocket','pickup','sticky-hold','symbiosis'];
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
const effects=(abilityId,itemId=null)=>compilePassiveEffects({abilityId,itemId,manifests});
const unit=(actorId,overrides={})=>({actorId,types:['normal'],hp:300,maxHp:300,stats:{hp:300,atk:120,def:120,spa:120,spd:120,spe:100},pp:{hit:16},maxPp:{hit:16},status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},itemState:createHeldItemState(null),itemHistory:[],...overrides});
function fixture(format='single'){const count=format==='double'?2:1,a=[unit('a1'),unit('a2')],b=[unit('b1'),unit('b2')];return {id:`ability-wave13-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:1,activeCount:count,rngState:1,field:{},sides:{A:{active:a.slice(0,count).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,count).map(x=>x.actorId),roster:b,conditions:{}}}};}
const move=(id='hit',type='normal',category='physical',power=80,accuracy=100)=>({id,name:id,type,category,power,accuracy,maxPP:16,contact:false});
const mechanics=(overrides={})=>({targetMode:'adjacentFoe',redirectable:true,priority:0,contact:false,tags:[],handlers:[],...overrides});

for(const format of ['single','double'])test(`r3-ability-hooks-wave13:${format} compiles and validates promoted abilities`,()=>{for(const id of ids){assert.deepEqual(validateMechanicManifest(manifests.abilities[id],'abilities'),[],id);assert.ok(effects(id).length,id);}});

test('Gluttony expands Berry threshold to half HP only for Berries',()=>{let battle=fixture();let a=battle.sides.A.roster[0];a.hp=135;a.itemState=createHeldItemState('pinch-berry');a.passiveEffects=[...effects('gluttony'),{sourceKind:'item',sourceId:'pinch-berry',kind:'item-threshold-heal',order:50,thresholdNumerator:1,thresholdDenominator:4,healNumerator:1,healDenominator:4}];let r=resolveHpThresholdItems(battle,{actorIds:['a1']});assert.equal(r.battle.sides.A.roster[0].hp,210);assert.ok(r.events.some(e=>e.abilityId==='gluttony'));battle=fixture();a=battle.sides.A.roster[0];a.hp=135;a.itemState=createHeldItemState('pinch-herb');a.passiveEffects=[...effects('gluttony'),{sourceKind:'item',sourceId:'pinch-herb',kind:'item-threshold-heal',order:50,thresholdNumerator:1,thresholdDenominator:4,healNumerator:1,healDenominator:4}];r=resolveHpThresholdItems(battle,{actorIds:['a1']});assert.equal(r.battle.sides.A.roster[0].hp,135);});

test('Cud Chew replays consumed Berry at end of next turn',()=>{let battle=fixture();const a=battle.sides.A.roster[0];a.hp=120;a.itemState=createHeldItemState('sitrus-berry');a.passiveEffects=[...effects('cud-chew'),...effects(null,'sitrus-berry')];let r=activateHeldItem(battle,{actorId:'a1',itemId:'sitrus-berry',reason:'hp-threshold',consume:true});assert.equal(r.battle.sides.A.roster[0].abilityState['berry-replay:cud-chew'].dueTurn,2);r=resolveEndTurnItemAbilityLifecycle(r.battle);assert.equal(r.battle.sides.A.roster[0].hp,120);r.battle.turn=2;r=resolveEndTurnItemAbilityLifecycle(r.battle);assert.equal(r.battle.sides.A.roster[0].hp,195);assert.ok(r.events.some(e=>e.abilityId==='cud-chew'));});

test('Symbiosis passes item immediately with donor provenance',()=>{const battle=fixture('double'),consumer=battle.sides.A.roster[0],donor=battle.sides.A.roster[1];consumer.itemState=createHeldItemState('sitrus-berry');consumer.passiveEffects=effects(null,'sitrus-berry');donor.itemState=createHeldItemState('leftovers');donor.passiveEffects=[...effects('symbiosis'),...effects(null,'leftovers')];const r=activateHeldItem(battle,{actorId:'a1',itemId:'sitrus-berry',reason:'hp-threshold',consume:true});assert.equal(heldItemId(r.battle.sides.A.roster[0]),'leftovers');assert.equal(heldItemId(r.battle.sides.A.roster[1]),null);assert.ok(r.events.some(e=>e.abilityId==='symbiosis'&&e.sourceId==='a2'&&e.targetId==='a1'));});

test('Cud Chew replay survives Symbiosis filling the item slot',()=>{let battle=fixture('double');const consumer=battle.sides.A.roster[0],donor=battle.sides.A.roster[1];consumer.hp=100;consumer.itemState=createHeldItemState('sitrus-berry');consumer.passiveEffects=[...effects('cud-chew'),...effects(null,'sitrus-berry')];donor.itemState=createHeldItemState('leftovers');donor.passiveEffects=[...effects('symbiosis'),...effects(null,'leftovers')];let r=activateHeldItem(battle,{actorId:'a1',itemId:'sitrus-berry',reason:'hp-threshold',consume:true});r.battle.turn=2;r=resolveEndTurnItemAbilityLifecycle(r.battle);assert.equal(r.battle.sides.A.roster[0].hp,175);assert.equal(heldItemId(r.battle.sides.A.roster[0]),'leftovers');});

test('Magician steals after damage and runtime handler is wired once per move',()=>{let battle=fixture();battle.sides.A.roster[0].passiveEffects=effects('magician');battle.sides.B.roster[0].itemState=createHeldItemState('leftovers');battle.sides.B.roster[0].passiveEffects=effects(null,'leftovers');let r=resolvePostMoveItemTransferAbilities(battle,{actorId:'a1',move:move(),mechanics:mechanics(),damagedTargetIds:['b1']});assert.equal(heldItemId(r.battle.sides.A.roster[0]),'leftovers');assert.ok(r.events.some(e=>e.abilityId==='magician'));
 battle=fixture();battle.sides.A.roster[0].passiveEffects=effects('magician');battle.sides.B.roster[0].itemState=createHeldItemState('leftovers');battle.sides.B.roster[0].passiveEffects=effects(null,'leftovers');const registry=createHookRegistry(HANDLER_DEFINITIONS),resolve=createMoveActionHandler({moves:{hit:move()},manifests:{hit:{id:'hit',targetMode:'adjacentFoe',redirectable:true,priority:0,contact:false,handlers:[{id:'spend-pp',hook:'onTryMove',order:10},{id:'deal-direct-damage',hook:'onMove',order:100}],testEvidence:{single:['wave13'],double:['wave13']}}},registry});r=resolve(battle,{kind:'move',side:'A',actorId:'a1',moveId:'hit',target:{side:'B',slot:0},priority:0,speed:100},{nextRandom:()=>0.5});assert.equal(heldItemId(r.battle.sides.A.roster[0]),'leftovers');assert.equal(r.events.filter(e=>e.reason==='item-steal-on-hit'&&e.kind==='itemTransferred').length,1);});

test('Pickpocket steals contact item unless secondaries are suppressed',()=>{let battle=fixture();battle.sides.A.roster[0].itemState=createHeldItemState('choice-scarf');battle.sides.A.roster[0].passiveEffects=effects(null,'choice-scarf');battle.sides.B.roster[0].passiveEffects=effects('pickpocket');let r=resolvePostMoveItemTransferAbilities(battle,{actorId:'a1',move:move(),mechanics:mechanics({contact:true}),damagedTargetIds:['b1']});assert.equal(heldItemId(r.battle.sides.B.roster[0]),'choice-scarf');battle=fixture();battle.sides.A.roster[0].itemState=createHeldItemState('choice-scarf');battle.sides.A.roster[0].passiveEffects=effects(null,'choice-scarf');battle.sides.B.roster[0].passiveEffects=effects('pickpocket');r=resolvePostMoveItemTransferAbilities(battle,{actorId:'a1',move:move(),mechanics:mechanics({contact:true,secondaryEffectsSuppressed:true}),damagedTargetIds:['b1']});assert.equal(heldItemId(r.battle.sides.A.roster[0]),'choice-scarf');});

test('Sticky Hold blocks generic transfer and Magician',()=>{let battle=fixture();battle.sides.B.roster[0].itemState=createHeldItemState('leftovers');battle.sides.B.roster[0].passiveEffects=[...effects('sticky-hold'),...effects(null,'leftovers')];let r=transferHeldItem(battle,{fromId:'b1',toId:'a1'});assert.equal(r.blocked,true);assert.ok(r.events.some(e=>e.abilityId==='sticky-hold'));battle.sides.A.roster[0].passiveEffects=effects('magician');r=resolvePostMoveItemTransferAbilities(battle,{actorId:'a1',move:move(),mechanics:mechanics(),damagedTargetIds:['b1']});assert.equal(heldItemId(r.battle.sides.A.roster[0]),null);});

test('Pickup deterministically claims current-turn consumed items once each',()=>{let battle=fixture('double');battle.sides.A.roster[1].passiveEffects=effects('pickup');battle.sides.B.roster[1].passiveEffects=effects('pickup');battle.sides.A.roster[0].itemState=createHeldItemState('sitrus-berry');battle.sides.A.roster[0].passiveEffects=effects(null,'sitrus-berry');battle.sides.B.roster[0].itemState=createHeldItemState('leppa-berry');battle.sides.B.roster[0].passiveEffects=effects(null,'leppa-berry');let r=activateHeldItem(battle,{actorId:'a1',itemId:'sitrus-berry',reason:'hp-threshold',consume:true});r=activateHeldItem(r.battle,{actorId:'b1',itemId:'leppa-berry',reason:'pp-restore',consume:true});r=resolveEndTurnItemAbilityLifecycle(r.battle);const got=[heldItemId(r.battle.sides.A.roster[1]),heldItemId(r.battle.sides.B.roster[1])];assert.deepEqual(new Set(got),new Set(['sitrus-berry','leppa-berry']));assert.equal(r.events.filter(e=>e.kind==='abilityTriggered'&&e.abilityId==='pickup').length,2);});

test('hostile item transfer activates shared Unburden item-loss state',()=>{const battle=fixture(),donor=battle.sides.B.roster[0];donor.itemState=createHeldItemState('choice-scarf');donor.passiveEffects=[...effects('unburden'),...effects(null,'choice-scarf')];assert.equal(effectiveBattleSpeed(battle,donor),150);const r=transferHeldItem(battle,{fromId:'b1',toId:'a1',reason:'item-steal-on-hit'});assert.equal(effectiveBattleSpeed(r.battle,r.battle.sides.B.roster[0]),200);});

test('item ownership loss does not masquerade as Berry consumption for Harvest',()=>{const battle=fixture();const donor=battle.sides.B.roster[0];donor.itemState=createHeldItemState('sitrus-berry');donor.passiveEffects=[...effects('harvest'),...effects(null,'sitrus-berry')];let r=transferHeldItem(battle,{fromId:'b1',toId:'a1',reason:'item-steal-on-hit'});assert.equal(r.battle.sides.B.roster[0].itemState.lostReason,'item-steal-on-hit');r=resolveEndTurnAbilityBerryRestores(r.battle);assert.equal(heldItemId(r.battle.sides.B.roster[0]),null);assert.equal(heldItemId(r.battle.sides.A.roster[0]),'sitrus-berry');assert.equal(r.events.some(e=>e.abilityId==='harvest'),false);});
