import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {HANDLER_DEFINITIONS,activeAbilityId,applyMechanicsSwitch,compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,resolveAllyFaintAbilityCopies,resolveContactAbilityReplacement,resolveEntryAbilities,resolveEntryHazards,resolveMechanicsEndTurn,validateMechanicManifest} from '../mechanics-v3/index.mjs';

const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['trace','receiver','mummy','wandering-spirit'];
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
const effects=(abilityId,itemId=null)=>compilePassiveEffects({abilityId,itemId,manifests});
const unit=(actorId,overrides={})=>({actorId,types:['normal'],hp:300,maxHp:300,stats:{hp:300,atk:120,def:120,spa:120,spd:120,spe:100},pp:{hit:16},maxPp:{hit:16},status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},itemState:createHeldItemState(null),buildSnapshot:{abilityId:null,itemId:null,moveIds:['hit']},...overrides});
function setAbility(mon,id,itemId=null){mon.activeAbilityId=id;mon.buildSnapshot.abilityId=id;mon.buildSnapshot.itemId=itemId;mon.passiveEffects=effects(id,itemId);mon.itemState=createHeldItemState(itemId);return mon;}
function fixture(format='single'){const count=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`ability-wave14-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:1,activeCount:count,rngState:1,field:{},sides:{A:{active:a.slice(0,count).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,count).map(x=>x.actorId),roster:b,conditions:{}}}};}
const move=(id='hit',type='normal',category='physical',power=80,accuracy=100)=>({id,name:id,type,category,power,accuracy,maxPP:16,contact:true});
const mechanics=(overrides={})=>({targetMode:'adjacentFoe',redirectable:true,priority:0,contact:true,tags:[],handlers:[],...overrides});

for(const format of ['single','double'])test(`r3-ability-hooks-wave14:${format} compiles and validates promoted abilities`,()=>{for(const id of ids){assert.deepEqual(validateMechanicManifest(manifests.abilities[id],'abilities'),[],id);assert.ok(effects(id).length,id);}});

test('Trace copies opposing active Ability and copied entry effects activate immediately',()=>{const battle=fixture();setAbility(battle.sides.A.roster[0],'trace');setAbility(battle.sides.B.roster[0],'intimidate');const result=resolveEntryAbilities(battle,[{kind:'switchIn',side:'A',slot:0,actorId:'a1'}],{manifests});const actor=result.battle.sides.A.roster[0];assert.equal(activeAbilityId(actor),'intimidate');assert.equal(result.battle.sides.B.roster[0].stages.atk,-1);assert.ok(result.events.some(e=>e.abilityId==='trace'&&e.copiedAbilityId==='intimidate'));});

test('Trace selects deterministically in Double and skips unsupported form-defining candidates',()=>{let battle=fixture('double');setAbility(battle.sides.A.roster[0],'trace');setAbility(battle.sides.B.roster[0],'overgrow');setAbility(battle.sides.B.roster[1],'torrent');battle.rngState=0xffffffff;let result=resolveEntryAbilities(battle,[{kind:'switchIn',side:'A',slot:0,actorId:'a1'}],{manifests});assert.ok(['overgrow','torrent'].includes(activeAbilityId(result.battle.sides.A.roster[0])));const first=activeAbilityId(result.battle.sides.A.roster[0]);result=resolveEntryAbilities(battle,[{kind:'switchIn',side:'A',slot:0,actorId:'a1'}],{manifests});assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),first);
 battle=fixture('double');setAbility(battle.sides.A.roster[0],'trace');battle.sides.B.roster[0].activeAbilityId='disguise';battle.sides.B.roster[0].passiveEffects=[{sourceKind:'ability',sourceId:'disguise',kind:'fixture'}];setAbility(battle.sides.B.roster[1],'torrent');result=resolveEntryAbilities(battle,[{kind:'switchIn',side:'A',slot:0,actorId:'a1'}],{manifests});assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'torrent');});

test('transient copied Ability restores on switch-out after copied switch-out hooks resolve',()=>{const battle=fixture();setAbility(battle.sides.A.roster[0],'trace');setAbility(battle.sides.B.roster[0],'natural-cure');battle.sides.A.roster[0].status={id:'burn'};const entered=resolveEntryAbilities(battle,[{kind:'switchIn',side:'A',slot:0,actorId:'a1'}],{manifests});assert.equal(activeAbilityId(entered.battle.sides.A.roster[0]),'natural-cure');const switched=applyMechanicsSwitch(entered.battle,'A','a1','a3',{manifests});assert.equal(switched.ok,true);assert.equal(switched.battle.sides.A.roster[0].status,null);assert.equal(activeAbilityId(switched.battle.sides.A.roster[0]),'trace');assert.ok(switched.events.some(e=>e.kind==='abilityRestored'&&e.abilityId==='trace'));});

test('Mummy replaces contact attacker Ability while preserving item passive effects and restores on switch',()=>{let battle=fixture();setAbility(battle.sides.A.roster[0],'overgrow','choice-scarf');setAbility(battle.sides.B.roster[0],'mummy');let result=resolveContactAbilityReplacement(battle,{attackerId:'a1',targetId:'b1',move:move(),mechanics:mechanics(),damage:40,manifests});let actor=result.battle.sides.A.roster[0];assert.equal(activeAbilityId(actor),'mummy');assert.ok(actor.passiveEffects.some(e=>e.sourceKind==='item'&&e.sourceId==='choice-scarf'));assert.ok(result.events.some(e=>e.abilityId==='mummy'&&e.kind==='abilityTriggered'));const switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests});assert.equal(activeAbilityId(switched.battle.sides.A.roster[0]),'overgrow');
 battle=fixture();setAbility(battle.sides.A.roster[0],'overgrow');setAbility(battle.sides.B.roster[0],'mummy');result=resolveContactAbilityReplacement(battle,{attackerId:'a1',targetId:'b1',move:move(),mechanics:mechanics({contact:false}),damage:40,manifests});assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'overgrow');});

test('Wandering Spirit swaps active Abilities on damaging contact and both restore after leaving field',()=>{const battle=fixture();setAbility(battle.sides.A.roster[0],'overgrow');setAbility(battle.sides.B.roster[0],'wandering-spirit');const result=resolveContactAbilityReplacement(battle,{attackerId:'a1',targetId:'b1',move:move(),mechanics:mechanics(),damage:50,manifests});assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'wandering-spirit');assert.equal(activeAbilityId(result.battle.sides.B.roster[0]),'overgrow');assert.equal(result.events.filter(e=>e.kind==='abilityChanged').length,2);let switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests});assert.equal(activeAbilityId(switched.battle.sides.A.roster[0]),'overgrow');switched=applyMechanicsSwitch(switched.battle,'B','b1','b3',{manifests});assert.equal(activeAbilityId(switched.battle.sides.B.roster[0]),'wandering-spirit');});

test('Receiver copies a fainted ally Ability only while active and restores on switch',()=>{const battle=fixture('double');setAbility(battle.sides.A.roster[0],'receiver');setAbility(battle.sides.A.roster[1],'torrent');battle.sides.A.roster[1].hp=0;const result=resolveAllyFaintAbilityCopies(battle,{faintedId:'a2',manifests});assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'torrent');assert.ok(result.events.some(e=>e.abilityId==='receiver'&&e.copiedAbilityId==='torrent'));const switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests});assert.equal(activeAbilityId(switched.battle.sides.A.roster[0]),'receiver');});

test('runtime damage wiring triggers Mummy and Receiver through the shared hit path',()=>{let battle=fixture('double');setAbility(battle.sides.A.roster[0],'overgrow');setAbility(battle.sides.B.roster[0],'mummy');battle.sides.B.roster[0].hp=300;const registry=createHookRegistry(HANDLER_DEFINITIONS),moveManifest={id:'hit',targetMode:'adjacentFoe',redirectable:true,priority:0,contact:true,handlers:[{id:'spend-pp',hook:'onTryMove',order:10},{id:'deal-direct-damage',hook:'onMove',order:100}],testEvidence:{single:['wave14'],double:['wave14']}},resolve=createMoveActionHandler({moves:{hit:move('hit','normal','physical',40)},manifests:{hit:moveManifest},abilityManifests:manifests,registry});let r=resolve(battle,{kind:'move',side:'A',actorId:'a1',moveId:'hit',target:{side:'B',slot:0},priority:0,speed:100},{nextRandom:()=>0.99});assert.equal(activeAbilityId(r.battle.sides.A.roster[0]),'mummy');
 battle=fixture('double');setAbility(battle.sides.A.roster[0],'overgrow');setAbility(battle.sides.B.roster[0],'receiver');setAbility(battle.sides.B.roster[1],'torrent');battle.sides.B.roster[1].hp=1;const killer=createMoveActionHandler({moves:{hit:move('hit','normal','physical',200)},manifests:{hit:moveManifest},abilityManifests:manifests,registry});r=killer(battle,{kind:'move',side:'A',actorId:'a1',moveId:'hit',target:{side:'B',slot:1},priority:0,speed:100},{nextRandom:()=>0.99});assert.equal(r.battle.sides.B.roster[1].hp,0);assert.equal(activeAbilityId(r.battle.sides.B.roster[0]),'torrent');assert.ok(r.events.some(e=>e.abilityId==='receiver'));});


test('Receiver copies an ally Ability when entry hazards cause the ally to faint',()=>{const battle=fixture('double');setAbility(battle.sides.A.roster[0],'receiver');setAbility(battle.sides.A.roster[1],'torrent');battle.sides.A.roster[1].hp=1;battle.sides.A.conditions['stealth-rock']={id:'stealth-rock',layers:1,sourceActorId:'b1',sourceMoveId:'stealth-rock',order:1};const result=resolveEntryHazards(battle,[{kind:'switchIn',side:'A',slot:1,actorId:'a2'}],{manifests});assert.equal(result.battle.sides.A.roster[1].hp,0);assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'torrent');assert.ok(result.events.some(e=>e.abilityId==='receiver'&&e.copiedAbilityId==='torrent'));});

test('Receiver copies an ally Ability when end-turn residual damage causes the ally to faint',()=>{const battle=fixture('double');battle.phase='END_TURN';setAbility(battle.sides.A.roster[0],'receiver');setAbility(battle.sides.A.roster[1],'torrent');battle.sides.A.roster[1].hp=1;battle.sides.A.roster[1].status={id:'poison',sourceActorId:'b1',sourceMoveId:'toxic'};const result=resolveMechanicsEndTurn(battle,[],{manifests});assert.equal(result.battle.sides.A.roster[1].hp,0);assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'torrent');assert.ok(result.events.some(e=>e.abilityId==='receiver'&&e.copiedAbilityId==='torrent'));});
