import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-candidates/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves={'shed-tail':byId['shed-tail']},registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:1001,maxHp:1001,stats:{hp:1001,atk:180,def:180,spa:180,spd:180,spe:100},pp:{'shed-tail':20},maxPp:{'shed-tail':20},status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:['shed-tail']},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2')];return {id:`wave47-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:82,activeCount:n,rngState:47,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(switchToId='a3')=>({kind:'move',side:'A',actorId:'a1',moveId:'shed-tail',target:{side:'A',slot:0},switchToId,moveType:'normal',moveCategory:'status',priority:0,speed:100});const runtime={nextRandom:()=>0,hasActed:()=>false,willMove:()=>true};

test('r3-move-hooks-wave47:single/double promotes Shed Tail with pivot validation evidence',()=>{assert.deepEqual(manifests.moves['shed-tail'].testEvidence,{single:['r3-move-hooks-wave47:single'],double:['r3-move-hooks-wave47:double']});assert.equal(validateAction(fixture(),action()).ok,true);assert.equal(validateAction(fixture(),{...action(),switchToId:undefined}).code,'PIVOT_SWITCH_TARGET_REQUIRED');});

test('Shed Tail pays half max HP rounded up, switches, and gives the replacement a quarter-max substitute',()=>{const battle=fixture(),result=resolveMove(battle,action(),runtime),out=result.battle.sides.A.roster.find(x=>x.actorId==='a1'),incoming=result.battle.sides.A.roster.find(x=>x.actorId==='a3');assert.equal(out.hp,500);assert.equal(result.battle.sides.A.active[0],'a3');assert.equal(incoming.volatiles.substitute.hp,250);assert.equal(incoming.volatiles.substitute.transferred,true);assert.ok(result.events.some(e=>e.kind==='substituteCreated'&&e.actorId==='a3'&&e.transferred));});

test('Shed Tail fails atomically when the user cannot afford the half-HP cost',()=>{const battle=fixture();battle.sides.A.roster[0].hp=501;const before=structuredClone(battle),result=resolveMove(battle,action(),runtime);assert.equal(result.battle.sides.A.active[0],'a1');assert.equal(result.battle.sides.A.roster[0].hp,501);assert.equal(result.battle.sides.A.roster[2].volatiles.substitute,undefined);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='insufficientHp'));assert.equal(before.sides.A.roster[0].hp,501);});

test('Shed Tail transfers only the new Substitute, not the outgoing user stat stages or unrelated volatiles',()=>{const battle=fixture();battle.sides.A.roster[0].stages.atk=3;battle.sides.A.roster[0].volatiles.marker={id:'marker',remaining:2};const result=resolveMove(battle,action(),runtime),incoming=result.battle.sides.A.roster.find(x=>x.actorId==='a3');assert.equal(incoming.stages.atk,0);assert.equal(incoming.volatiles.marker,undefined);assert.ok(incoming.volatiles.substitute);});


test('Shed Tail fails behind an existing Substitute and triggers threshold berries before switching',()=>{let battle=fixture();battle.sides.A.roster[0].volatiles.substitute={id:'substitute',hp:200,maxHp:250};let result=resolveMove(battle,action(),runtime);assert.equal(result.battle.sides.A.active[0],'a1');assert.equal(result.battle.sides.A.roster[0].hp,1001);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='substituteAlreadyActive'));battle=fixture();const actor=battle.sides.A.roster[0];actor.buildSnapshot.itemId='sitrus-berry';actor.itemState=createHeldItemState('sitrus-berry');actor.passiveEffects=compilePassiveEffects({itemId:'sitrus-berry',manifests});result=resolveMove(battle,action(),runtime);const outgoing=result.battle.sides.A.roster.find(x=>x.actorId==='a1');assert.equal(outgoing.hp,750);assert.equal(outgoing.itemState.consumed,true);const berryIndex=result.events.findIndex(e=>e.kind==='itemConsumed'&&e.itemId==='sitrus-berry'),switchIndex=result.events.findIndex(e=>e.kind==='switchOut'&&e.actorId==='a1');assert.ok(berryIndex>=0&&switchIndex>berryIndex);});
