import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {applyMechanicsSwitch,compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS,tryBeforeMoveConditions,variableMovePower} from '../mechanics-v3/index.mjs';
import {battleFoundation,canFlingItem,deterministicBattleGender,effectiveWeightKg} from '../mechanics-v3/foundation-data.mjs';

const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const ids=['attract','fling','low-kick','grass-knot','heavy-slam','heat-crash'];
const moves=Object.fromEntries(catalog.filter(move=>ids.includes(move.id)).map(move=>[move.id,move]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
function unit(actorId,{gender='male',weightKg=100,itemId=null,abilityId=null,moveIds=ids,types=['normal'],hp=500}={}){return {actorId,speciesId:'venusaur',baseSpeciesId:'venusaur',types:[...types],weightKg,gender,level:50,hp,maxHp:500,stats:{hp:500,atk:160,def:150,spa:160,spd:150,spe:100},stages:stages(),status:null,volatiles:{},pp:Object.fromEntries(moveIds.map(id=>[id,20])),maxPp:Object.fromEntries(moveIds.map(id=>[id,20])),passiveEffects:(abilityId||itemId&&manifests.items?.[itemId])?compilePassiveEffects({abilityId,itemId:itemId&&manifests.items?.[itemId]?itemId:null,manifests}):[],abilityState:{},itemState:createHeldItemState(itemId),buildSnapshot:{moveIds:[...moveIds],abilityId,itemId}};}
function fixture(format='single',a1={},b1={}){const n=format==='double'?2:1,a=[unit('a1',a1),unit('a2',{moveIds:[]}),unit('a3',{moveIds:[]})],b=[unit('b1',{gender:'female',...b1,moveIds:[]}),unit('b2',{gender:'female',moveIds:[]}),unit('b3',{gender:'female',moveIds:[]})];return {id:`wave51-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:51,activeCount:n,rngState:51,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=id=>({kind:'move',side:'A',actorId:'a1',moveId:id,target:{side:'B',slot:0},priority:0,speed:100});
const safeRuntime={nextRandom:()=>.99,hasActed:()=>false,willMove:()=>true};
const power=result=>result.events.find(event=>event.kind==='powerResolved')?.power;

test('r3-move-hooks-wave51:single/double promotes the six foundation-backed moves with shared evidence',()=>{for(const id of ids)assert.deepEqual(manifests.moves[id].testEvidence,{single:['r3-move-hooks-wave51:single'],double:['r3-move-hooks-wave51:double']},id);});

test('foundation covers battle forms/items and deterministic gender plus Autotomize-aware effective weight',()=>{const foundation=battleFoundation();assert.ok(Object.keys(foundation.species).length>=61);assert.equal(Object.keys(foundation.items).length,166);assert.equal(canFlingItem('kings-rock'),true);assert.equal(canFlingItem('venusaurite'),false);assert.equal(deterministicBattleGender('primarina','same-key'),deterministicBattleGender('primarina','same-key'));assert.equal(effectiveWeightKg({weightKg:118,volatiles:{'weight-reduction':{reductionHg:1000}}}),18);assert.equal(effectiveWeightKg({weightKg:85.5,volatiles:{'weight-reduction':{reductionHg:1000}}}),.1);});

test('Low Kick and Grass Knot use the canonical target-weight tiers, including Autotomize-modified weight',()=>{const actor=unit('a1'),target=unit('b1');for(const [weight,expected] of [[9.9,20],[10,40],[24.9,40],[25,60],[49.9,60],[50,80],[99.9,80],[100,100],[199.9,100],[200,120]]){target.weightKg=weight;target.volatiles={};assert.equal(variableMovePower('target-weight-tier',{battle:{},actor,target}),expected,weight);}target.weightKg=118;target.volatiles={'weight-reduction':{reductionHg:1000}};assert.equal(variableMovePower('target-weight-tier',{battle:{},actor,target}),40);for(const id of ['low-kick','grass-knot']){const result=resolveMove(fixture('single',{}, {weightKg:118}),action(id),safeRuntime);assert.equal(power(result),100,id);}});

test('Heavy Slam and Heat Crash use user/target weight ratio tiers in single and double',()=>{const actor=unit('a1'),target=unit('b1');for(const [ratio,expected] of [[1.99,40],[2,60],[2.99,60],[3,80],[3.99,80],[4,100],[4.99,100],[5,120]]){actor.weightKg=ratio*10;target.weightKg=10;assert.equal(variableMovePower('user-target-weight-ratio',{battle:{},actor,target}),expected,ratio);}for(const format of ['single','double'])for(const id of ['heavy-slam','heat-crash']){const result=resolveMove(fixture(format,{weightKg:100},{weightKg:20}),action(id),safeRuntime);assert.equal(power(result),120,`${format}:${id}`);}});

test('Attract requires opposite binary genders, respects Oblivious/Mental Herb, and blocks actions half the time',()=>{let result=resolveMove(fixture(),action('attract'),safeRuntime);let target=result.battle.sides.B.roster[0];assert.equal(target.volatiles.infatuation.sourceId,'a1');let gated=tryBeforeMoveConditions(result.battle,{kind:'move',side:'B',actorId:'b1',moveId:'fixture'},{nextRandom:()=>0});assert.equal(gated.cancelled,true);assert.ok(gated.events.some(e=>e.kind==='actionPrevented'&&e.status==='infatuation'));gated=tryBeforeMoveConditions(result.battle,{kind:'move',side:'B',actorId:'b1',moveId:'fixture'},{nextRandom:()=>.99});assert.equal(gated.cancelled,false);
 result=resolveMove(fixture('single',{}, {gender:'male'}),action('attract'),safeRuntime);assert.equal(result.battle.sides.B.roster[0].volatiles.infatuation,undefined);assert.ok(result.events.some(e=>e.reason==='genderMismatch'));
 result=resolveMove(fixture('single',{}, {abilityId:'oblivious'}),action('attract'),safeRuntime);assert.equal(result.battle.sides.B.roster[0].volatiles.infatuation,undefined);assert.ok(result.events.some(e=>e.reason==='abilityBlocked'));
 result=resolveMove(fixture('single',{}, {itemId:'mental-herb'}),action('attract'),safeRuntime);target=result.battle.sides.B.roster[0];assert.equal(target.volatiles.infatuation,undefined);assert.equal(target.itemState.consumed,true);});

test('Infatuation ends when its source switches out',()=>{let result=resolveMove(fixture(),action('attract'),safeRuntime);const switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests});assert.equal(switched.ok,true);assert.equal(switched.battle.sides.B.roster[0].volatiles.infatuation,undefined);assert.ok(switched.events.some(e=>e.kind==='volatileEnded'&&e.reason==='sourceSwitched'));});

function flingBattle(itemId,targetPatch={}){const battle=fixture('single',{itemId},{hp:500,...targetPatch});return battle;}
test('Fling consumes the held item before Protect and rejects missing/unflingable items',()=>{let battle=flingBattle('kings-rock');battle.sides.B.roster[0].volatiles.protect={id:'protect',sourceId:'protect',blocksStatus:true,endTurnTimer:1};let result=resolveMove(battle,action('fling'),safeRuntime);assert.equal(result.battle.sides.A.roster[0].itemState.consumed,true);assert.equal(result.battle.sides.B.roster[0].hp,500);assert.ok(result.events.some(e=>e.kind==='itemConsumed'&&e.reason==='fling'));result=resolveMove(fixture(),action('fling'),safeRuntime);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noHeldItem'));result=resolveMove(flingBattle('venusaurite'),action('fling'),safeRuntime);assert.equal(result.battle.sides.A.roster[0].itemState.consumed,false);assert.ok(result.events.some(e=>e.reason==='itemCannotBeFlung'));});

test('Fling uses item power and applies King Rock, Light Ball, Poison Barb, Mental Herb, White Herb and Berry behavior',()=>{let result=resolveMove(flingBattle('kings-rock'),action('fling'),safeRuntime);assert.equal(power(result),30);assert.ok(result.battle.sides.B.roster[0].volatiles.flinch);result=resolveMove(flingBattle('light-ball'),action('fling'),safeRuntime);assert.equal(result.battle.sides.B.roster[0].status?.id,'paralysis');result=resolveMove(flingBattle('poison-barb'),action('fling'),safeRuntime);assert.equal(power(result),70);assert.equal(result.battle.sides.B.roster[0].status?.id,'poison');let battle=flingBattle('mental-herb');battle.sides.B.roster[0].volatiles.taunt={id:'taunt'};battle.sides.B.roster[0].volatiles.encore={id:'encore'};result=resolveMove(battle,action('fling'),safeRuntime);assert.equal(result.battle.sides.B.roster[0].volatiles.taunt,undefined);assert.equal(result.battle.sides.B.roster[0].volatiles.encore,undefined);battle=flingBattle('white-herb');battle.sides.B.roster[0].stages.atk=-2;battle.sides.B.roster[0].stages.spa=2;result=resolveMove(battle,action('fling'),safeRuntime);assert.equal(result.battle.sides.B.roster[0].stages.atk,0);assert.equal(result.battle.sides.B.roster[0].stages.spa,2);result=resolveMove(flingBattle('oran-berry'),action('fling'),safeRuntime);const heal=result.events.find(e=>e.kind==='heal'&&e.itemId==='oran-berry');assert.equal(power(result),10);assert.ok((heal?.amount||0)>0);assert.equal(result.battle.sides.B.roster[0].itemState.consumedBerryEver,true);});
