import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {applyMajorStatus,compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['uproar','tackle','hypnosis'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,20]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:2000,maxHp:2000,stats:{hp:2000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='double'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave44-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:70,activeCount:n,rngState:44,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target={side:'B',slot:0}}={})=>({kind:'move',side,actorId,moveId,target,moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const runtime={nextRandom:()=>0,hasActed:()=>false,willMove:()=>true};
const setAbility=(target,id)=>{target.activeAbilityId=id;target.buildSnapshot.abilityId=id;target.passiveEffects=compilePassiveEffects({abilityId:id,itemId:null,manifests});};
const evidence={single:['r3-move-hooks-wave44:single'],double:['r3-move-hooks-wave44:double']};

test('r3-move-hooks-wave44:single/double promotes Uproar with evidence and sound/substitute metadata',()=>{assert.deepEqual(manifests.moves.uproar.testEvidence,evidence);assert.equal(manifests.moves.uproar.tags.includes('sound'),true);assert.equal(manifests.moves.uproar.bypassSubstitute,true);});

test('Uproar lasts three connected uses, wakes all active sleepers, blocks new sleep, and ends without confusion',()=>{let battle=fixture();battle.sides.A.roster[1].status={id:'sleep',turnsRemaining:2};battle.sides.B.roster[1].status={id:'sleep',turnsRemaining:2};let result=resolveMove(battle,action('uproar'),runtime);battle=result.battle;assert.equal(battle.sides.A.roster[1].status,null);assert.equal(battle.sides.B.roster[1].status,null);assert.equal(battle.sides.A.roster[0].volatiles.rampage?.remaining,2);assert.equal(battle.sides.A.roster[0].volatiles.rampage?.blocksSleep,true);const sleep=applyMajorStatus(battle,{actorId:'b1',targetId:'b2',moveId:'hypnosis',status:'sleep'},runtime);assert.equal(sleep.battle.sides.B.roster[1].status,null);assert.ok(sleep.events.some(e=>e.kind==='statusFailed'&&e.reason==='uproarBlocked'));assert.equal(validateAction(battle,action('tackle')).code,'RAMPAGE_MOVE_REQUIRED');
 result=resolveMove(battle,action('uproar'),runtime);battle=result.battle;assert.equal(battle.sides.A.roster[0].volatiles.rampage?.remaining,1);result=resolveMove(battle,action('uproar'),runtime);battle=result.battle;assert.equal(battle.sides.A.roster[0].volatiles.rampage,undefined);assert.equal(battle.sides.A.roster[0].volatiles.confusion,undefined);assert.ok(result.events.some(e=>e.kind==='uproarEnded'&&e.reason==='completed'));});

test('Uproar bypasses Substitute as a sound move and Soundproof prevents both damage and lock start',()=>{let battle=fixture('single');battle.sides.B.roster[0].volatiles.substitute={id:'substitute',hp:500,maxHp:500};const before=battle.sides.B.roster[0].hp;let result=resolveMove(battle,action('uproar'),runtime);assert.ok(result.battle.sides.B.roster[0].hp<before);assert.equal(result.battle.sides.B.roster[0].volatiles.substitute.hp,500);assert.ok(result.battle.sides.A.roster[0].volatiles.rampage);
 battle=fixture('single');setAbility(battle.sides.B.roster[0],'soundproof');const soundproofHp=battle.sides.B.roster[0].hp;result=resolveMove(battle,action('uproar'),runtime);assert.equal(result.battle.sides.B.roster[0].hp,soundproofHp);assert.equal(result.battle.sides.A.roster[0].volatiles.rampage,undefined);assert.ok(result.events.some(e=>e.kind==='moveBlocked'&&e.abilityId==='soundproof'));});
