import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['fissure','guillotine','horn-drill','sheer-cold'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)}),stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,8]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:1000,maxHp:1000,stats:{hp:1000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave34-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:8,activeCount:n,rngState:34,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=moveId=>({kind:'move',side:'A',actorId:'a1',moveId,target:{side:'B',slot:0},moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:0,speed:100});
const runtime=value=>({nextRandom:()=>value,hasActed:()=>false,willMove:()=>false});
const evidence={single:['r3-move-hooks-wave34:single'],double:['r3-move-hooks-wave34:double']};

test('r3-move-hooks-wave34:single promotes all four OHKO moves with a dedicated fixed-damage path',()=>{for(const id of ids){assert.ok(manifests.moves[id]);assert.deepEqual(manifests.moves[id].testEvidence,evidence);assert.equal(manifests.moves[id].handlers.some(h=>h.id==='deal-fixed-damage'&&h.params?.formula==='target-max-hp'&&h.params?.ohko===true),true,id);}assert.equal(manifests.abilities.sturdy.handlers[0].params.blocksOhko,true);});

test('equal-level OHKO uses 30% base accuracy without accuracy/evasion stage math',()=>{let battle=fixture();battle.sides.A.roster[0].stages.accuracy=-6;battle.sides.B.roster[0].stages.evasion=6;let hit=resolveMove(battle,action('fissure'),runtime(.29));assert.equal(hit.battle.sides.B.roster[0].hp,0);battle=fixture();battle.sides.A.roster[0].stages.accuracy=6;battle.sides.B.roster[0].stages.evasion=-6;const miss=resolveMove(battle,action('fissure'),runtime(.30));assert.equal(miss.battle.sides.B.roster[0].hp,1000);assert.ok(miss.events.some(e=>e.kind==='moveMissed'&&e.effectiveAccuracy===30));});

test('OHKO fails against a higher-level target and gains accuracy from positive level difference',()=>{let battle=fixture();battle.sides.A.roster[0].level=49;battle.sides.B.roster[0].level=50;let result=resolveMove(battle,action('guillotine'),runtime(0));assert.equal(result.battle.sides.B.roster[0].hp,1000);assert.ok(result.events.some(e=>e.kind==='moveMissed'&&e.reason==='ohkoLevel'));battle=fixture();battle.sides.A.roster[0].level=55;battle.sides.B.roster[0].level=50;result=resolveMove(battle,action('guillotine'),runtime(.34));assert.equal(result.battle.sides.B.roster[0].hp,0);});

test('Sheer Cold has 20% base accuracy for non-Ice users and cannot affect Ice targets',()=>{let battle=fixture();let result=resolveMove(battle,action('sheer-cold'),runtime(.19));assert.equal(result.battle.sides.B.roster[0].hp,0);battle=fixture();result=resolveMove(battle,action('sheer-cold'),runtime(.20));assert.equal(result.battle.sides.B.roster[0].hp,1000);battle=fixture();battle.sides.A.roster[0].types=['ice'];result=resolveMove(battle,action('sheer-cold'),runtime(.29));assert.equal(result.battle.sides.B.roster[0].hp,0);battle=fixture();battle.sides.B.roster[0].types=['ice'];result=resolveMove(battle,action('sheer-cold'),runtime(0));assert.equal(result.battle.sides.B.roster[0].hp,1000);assert.ok(result.events.some(e=>e.kind==='moveBlocked'&&e.reason==='ohkoTypeImmune'));});

test('r3-move-hooks-wave34:double Sturdy blocks OHKO at partial HP while Substitute absorbs the hit',()=>{let battle=fixture('double'),target=battle.sides.B.roster[0];target.hp=400;target.passiveEffects=compilePassiveEffects({abilityId:'sturdy',itemId:null,manifests});let result=resolveMove(battle,action('horn-drill'),runtime(0));assert.equal(result.battle.sides.B.roster[0].hp,400);assert.ok(result.events.some(e=>e.kind==='moveBlocked'&&e.reason==='ohkoAbility'&&e.abilityId==='sturdy'));battle=fixture('double');battle.sides.B.roster[0].volatiles.substitute={id:'substitute',hp:200};result=resolveMove(battle,action('horn-drill'),runtime(0));assert.equal(result.battle.sides.B.roster[0].hp,1000);assert.equal(result.battle.sides.B.roster[0].volatiles.substitute,undefined);assert.ok(result.events.some(e=>e.kind==='substituteBroken'));});
