import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {applyMechanicsSwitch,createHeldItemState,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS,resolveMechanicsEndTurn} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-candidates/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['wish','flying-press','shell-side-arm'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,20]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:1000,maxHp:1000,stats:{hp:1000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3',{hp:200})],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave40-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:30,activeCount:n,rngState:40,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target=null}={})=>({kind:'move',side,actorId,moveId,target:target??(manifests.moves[moveId].targetMode==='self'?{side,slot:0}:{side:side==='A'?'B':'A',slot:0}),moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const runtime=(value=.5)=>({nextRandom:()=>value,hasActed:()=>false,willMove:()=>true});
const evidence={single:['r3-move-hooks-wave40:single'],double:['r3-move-hooks-wave40:double']};

test('r3-move-hooks-wave40:single/double promotes Wish, Flying Press, and Shell Side Arm with evidence',()=>{for(const id of ids)assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);});

test('Wish is tied to the active slot and heals the replacement by half the original user max HP one turn later',()=>{let battle=fixture();battle.sides.A.roster[0].hp=600;let result=resolveMove(battle,action('wish'),runtime());assert.equal(result.battle.sides.A.slotEffects['0'].wish.amount,500);let end=structuredClone(result.battle);end.phase='END_TURN';let tick=resolveMechanicsEndTurn(end,[],{manifests});assert.equal(tick.battle.sides.A.slotEffects['0'].wish.remaining,1);const switched=applyMechanicsSwitch(tick.battle,'A','a1','a3',{manifests});end=structuredClone(switched.battle);end.phase='END_TURN';const resolved=resolveMechanicsEndTurn(end,[],{manifests});assert.equal(resolved.battle.sides.A.roster.find(x=>x.actorId==='a3').hp,700);assert.ok(resolved.events.some(e=>e.kind==='slotEffectResolved'&&e.effect==='wish'&&e.targetId==='a3'));});

test('Flying Press multiplies Fighting and Flying effectiveness',()=>{const battle=fixture();battle.sides.B.roster[0].types=['bug'];const result=resolveMove(battle,action('flying-press'),runtime(.9));const damage=result.events.find(e=>e.kind==='damage'&&e.moveId==='flying-press');assert.equal(damage.effectiveness,1);assert.equal(damage.breakdown.damageProfile.secondaryAttackType,'flying');});

test('Shell Side Arm selects the stronger damage category, gains contact only when Physical, and can poison',()=>{let battle=fixture();battle.sides.A.roster[0].stats.atk=300;battle.sides.A.roster[0].stats.spa=80;battle.sides.B.roster[0].stats.def=80;battle.sides.B.roster[0].stats.spd=300;let result=resolveMove(battle,action('shell-side-arm'),runtime(0));assert.ok(result.events.some(e=>e.kind==='moveCategorySelected'&&e.category==='physical'));assert.equal(result.events.find(e=>e.kind==='damage'&&e.moveId==='shell-side-arm').category,'physical');assert.equal(result.battle.sides.B.roster[0].status?.id??result.battle.sides.B.roster[0].status,'poison');battle=fixture();battle.sides.A.roster[0].stats.atk=80;battle.sides.A.roster[0].stats.spa=300;battle.sides.B.roster[0].stats.def=300;battle.sides.B.roster[0].stats.spd=80;result=resolveMove(battle,action('shell-side-arm'),runtime(.99));assert.ok(result.events.some(e=>e.kind==='moveCategorySelected'&&e.category==='special'));assert.equal(result.events.find(e=>e.kind==='damage'&&e.moveId==='shell-side-arm').category,'special');});
