import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['rest','heal-bell','magnetic-flux'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]])),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,16]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:600,maxHp:1000,stats:{hp:1000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='double'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave35-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:9,activeCount:n,rngState:35,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,target=null)=>({kind:'move',side:'A',actorId:'a1',moveId,target:target??(manifests.moves[moveId].targetMode==='self'?{side:'A',slot:0}:null),moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:0,speed:100}),runtime={nextRandom:()=>.5,hasActed:()=>false,willMove:()=>false};
const setAbility=(unit,id)=>{unit.activeAbilityId=id;unit.buildSnapshot.abilityId=id;unit.passiveEffects=compilePassiveEffects({abilityId:id,itemId:null,manifests});};
const evidence={single:['r3-move-hooks-wave35:single'],double:['r3-move-hooks-wave35:double']};

test('r3-move-hooks-wave35:single promotes Rest, Heal Bell, and Magnetic Flux',()=>{for(const id of ids){assert.ok(manifests.moves[id]);assert.deepEqual(manifests.moves[id].testEvidence,evidence);}assert.equal(manifests.moves['heal-bell'].tags.includes('sound'),true);assert.deepEqual(manifests.moves['magnetic-flux'].handlers.find(h=>h.id==='apply-stat-stages').params.requireTargetAbilityIds,['plus','minus']);});

test('Rest cures current status, fully heals, and applies its fixed three-count sleep state',()=>{let battle=fixture('single'),actor=battle.sides.A.roster[0];actor.status={id:'burn',sourceId:'probe'};const result=resolveMove(battle,action('rest'),runtime),final=result.battle.sides.A.roster[0];assert.equal(final.hp,1000);assert.equal(final.status.id,'sleep');assert.equal(final.status.turnsRemaining,3);assert.ok(result.events.some(e=>e.kind==='statusCured'&&e.status==='burn'));assert.ok(result.events.some(e=>e.kind==='heal'&&e.amount===400));});

test('Rest fails while already asleep, at full HP, or when an ability blocks sleep',()=>{let battle=fixture('single');battle.sides.A.roster[0].status={id:'sleep',turnsRemaining:2};const sleepPp=battle.sides.A.roster[0].pp.rest;let result=resolveMove(battle,action('rest'),runtime);assert.ok(result.events.some(e=>e.kind==='actionPrevented'&&e.status==='sleep'));assert.equal(result.battle.sides.A.roster[0].pp.rest,sleepPp);battle=fixture('single');battle.sides.A.roster[0].hp=1000;result=resolveMove(battle,action('rest'),runtime);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='fullHp'));battle=fixture('single');setAbility(battle.sides.A.roster[0],'insomnia');result=resolveMove(battle,action('rest'),runtime);assert.ok(result.events.some(e=>e.kind==='statusFailed'&&e.reason==='abilityBlocked'&&e.sourceAbilityId==='insomnia'));});

test('r3-move-hooks-wave35:double Heal Bell cures the party but only active Soundproof allies are immune',()=>{const battle=fixture(),[a1,a2,a3]=battle.sides.A.roster;a1.status={id:'burn'};a2.status={id:'poison'};a3.status={id:'paralysis'};setAbility(a2,'soundproof');setAbility(a3,'soundproof');const result=resolveMove(battle,action('heal-bell'),runtime);assert.equal(result.battle.sides.A.roster[0].status,null);assert.equal(result.battle.sides.A.roster[1].status.id,'poison');assert.equal(result.battle.sides.A.roster[2].status,null);assert.ok(result.events.some(e=>e.kind==='moveBlocked'&&e.targetId==='a2'&&e.abilityId==='soundproof'));assert.equal(result.events.some(e=>e.kind==='moveBlocked'&&e.targetId==='a3'),false);});

test('Magnetic Flux boosts only active Plus/Minus allies and fails closed when no eligible holder is active',()=>{let battle=fixture();setAbility(battle.sides.A.roster[1],'plus');let result=resolveMove(battle,action('magnetic-flux'),runtime);assert.equal(result.battle.sides.A.roster[0].stages.def,0);assert.equal(result.battle.sides.A.roster[1].stages.def,1);assert.equal(result.battle.sides.A.roster[1].stages.spd,1);battle=fixture('single');result=resolveMove(battle,action('magnetic-flux'),runtime);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noTarget'));battle=fixture('single');setAbility(battle.sides.A.roster[0],'minus');result=resolveMove(battle,action('magnetic-flux'),runtime);assert.equal(result.battle.sides.A.roster[0].stages.def,1);});
