import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS,resolveEntryHazards,applyMechanicsSwitch,resolveDestinyBondKo} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-candidates/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['healing-wish','destiny-bond','tackle'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,20]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:1000,maxHp:1000,stats:{hp:1000,atk:220,def:160,spa:180,spd:160,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave45-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:80,activeCount:n,rngState:45,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target=null}={})=>({kind:'move',side,actorId,moveId,target:target??(manifests.moves[moveId].targetMode==='self'?{side,slot:0}:{side:side==='A'?'B':'A',slot:0}),moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const runtime={nextRandom:()=>0,hasActed:()=>false,willMove:()=>true};
const evidence={single:['r3-move-hooks-wave45:single'],double:['r3-move-hooks-wave45:double']};

test('r3-move-hooks-wave45:single/double promotes Healing Wish and Destiny Bond with evidence',()=>{for(const id of ['healing-wish','destiny-bond'])assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);});

test('Healing Wish faints the user, follows its slot, restores status/HP before entry hazards, and then consumes',()=>{let battle=fixture();battle.sides.A.conditions['stealth-rock']={id:'stealth-rock',layers:1,sourceActorId:'b1',sourceMoveId:'stealth-rock',order:1};let result=resolveMove(battle,action('healing-wish'),runtime);battle=result.battle;assert.equal(battle.sides.A.roster[0].hp,0);assert.equal(battle.sides.A.slotEffects['0']['healing-wish'].sourceActorId,'a1');battle.sides.A.roster[2].hp=200;battle.sides.A.roster[2].status={id:'poison'};const switched=applyMechanicsSwitch(battle,'A','a1','a3',{manifests}),entered=resolveEntryHazards(switched.battle,switched.events,{manifests,moves});const replacement=entered.battle.sides.A.roster[2];assert.equal(replacement.status,null);assert.ok(replacement.hp<replacement.maxHp);assert.ok(replacement.hp>200);const healIndex=entered.events.findIndex(e=>e.kind==='slotEffectResolved'&&e.effect==='healing-wish'),hazardIndex=entered.events.findIndex(e=>e.kind==='hazardTriggered'&&e.hazard==='stealth-rock');assert.ok(healIndex>=0&&hazardIndex>healIndex);assert.equal(entered.battle.sides.A.slotEffects?.['0']?.['healing-wish'],undefined);});

test('Healing Wish defers on a fully healthy replacement, fails without a reserve, and respects healing block choice validation',()=>{let battle=fixture();let result=resolveMove(battle,action('healing-wish'),runtime),switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests}),entered=resolveEntryHazards(switched.battle,switched.events,{manifests,moves});assert.ok(entered.battle.sides.A.slotEffects?.['0']?.['healing-wish']);assert.ok(entered.events.some(e=>e.kind==='slotEffectDeferred'&&e.reason==='targetHealthy'));battle=fixture();battle.sides.A.roster= [battle.sides.A.roster[0]];battle.sides.A.active=['a1'];result=resolveMove(battle,action('healing-wish'),runtime);assert.equal(result.battle.sides.A.roster[0].hp,1000);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noReserve'));battle=fixture();battle.sides.A.roster[0].volatiles['psychic-noise']={id:'psychic-noise',blocksHealing:true};assert.equal(validateAction(battle,action('healing-wish')).code,'HEALING_BLOCKED');});

test('Destiny Bond KOs a direct attacker that knocks out the armed user',()=>{let battle=fixture();battle.sides.A.roster[0].hp=1;let armed=resolveMove(battle,action('destiny-bond'),runtime);assert.ok(armed.battle.sides.A.roster[0].volatiles['destiny-bond']);const attack=resolveMove(armed.battle,action('tackle',{side:'B',actorId:'b1',target:{side:'A',slot:0}}),runtime);assert.equal(attack.battle.sides.A.roster[0].hp,0);assert.equal(attack.battle.sides.B.roster[0].hp,0);assert.ok(attack.events.some(e=>e.kind==='destinyBondTriggered'&&e.targetId==='b1'));});

test('Destiny Bond expires when the user starts its next move, only blocks after a successful prior use, and future-move KOs are excluded',()=>{let battle=fixture(),first=resolveMove(battle,action('destiny-bond'),runtime);const second=resolveMove(first.battle,action('destiny-bond'),runtime);assert.equal(second.battle.sides.A.roster[0].volatiles['destiny-bond'],undefined);assert.ok(second.events.some(e=>e.kind==='moveFailed'&&e.reason==='consecutiveUseBlocked'));const third=resolveMove(second.battle,action('destiny-bond'),runtime);assert.ok(third.battle.sides.A.roster[0].volatiles['destiny-bond']);assert.ok(!third.events.some(e=>e.kind==='moveFailed'&&e.reason==='consecutiveUseBlocked'));battle=fixture();battle.sides.A.roster[0].volatiles['destiny-bond']={id:'destiny-bond',sourceId:'destiny-bond'};battle.sides.A.roster[0].hp=0;const excluded=resolveDestinyBondKo(battle,{attackerId:'b1',targetId:'a1',moveId:'future-sight'});assert.equal(excluded.battle.sides.B.roster[0].hp,1000);});
