import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {applyMechanicsReplacementSwitch,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';
import {applyReplacements,completeEntry,resolveActionQueue,resumeActionQueue} from '../rules-v3/index.mjs';

const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const moves=Object.fromEntries(catalog.map(move=>[move.id,move]));
const ids=['copycat','instruct','sleep-talk'];
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
function unit(actorId,{moveIds=[],hp=300,status=null,types=['normal']}={}){return {actorId,speciesId:'venusaur',baseSpeciesId:'venusaur',types:[...types],level:50,hp,maxHp:300,stats:{hp:300,atk:120,def:100,spa:120,spd:100,spe:100},stages:stages(),status,volatiles:{},pp:Object.fromEntries(moveIds.map(id=>[id,10])),maxPp:Object.fromEntries(moveIds.map(id=>[id,10])),passiveEffects:[],abilityState:{},itemState:null,buildSnapshot:{moveIds:[...moveIds],abilityId:null,itemId:null}};}
function fixture(format='single',{a1Moves=['copycat','instruct','sleep-talk'],b1Moves=['tackle'],a1Status=null}={}){const n=format==='double'?2:1,a=[unit('a1',{moveIds:a1Moves,status:a1Status}),unit('a2',{moveIds:['tackle']}),unit('a3',{moveIds:['tackle']})],b=[unit('b1',{moveIds:b1Moves}),unit('b2',{moveIds:['tackle']}),unit('b3',{moveIds:['tackle']})];return {id:`wave53-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:53,activeCount:n,rngState:53,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(id,extra={})=>({kind:'move',side:'A',actorId:'a1',moveId:id,target:id==='instruct'?{side:'B',slot:0}:undefined,priority:0,speed:100,...extra});
const runtime=(roll=0)=>({nextRandom:()=>roll,hasActed:()=>false,willMove:()=>true});
const mon=(battle,id)=>[...battle.sides.A.roster,...battle.sides.B.roster].find(unit=>unit.actorId===id);

test('r3-move-hooks-wave53:single/double promotes Copycat, Instruct, and Sleep Talk while Tera Blast remains current-Champions fail-closed',()=>{for(const id of ids){assert.equal(manifests.moves[id].reviewState,'executable',id);assert.equal(manifests.moves[id].unusable,undefined,id);assert.deepEqual(manifests.moves[id].testEvidence,{single:['r3-move-hooks-wave53:single'],double:['r3-move-hooks-wave53:double']},id);}assert.equal(manifests.moves['tera-blast'].reviewState,'fail-closed');assert.equal(manifests.moves['tera-blast'].reviewReason,'champions-terastallization-unavailable');});

test('Copycat fails without a previous battle move but still spends its own PP',()=>{const battle=fixture(),before=mon(battle,'a1').pp.copycat,result=resolveMove(battle,action('copycat'),runtime());assert.equal(mon(result.battle,'a1').pp.copycat,before-1);assert.ok(result.events.some(event=>event.kind==='moveFailed'&&event.reason==='noPreviousMove'));assert.equal(result.battle.lastMoveUsed.moveId,'copycat');});

test('Copycat executes the previous battle move without spending copied PP and preserves per-user selected-move history',()=>{const battle=fixture();battle.lastMoveUsed={actorId:'b1',moveId:'tackle',turn:52,target:{side:'A',slot:0}};const hp=mon(battle,'b1').hp,result=resolveMove(battle,action('copycat'),runtime());assert.ok(mon(result.battle,'b1').hp<hp);assert.equal(mon(result.battle,'a1').lastMoveId,'copycat');assert.equal(result.battle.lastMoveUsed.moveId,'tackle');assert.ok(result.events.some(event=>event.kind==='moveCalled'&&event.calledMoveId==='tackle'&&event.mode==='use'));assert.ok(result.events.some(event=>event.kind==='ppSpendSkipped'&&event.moveId==='tackle'&&event.reason==='calledMove'));});

test('Copycat honors its explicit blacklist',()=>{const battle=fixture();battle.lastMoveUsed={actorId:'b1',moveId:'protect',turn:52};const result=resolveMove(battle,action('copycat'),runtime());assert.ok(result.events.some(event=>event.kind==='moveFailed'&&event.reason==='copycatBlockedMove'&&event.calledMoveId==='protect'));});

test('Copycat chooses a seeded legal target for the copied move in Double',()=>{const battle=fixture('double');battle.lastMoveUsed={actorId:'b1',moveId:'tackle',turn:52};const result=resolveMove(battle,action('copycat'),runtime(.99));assert.equal(mon(result.battle,'b1').hp,300);assert.ok(mon(result.battle,'b2').hp<300);});

test('Instruct repeats the target last move against its stored target slot and spends that target move PP',()=>{const battle=fixture();const target=mon(battle,'b1');target.lastMoveId='tackle';target.lastMoveTarget={side:'A',slot:0};const before=target.pp.tackle,hp=mon(battle,'a1').hp,result=resolveMove(battle,action('instruct'),runtime());assert.equal(mon(result.battle,'b1').pp.tackle,before-1);assert.ok(mon(result.battle,'a1').hp<hp);assert.equal(mon(result.battle,'a1').pp.instruct,9);assert.ok(result.events.some(event=>event.kind==='moveCalled'&&event.calledActorId==='b1'&&event.calledMoveId==='tackle'&&event.mode==='run'));});

test('Instruct fails at zero PP and against two-turn/recharge/blacklisted last moves',()=>{for(const [moveId,setup] of [['tackle','zero'],['fly','blocked'],['hyper-beam','blocked'],['sleep-talk','blocked']]){const battle=fixture('single',{b1Moves:[moveId]});const target=mon(battle,'b1');target.lastMoveId=moveId;target.lastMoveTarget={side:'A',slot:0};if(setup==='zero')target.pp[moveId]=0;const result=resolveMove(battle,action('instruct'),runtime());assert.ok(result.events.some(event=>event.kind==='moveFailed'&&(setup==='zero'?event.reason==='noPP':event.reason==='instructBlockedMove')),moveId);}});

test('Sleep Talk fails while awake after spending its own PP',()=>{const battle=fixture('single',{a1Moves:['sleep-talk','tackle']}),result=resolveMove(battle,action('sleep-talk'),runtime());assert.equal(mon(result.battle,'a1').pp['sleep-talk'],9);assert.ok(result.events.some(event=>event.kind==='moveFailed'&&event.reason==='userNotAsleep'));});

test('Sleep Talk while asleep selects only an eligible known move and never spends called-move PP',()=>{const battle=fixture('single',{a1Moves:['sleep-talk','fly','tackle'],a1Status:{id:'sleep',turnsRemaining:2}});const before=mon(battle,'a1').pp.tackle,result=resolveMove(battle,action('sleep-talk'),runtime(0));assert.equal(mon(result.battle,'a1').status.turnsRemaining,1);assert.equal(mon(result.battle,'a1').pp['sleep-talk'],9);assert.equal(mon(result.battle,'a1').pp.tackle,before);assert.equal(mon(result.battle,'a1').lastMoveId,'sleep-talk');assert.equal(result.battle.lastMoveUsed.moveId,'tackle');assert.ok(result.events.some(event=>event.kind==='moveCalled'&&event.calledMoveId==='tackle'));});

test('called U-turn defers replacement instead of inventing a reserve target',()=>{const battle=fixture();battle.lastMoveUsed={actorId:'b1',moveId:'u-turn',turn:52};const result=resolveMove(battle,action('copycat'),runtime()),request=result.battle.forcedReplacements?.A?.[0];assert.equal(request?.actorId,'a1');assert.equal(request?.replacementState?.kind,'pivot');assert.equal(request?.replacementState?.moveId,'u-turn');assert.equal(result.battle.sides.A.active[0],'a1');assert.ok(result.events.some(event=>event.kind==='forcedReplacementRequested'&&event.triggerMoveId==='u-turn'));});

test('called Baton Pass defers choice and transfers the captured whitelist after the chosen replacement',()=>{const battle=fixture('single',{a1Moves:['sleep-talk','baton-pass'],a1Status:{id:'sleep',turnsRemaining:2}}),user=mon(battle,'a1');user.stages.atk=2;user.volatiles.substitute={id:'substitute',hp:44,maxHp:44};const result=resolveMove(battle,action('sleep-talk'),runtime(0)),request=result.battle.forcedReplacements?.A?.[0];assert.equal(request?.replacementState?.kind,'baton-pass');const switched=applyMechanicsReplacementSwitch(result.battle,'A','a1','a3',{manifests,request}),incoming=mon(switched.battle,'a3');assert.equal(switched.ok,true);assert.equal(incoming.stages.atk,2);assert.equal(incoming.volatiles.substitute.hp,44);assert.ok(switched.events.some(event=>event.kind==='batonPassTransferred'));});

test('called Shed Tail pays HP before replacement and transfers the substitute only after the replacement choice',()=>{const battle=fixture();battle.lastMoveUsed={actorId:'b1',moveId:'shed-tail',turn:52};const result=resolveMove(battle,action('copycat'),runtime()),request=result.battle.forcedReplacements?.A?.[0];assert.equal(mon(result.battle,'a1').hp,150);assert.equal(request?.replacementState?.kind,'shed-tail');assert.equal(mon(result.battle,'a3').volatiles.substitute,undefined);const switched=applyMechanicsReplacementSwitch(result.battle,'A','a1','a3',{manifests,request});assert.equal(mon(switched.battle,'a3').volatiles.substitute.hp,75);});


test('called pivot suspends the action queue for a real replacement choice and resumes against the incoming slot',()=>{const battle=fixture();battle.lastMoveUsed={actorId:'b1',moveId:'u-turn',turn:52};const actions=[action('copycat',{speed:120}),{kind:'move',side:'B',actorId:'b1',moveId:'tackle',target:{side:'A',slot:0},priority:0,speed:80}],handlers={move:resolveMove},resolved=resolveActionQueue(battle,actions,handlers,{getSpeed:(current,queued)=>queued.speed,isTrickRoom:()=>false});assert.equal(resolved.ok,true);assert.equal(resolved.battle.phase,'REPLACE');assert.ok(resolved.battle.pendingResolution);assert.equal(resolved.battle.sides.A.active[0],'a1');const request=resolved.battle.forcedReplacements.A[0],replaced=applyReplacements(resolved.battle,{A:[{slot:0,actorId:'a3'}],B:[]},{applyLiveSwitch:(current,side,actorId,toId,forced)=>applyMechanicsReplacementSwitch(current,side,actorId,toId,{manifests,request:forced})});assert.equal(replaced.ok,true);const entered=completeEntry(replaced.battle,replaced.events);assert.equal(entered.battle.phase,'RESOLVE');const hp=mon(entered.battle,'a3').hp,resumed=resumeActionQueue(entered.battle,handlers,{getSpeed:(current,queued)=>queued.speed,isTrickRoom:()=>false});assert.equal(resumed.ok,true);assert.ok(mon(resumed.battle,'a3').hp<hp);assert.ok(resumed.events.some(event=>event.kind==='turnResumed'));});

test('called Parting Shot requests replacement for the caller only after its stat drops apply',()=>{const battle=fixture();battle.lastMoveUsed={actorId:'b1',moveId:'parting-shot',turn:52};const result=resolveMove(battle,action('copycat'),runtime());assert.equal(mon(result.battle,'b1').stages.atk,-1);assert.equal(mon(result.battle,'b1').stages.spa,-1);assert.equal(result.battle.forcedReplacements.A[0].actorId,'a1');assert.equal(result.battle.forcedReplacements.A[0].replacementState.kind,'pivot');});
