import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {activeAbilityId,applyMechanicsSwitch,compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';
import {resolveActionQueue,validateTurnActions} from '../rules-v3/turn-engine.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['after-you','quash','gastro-acid','imprison','protect'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,16]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:700,maxHp:1000,stats:{hp:1000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='double'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave36-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:10,activeCount:n,rngState:36,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target=null,speed=100}={})=>({kind:'move',side,actorId,moveId,target:target??(manifests.moves[moveId]?.targetMode==='self'?{side,slot:0}:null),moveType:byId[moveId]?.type,moveCategory:byId[moveId]?.category,priority:manifests.moves[moveId]?.priority??0,speed});
const directRuntime={nextRandom:()=>.5,hasActed:()=>false,willMove:()=>false};
const setAbility=(unit,id)=>{unit.activeAbilityId=id;unit.buildSnapshot.abilityId=id;unit.passiveEffects=compilePassiveEffects({abilityId:id,itemId:null,manifests});};
const evidence={single:['r3-move-hooks-wave36:single'],double:['r3-move-hooks-wave36:double']};

test('r3-move-hooks-wave36:single promotes four action/ability-control moves with Wave 36 evidence',()=>{for(const id of ['after-you','quash','gastro-acid','imprison']){assert.ok(manifests.moves[id],id);assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);}assert.equal(manifests.moves['after-you'].bypassesProtect,true);assert.equal(manifests.moves['gastro-acid'].handlers.at(-1).params.mode,'suppress');});

test('r3-move-hooks-wave36:double After You and Quash reorder the live pending queue rather than faking priority',()=>{
 const run=(moveId,target)=>{const battle=fixture(),actions=[action(moveId,{target,speed:400}),{kind:'move',side:'A',actorId:'a2',moveId:'noop-a2',priority:0,speed:100},{kind:'move',side:'B',actorId:'b1',moveId:'noop-b1',priority:0,speed:300},{kind:'move',side:'B',actorId:'b2',moveId:'noop-b2',priority:0,speed:200}],handlers={move:(state,queued,runtime)=>['after-you','quash'].includes(queued.moveId)?resolveMove(state,queued,runtime):{battle:structuredClone(state),events:[{kind:'probeMove',actorId:queued.actorId,moveId:queued.moveId}]}};return resolveActionQueue(battle,actions,handlers);};
 let result=run('after-you',{side:'A',slot:1});assert.equal(result.ok,true);assert.deepEqual(result.queue.map(x=>x.actorId),['a1','a2','b1','b2']);assert.ok(result.events.some(e=>e.kind==='pendingActionReordered'&&e.targetId==='a2'&&e.position==='front'));
 result=run('quash',{side:'B',slot:0});assert.equal(result.ok,true);assert.deepEqual(result.queue.map(x=>x.actorId),['a1','b2','a2','b1']);assert.ok(result.events.some(e=>e.kind==='pendingActionReordered'&&e.targetId==='b1'&&e.position==='back'));
});

test('After You and Quash fail closed in singles, and queue-order overrides cannot be injected by clients',()=>{for(const moveId of ['after-you','quash']){const result=resolveMove(fixture('single'),action(moveId,{target:{side:'B',slot:0}}),directRuntime);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='singleBattle'),moveId);}const battle=fixture(),actions=[action('protect',{actorId:'a1',speed:400}),action('protect',{actorId:'a2',target:{side:'A',slot:1},speed:300}),action('protect',{side:'B',actorId:'b1',target:{side:'B',slot:0},speed:200}),action('protect',{side:'B',actorId:'b2',target:{side:'B',slot:1},speed:100})];actions[0].queueOrderOverride=99;assert.equal(validateTurnActions(battle,actions).code,'INVALID_ACTION');});

test('Gastro Acid suppresses the active Ability and restores it when the holder switches out',()=>{let battle=fixture();setAbility(battle.sides.B.roster[0],'sturdy');let result=resolveMove(battle,action('gastro-acid',{target:{side:'B',slot:0}}),directRuntime);assert.equal(activeAbilityId(result.battle.sides.B.roster[0]),'none');assert.equal(result.battle.sides.B.roster[0].passiveEffects.some(e=>e.sourceKind==='ability'),false);assert.ok(result.events.some(e=>e.kind==='abilitySuppressed'&&e.targetId==='b1'));const switched=applyMechanicsSwitch(result.battle,'B','b1','b3',{manifests});assert.equal(activeAbilityId(switched.battle.sides.B.roster[0]),'sturdy');assert.ok(switched.events.some(e=>e.kind==='abilityRestored'&&e.actorId==='b1'));battle=fixture();setAbility(battle.sides.B.roster[0],'disguise');result=resolveMove(battle,action('gastro-acid',{target:{side:'B',slot:0}}),directRuntime);assert.equal(activeAbilityId(result.battle.sides.B.roster[0]),'disguise');assert.ok(result.events.some(e=>e.kind==='abilityChangeFailed'&&e.reason==='blockedAbility'));});

test('Magic Bounce reflects Gastro Acid back to the caster through the shared status-reflection path',()=>{const battle=fixture();setAbility(battle.sides.A.roster[0],'sturdy');setAbility(battle.sides.B.roster[0],'magic-bounce');const result=resolveMove(battle,action('gastro-acid',{target:{side:'B',slot:0}}),directRuntime);assert.equal(activeAbilityId(result.battle.sides.A.roster[0]),'none');assert.equal(activeAbilityId(result.battle.sides.B.roster[0]),'magic-bounce');assert.ok(result.events.some(e=>e.kind==='moveReflected'&&e.abilityId==='magic-bounce'));});

test('Imprison blocks shared moves only while the Imprison user remains active',()=>{let battle=fixture();const user=battle.sides.A.roster[0],foe=battle.sides.B.roster[0];user.buildSnapshot.moveIds=['imprison','protect'];user.pp={imprison:16,protect:16};foe.buildSnapshot.moveIds=['protect'];foe.pp={protect:16};let result=resolveMove(battle,action('imprison',{target:{side:'A',slot:0}}),directRuntime);let check=validateAction(result.battle,action('protect',{side:'B',actorId:'b1',target:{side:'B',slot:0}}));assert.equal(check.code,'IMPRISONED_MOVE');assert.equal(check.sourceActorId,'a1');const switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests});check=validateAction(switched.battle,action('protect',{side:'B',actorId:'b1',target:{side:'B',slot:0}}));assert.deepEqual(check,{ok:true});});
