import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHeldItemState,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-candidates/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['endure','steel-beam','charge','thunderbolt','tackle'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,16]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:700,maxHp:1000,stats:{hp:1000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(){const a=[unit('a1'),unit('a2')],b=[unit('b1'),unit('b2')];return {id:'wave37',format:'single',level:50,phase:'RESOLVE',phaseRevision:1,turn:11,activeCount:1,rngState:37,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:['a1'],roster:a,conditions:{}},B:{active:['b1'],roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target=null}={})=>({kind:'move',side,actorId,moveId,target:target??(manifests.moves[moveId]?.targetMode==='self'?{side,slot:0}:{side:side==='A'?'B':'A',slot:0}),moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const runtime=value=>({nextRandom:()=>value,hasActed:()=>false,willMove:()=>false});
const damage=result=>result.events.find(e=>e.kind==='damage'&&e.targetId==='b1'&&!e.selfDamage)?.amount||0;
const evidence={single:['r3-move-hooks-wave37:single'],double:['r3-move-hooks-wave37:double']};

test('r3-move-hooks-wave37:single promotes Endure, Steel Beam, and Charge with Wave 37 evidence',()=>{for(const id of ['endure','steel-beam','charge'])assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);assert.equal(manifests.moves.endure.priority,4);assert.equal(manifests.moves['steel-beam'].handlers.at(-1).id,'apply-self-hp-damage');});

test('Endure clamps otherwise lethal move damage to 1 HP',()=>{let battle=fixture();battle.sides.A.roster[0].hp=40;let result=resolveMove(battle,action('endure'),runtime(.5));battle=result.battle;battle.sides.B.roster[0].stats.atk=900;result=resolveMove(battle,action('tackle',{side:'B',actorId:'b1'}),runtime(.999));assert.equal(result.battle.sides.A.roster[0].hp,1);assert.ok(result.events.some(e=>e.kind==='endureActivated'&&e.targetId==='a1'));});

test('Endure shares the consecutive protection stall gate',()=>{let result=resolveMove(fixture(),action('endure'),runtime(.5));assert.ok(result.events.some(e=>e.kind==='endureApplied'));const before=result.battle.sides.A.roster[0].pp.endure;result=resolveMove(result.battle,action('endure'),runtime(.99));assert.ok(result.events.some(e=>e.kind==='protectionFailed'&&e.counter===3));assert.equal(result.battle.sides.A.roster[0].pp.endure,before-1);});

test('Steel Beam always pays half max HP rounded normally, including on an accuracy miss',()=>{let battle=fixture();Object.assign(battle.sides.A.roster[0],{hp:1001,maxHp:1001,stats:{...battle.sides.A.roster[0].stats,hp:1001}});let result=resolveMove(battle,action('steel-beam'),runtime(.5));assert.equal(result.battle.sides.A.roster[0].hp,500);assert.ok(result.events.some(e=>e.selfDamage===true&&e.amount===501));assert.ok(result.events.some(e=>e.kind==='damage'&&e.targetId==='b1'));battle=fixture();Object.assign(battle.sides.A.roster[0],{hp:1001,maxHp:1001,stats:{...battle.sides.A.roster[0].stats,hp:1001}});result=resolveMove(battle,action('steel-beam'),runtime(.999));assert.equal(result.battle.sides.A.roster[0].hp,500);assert.ok(result.events.some(e=>e.kind==='moveMissed'));assert.equal(result.events.some(e=>e.kind==='damage'&&e.targetId==='b1'),false);});

test('Charge boosts Sp. Def, doubles the next Electric move, and is consumed only by an Electric move other than Charge',()=>{let battle=fixture();let charged=resolveMove(battle,action('charge'),runtime(.999));assert.equal(charged.battle.sides.A.roster[0].stages.spd,1);assert.ok(charged.battle.sides.A.roster[0].volatiles.charge);const boosted=resolveMove(charged.battle,action('thunderbolt'),runtime(.999));const plain=resolveMove(fixture(),action('thunderbolt'),runtime(.999));assert.ok(damage(boosted)>damage(plain)*1.8);assert.equal(boosted.battle.sides.A.roster[0].volatiles.charge,undefined);charged=resolveMove(fixture(),action('charge'),runtime(.999));const normal=resolveMove(charged.battle,action('tackle'),runtime(.999));assert.ok(normal.battle.sides.A.roster[0].volatiles.charge);const refreshed=resolveMove(normal.battle,action('charge'),runtime(.999));assert.ok(refreshed.battle.sides.A.roster[0].volatiles.charge);assert.equal(refreshed.battle.sides.A.roster[0].stages.spd,2);});
