import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHeldItemState,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS,prepareTurnOrderMechanics} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['triple-axel','population-bomb','beak-blast','tackle'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,20]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:5000,maxHp:5000,stats:{hp:5000,atk:150,def:150,spa:150,spd:150,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave41-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:40,activeCount:n,rngState:41,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target={side:'B',slot:0}}={})=>({kind:'move',side,actorId,moveId,target,moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const sequence=values=>{let i=0;return {nextRandom:()=>values[i++]??0,hasActed:()=>false,willMove:()=>true};};
const evidence={single:['r3-move-hooks-wave41:single'],double:['r3-move-hooks-wave41:double']};

test('r3-move-hooks-wave41:single/double promotes Triple Axel, Population Bomb, and Beak Blast with evidence',()=>{for(const id of ['triple-axel','population-bomb','beak-blast'])assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);});

test('Triple Axel checks accuracy per hit and uses 20/40/60 power progression',()=>{let result=resolveMove(fixture(),action('triple-axel'),sequence(Array(20).fill(0)));let damage=result.events.filter(e=>e.kind==='damage'&&e.moveId==='triple-axel');assert.equal(damage.length,3);assert.ok(damage[0].amount<damage[1].amount&&damage[1].amount<damage[2].amount);assert.equal(result.events.find(e=>e.kind==='hitCount').hitCount,3);result=resolveMove(fixture(),action('triple-axel'),sequence([0,.99,.99,.99]));damage=result.events.filter(e=>e.kind==='damage'&&e.moveId==='triple-axel');assert.equal(damage.length,1);assert.ok(result.events.some(e=>e.kind==='moveMissed'&&e.hit===2));});

test('Population Bomb can execute all ten hits and stops immediately on a later accuracy failure',()=>{let result=resolveMove(fixture(),action('population-bomb'),sequence(Array(80).fill(0)));assert.equal(result.events.filter(e=>e.kind==='damage'&&e.moveId==='population-bomb').length,10);assert.equal(result.events.find(e=>e.kind==='hitCount').hitCount,10);result=resolveMove(fixture(),action('population-bomb'),sequence([0,.99,.99,.99]));assert.equal(result.events.filter(e=>e.kind==='damage'&&e.moveId==='population-bomb').length,1);assert.equal(result.events.find(e=>e.kind==='hitCount').hitCount,1);});

test('Beak Blast enters its heated state before actions, burns contact attackers, and clears the state after firing',()=>{let battle=fixture();const prepared=prepareTurnOrderMechanics(battle,[action('beak-blast',{side:'B',actorId:'b1',target:{side:'A',slot:0}}),action('tackle')],sequence([0]),{moveManifests:manifests.moves});battle=prepared.battle;assert.equal(battle.sides.B.roster[0].volatiles['beak-blast']?.contactBurn,true);let contacted=resolveMove(battle,action('tackle'),sequence(Array(10).fill(.5)));assert.equal(contacted.battle.sides.A.roster[0].status?.id??contacted.battle.sides.A.roster[0].status,'burn');assert.ok(contacted.events.some(e=>e.kind==='preparedContactTriggered'&&e.sourceId==='b1'));const fired=resolveMove(contacted.battle,action('beak-blast',{side:'B',actorId:'b1',target:{side:'A',slot:0}}),sequence(Array(10).fill(.5)));assert.equal(fired.battle.sides.B.roster[0].volatiles['beak-blast'],undefined);});

test('Beak Blast contact burn still resolves when the heated user is knocked out by the contact hit',()=>{let battle=fixture();battle.sides.B.roster[0].hp=1;const prepared=prepareTurnOrderMechanics(battle,[action('beak-blast',{side:'B',actorId:'b1',target:{side:'A',slot:0}}),action('tackle')],sequence([0]),{moveManifests:manifests.moves});const contacted=resolveMove(prepared.battle,action('tackle'),sequence(Array(10).fill(.5)));assert.equal(contacted.battle.sides.B.roster[0].hp,0);assert.equal(contacted.battle.sides.A.roster[0].status?.id??contacted.battle.sides.A.roster[0].status,'burn');assert.ok(contacted.events.some(e=>e.kind==='preparedContactTriggered'&&e.sourceId==='b1'));});
