import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS,heldItemId} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const promoted=['outrage','petal-dance','raging-fury','thrash','axe-kick','high-jump-kick','supercell-slam','stockpile','spit-up','swallow','belly-drum','stuff-cheeks','spite','eerie-spell','torment','smack-down'];
const support=['slash','high-horsepower'];const ids=[...promoted,...support],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const blankStages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
const pp=()=>Object.fromEntries(ids.map(id=>[id,Math.max(byId[id]?.maxPP||16,1)]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:3200,maxHp:3200,stats:{hp:3200,atk:220,def:180,spa:210,spd:170,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:blankStages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave30-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:1,activeCount:n,rngState:30,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,target={side:'B',slot:0},side='A',actorId='a1')=>({kind:'move',side,actorId,moveId,target,priority:manifests.moves[moveId].priority,speed:100});
const evidence={single:['r3-move-hooks-wave30:single'],double:['r3-move-hooks-wave30:double']};
const runtime={nextRandom:()=>.5};function sequence(values,fallback=.9){let i=0;return {nextRandom:()=>values[i++]??fallback};}
function setAbility(unit,id){unit.buildSnapshot.abilityId=id;unit.activeAbilityId=id;unit.passiveEffects=[...compilePassiveEffects({abilityId:id,manifests}),...unit.passiveEffects.filter(x=>x.sourceKind==='item')];}
function setItem(unit,id){unit.buildSnapshot.itemId=id;unit.itemState=createHeldItemState(id);unit.passiveEffects=[...unit.passiveEffects.filter(x=>x.sourceKind!=='item'),...compilePassiveEffects({itemId:id,manifests})];}

test('r3-move-hooks-wave30:single promotes 16 moves across seven mechanics families',()=>{assert.equal(promoted.length,16);for(const id of promoted){assert.ok(manifests.moves[id],id);assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);}assert.equal(manifests.moves['raging-fury'].contact,false);});

test('rampage chooses a random foe, spends PP only once, locks the move, and confuses after completion',()=>{
 let battle=fixture('double');const before=battle.sides.A.roster[0].pp.outrage;let result=resolveMove(battle,action('outrage',{side:'B',slot:0}),sequence([.99,.9,.9,.1]));assert.ok(result.events.some(e=>e.kind==='damage'&&e.targetId==='b2'));assert.equal(result.battle.sides.A.roster[0].pp.outrage,before-1);assert.equal(result.battle.sides.A.roster[0].volatiles.rampage?.remaining,1);assert.equal(validateAction(result.battle,action('slash')).code,'RAMPAGE_MOVE_REQUIRED');
 result=resolveMove(result.battle,action('outrage'),sequence([.01,.9,.9,.4]));assert.equal(result.battle.sides.A.roster[0].pp.outrage,before-1);assert.equal(result.battle.sides.A.roster[0].volatiles.rampage,undefined);assert.ok(result.battle.sides.A.roster[0].volatiles.confusion);
});

test('rampage interruption by flinch ends the lock without fatigue confusion',()=>{let result=resolveMove(fixture(),action('thrash'),sequence([.1,.9,.9,.1]));result.battle.sides.A.roster[0].volatiles.flinch={id:'flinch',timer:1};result=resolveMove(result.battle,action('thrash'),runtime);assert.equal(result.battle.sides.A.roster[0].volatiles.rampage,undefined);assert.equal(result.battle.sides.A.roster[0].volatiles.confusion,undefined);assert.ok(result.events.some(e=>e.kind==='rampageEnded'&&e.reason==='actionPrevented'));});

test('crash moves lose half max HP on a miss, while a hit into Substitute counts as connected',()=>{for(const id of ['axe-kick','high-jump-kick','supercell-slam']){const battle=fixture();const result=resolveMove(battle,action(id),sequence([.999]));assert.equal(result.battle.sides.A.roster[0].hp,1600,id);assert.ok(result.events.some(e=>e.source==='crash'),id);}const battle=fixture();battle.sides.B.roster[0].volatiles.substitute={id:'substitute',hp:500,maxHp:800};const result=resolveMove(battle,action('high-jump-kick'),sequence([.1,.9,.9]));assert.equal(result.battle.sides.A.roster[0].hp,3200);assert.equal(result.events.some(e=>e.source==='crash'),false);});

test('Axe Kick keeps its confusion secondary only on a real damaging hit',()=>{const result=resolveMove(fixture(),action('axe-kick'),sequence([.1,.9,.9,.1,.4]));assert.ok(result.battle.sides.B.roster[0].volatiles.confusion);});

test('Stockpile reaches three layers, tracks Defense/SpD boosts, and rejects a fourth layer',()=>{let result={battle:fixture()};for(let i=0;i<3;i++)result=resolveMove(result.battle,action('stockpile',{side:'A',slot:0}),runtime);const user=result.battle.sides.A.roster[0];assert.equal(user.volatiles.stockpile.layers,3);assert.equal(user.stages.def,3);assert.equal(user.stages.spd,3);const failed=resolveMove(result.battle,action('stockpile',{side:'A',slot:0}),runtime);assert.ok(failed.events.some(e=>e.kind==='moveFailed'&&e.reason==='stockpileLimit'));assert.equal(failed.battle.sides.A.roster[0].volatiles.stockpile.layers,3);});

test('Spit Up scales to 300 BP at three Stockpiles and consumes the stored boosts',()=>{let result={battle:fixture()};for(let i=0;i<3;i++)result=resolveMove(result.battle,action('stockpile',{side:'A',slot:0}),runtime);result=resolveMove(result.battle,action('spit-up'),runtime);assert.equal(result.events.find(e=>e.kind==='powerResolved')?.power,300);const user=result.battle.sides.A.roster[0];assert.equal(user.volatiles.stockpile,undefined);assert.equal(user.stages.def,0);assert.equal(user.stages.spd,0);});

test('Swallow heals by stored layer count and consumes Stockpile state',()=>{let result={battle:fixture()};for(let i=0;i<2;i++)result=resolveMove(result.battle,action('stockpile',{side:'A',slot:0}),runtime);result.battle.sides.A.roster[0].hp=1000;result=resolveMove(result.battle,action('swallow',{side:'A',slot:0}),runtime);assert.equal(result.battle.sides.A.roster[0].hp,2600);assert.equal(result.battle.sides.A.roster[0].volatiles.stockpile,undefined);assert.equal(result.battle.sides.A.roster[0].stages.def,0);});

test('Belly Drum pays half max HP, sets Attack to +6, and fails at +6 without another HP cost',()=>{let battle=fixture(),result=resolveMove(battle,action('belly-drum',{side:'A',slot:0}),runtime);assert.equal(result.battle.sides.A.roster[0].hp,1600);assert.equal(result.battle.sides.A.roster[0].stages.atk,6);result=resolveMove(result.battle,action('belly-drum',{side:'A',slot:0}),runtime);assert.equal(result.battle.sides.A.roster[0].hp,1600);assert.ok(result.events.some(e=>e.reason==='stageAlreadyMaximized'));});

test('Stuff Cheeks requires a Berry, force-eats it, then raises Defense by two',()=>{let battle=fixture(),result=resolveMove(battle,action('stuff-cheeks',{side:'A',slot:0}),runtime);assert.ok(result.events.some(e=>e.reason==='heldBerryRequirement'));battle=fixture();battle.sides.A.roster[0].hp=2000;setItem(battle.sides.A.roster[0],'sitrus-berry');setAbility(battle.sides.B.roster[0],'unnerve');result=resolveMove(battle,action('stuff-cheeks',{side:'A',slot:0}),runtime);assert.equal(heldItemId(result.battle.sides.A.roster[0]),null);assert.equal(result.battle.sides.A.roster[0].stages.def,2);assert.equal(result.events.some(e=>e.kind==='itemActivationBlocked'),false);});

test('Spite cuts four PP from the target last move and Eerie Spell cuts three after a real hit',()=>{let battle=fixture();battle.sides.B.roster[0].lastMoveId='slash';battle.sides.B.roster[0].pp.slash=10;let result=resolveMove(battle,action('spite'),runtime);assert.equal(result.battle.sides.B.roster[0].pp.slash,6);battle=fixture();battle.sides.B.roster[0].lastMoveId='slash';battle.sides.B.roster[0].pp.slash=10;result=resolveMove(battle,action('eerie-spell'),runtime);assert.equal(result.battle.sides.B.roster[0].pp.slash,7);assert.ok(result.events.some(e=>e.kind==='damage'&&e.moveId==='eerie-spell'));});

test('Torment blocks consecutive use while Aroma Veil protects its holder and allies',()=>{let battle=fixture();battle.sides.B.roster[0].lastMoveId='slash';let result=resolveMove(battle,action('torment'),runtime),attempt=action('slash',{side:'A',slot:0},'B','b1');assert.equal(result.battle.sides.B.roster[0].volatiles.torment?.id,'torment');assert.equal(validateAction(result.battle,attempt).code,'TORMENT_SAME_MOVE_BLOCKED');const executed=resolveMove(result.battle,attempt,runtime);assert.ok(executed.events.some(e=>e.kind==='actionPrevented'&&e.reason==='TORMENT_SAME_MOVE_BLOCKED'));battle=fixture('double');setAbility(battle.sides.B.roster[1],'aroma-veil');result=resolveMove(battle,action('torment',{side:'B',slot:0}),runtime);assert.equal(result.battle.sides.B.roster[0].volatiles.torment,undefined);assert.ok(result.events.some(e=>e.kind==='volatileFailed'&&e.reason==='abilityBlocked'&&e.sourceAbilityId==='aroma-veil'));});

test('Smack Down interrupts airborne state, clears Magnet Rise, and makes Ground hit through Levitate',()=>{const battle=fixture();const target=battle.sides.B.roster[0];target.types=['flying'];target.volatiles['magnet-rise']={id:'magnet-rise'};target.volatiles['two-turn-move']={id:'two-turn-move',moveId:'fly',startedTurn:1,semiInvulnerable:'airborne',target:{side:'A',slot:0}};setAbility(target,'levitate');let result=resolveMove(battle,action('smack-down'),runtime);const grounded=result.battle.sides.B.roster[0];assert.ok(grounded.volatiles['forced-grounded']);assert.equal(grounded.volatiles['magnet-rise'],undefined);assert.equal(grounded.volatiles['two-turn-move'],undefined);result=resolveMove(result.battle,action('high-horsepower'),runtime);assert.ok(result.events.some(e=>e.kind==='damage'&&e.moveId==='high-horsepower'&&e.amount>0));});

test('r3-move-hooks-wave30:double keeps Stockpile utility self-scoped and Smack Down selected-target scoped',()=>{let battle=fixture('double');let result=resolveMove(battle,action('stockpile',{side:'A',slot:0},'A','a2'),runtime);assert.equal(result.battle.sides.A.roster[1].volatiles.stockpile.layers,1);assert.equal(result.battle.sides.A.roster[0].volatiles.stockpile,undefined);result=resolveMove(result.battle,action('smack-down',{side:'B',slot:1}),runtime);assert.ok(result.battle.sides.B.roster[1].volatiles['forced-grounded']);assert.equal(result.battle.sides.B.roster[0].volatiles['forced-grounded'],undefined);});
