import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS,resolveMechanicsEndTurn} from '../mechanics-v3/index.mjs';

const moveCatalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const speciesCatalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/species.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const moveIds=['future-sight','beat-up'],moves=Object.fromEntries(moveCatalog.filter(move=>moveIds.includes(move.id)).map(move=>[move.id,move])),species=Object.fromEntries(speciesCatalog.map(entry=>[entry.id,entry]));
const registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,species,registry});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
const unit=(actorId,speciesId,sideMoves=moveIds)=>{const entry=species[speciesId],hp=500;return {actorId,speciesId,baseSpeciesId:speciesId,types:[...entry.types],level:50,hp,maxHp:hp,stats:{hp,atk:160,def:150,spa:170,spd:150,spe:100},stages:stages(),status:null,volatiles:{},pp:Object.fromEntries(sideMoves.map(id=>[id,10])),maxPp:Object.fromEntries(sideMoves.map(id=>[id,10])),passiveEffects:[],abilityState:{},buildSnapshot:{moveIds:[...sideMoves],abilityId:null,itemId:null}};};
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1','venusaur'),unit('a2','charizard'),unit('a3','blastoise')],b=[unit('b1','pikachu',[]),unit('b2','raichu',[])];return {id:`wave49-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:91,activeCount:n,rngState:49,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,target={side:'B',slot:0})=>({kind:'move',side:'A',actorId:'a1',moveId,target,priority:0,speed:100});
const runtime={nextRandom:()=>0,hasActed:()=>false,willMove:()=>true};
const endTurn=battle=>{const next=structuredClone(battle);next.phase='END_TURN';return resolveMechanicsEndTurn(next,[],{manifests,moves});};

test('r3-move-hooks-wave49:single/double promotes Future Sight and Beat Up with shared mechanics evidence',()=>{for(const id of moveIds)assert.deepEqual(manifests.moves[id].testEvidence,{single:['r3-move-hooks-wave49:single'],double:['r3-move-hooks-wave49:double']},id);});

test('Future Sight binds to the target slot, lands two turns later on the current occupant, and survives source fainting',()=>{let battle=fixture(),result=resolveMove(battle,action('future-sight'),runtime);battle=result.battle;assert.equal(battle.sides.B.slotEffects['0']['future-attack'].remaining,3);battle.sides.A.roster[0].hp=0;let ended=endTurn(battle);assert.equal(ended.battle.sides.B.slotEffects['0']['future-attack'].remaining,2);battle=ended.battle;const original=battle.sides.B.roster[0],replacement=battle.sides.B.roster.push(unit('b3','jolteon',[]))-1;battle.sides.B.active[0]='b3';battle.sides.B.roster[replacement].hp=500;ended=endTurn(battle);assert.equal(ended.battle.sides.B.slotEffects['0']['future-attack'].remaining,1);ended=endTurn(ended.battle);const hit=ended.battle.sides.B.roster.find(x=>x.actorId==='b3');assert.ok(hit.hp<500);assert.equal(ended.battle.sides.B.slotEffects?.['0']?.['future-attack'],undefined);assert.equal(original.hp,500);assert.ok(ended.events.some(e=>e.kind==='slotEffectResolved'&&e.effect==='future-attack'&&e.targetId==='b3'));});

test('Future Sight refuses a second pending attack in the same slot without replacing the original source',()=>{let battle=fixture(),first=resolveMove(battle,action('future-sight'),runtime);battle=first.battle;const source=structuredClone(battle.sides.B.slotEffects['0']['future-attack']);const second=resolveMove(battle,action('future-sight'),runtime);assert.deepEqual(second.battle.sides.B.slotEffects['0']['future-attack'],source);assert.ok(second.events.some(e=>e.kind==='moveFailed'&&e.reason==='futureAttackAlreadyPending'));});

test('Beat Up derives one hit per healthy status-free party member using each species base Attack',()=>{let battle=fixture();battle.sides.A.roster[2].status={id:'poison'};const result=resolveMove(battle,action('beat-up'),runtime),prepared=result.events.find(e=>e.kind==='partyHitPowersPrepared'),hits=result.events.find(e=>e.kind==='hitCount'&&e.targetId==='b1');assert.deepEqual(prepared.powers,[13,13]);assert.equal(hits.plannedHits,2);assert.equal(hits.hitCount,2);assert.ok(result.battle.sides.B.roster[0].hp<500);});

test('Beat Up includes restored eligible party members and fails cleanly when none can participate',()=>{let battle=fixture();let result=resolveMove(battle,action('beat-up'),runtime);assert.equal(result.events.find(e=>e.kind==='partyHitPowersPrepared').hitCount,3);battle=fixture();for(const member of battle.sides.A.roster)member.status={id:'burn'};result=resolveMove(battle,action('beat-up'),runtime);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noEligiblePartyMember'));assert.equal(result.battle.sides.B.roster[0].hp,500);});
