import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {applyMechanicsSwitch,createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS,resolveMechanicsEndTurn} from '../mechanics-v3/index.mjs';
import {applyHpGroup} from '../rules-v3/lifecycle.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['roost','burn-up','psychic-noise','dragon-cheer','focus-energy','soak','heal-pulse'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,16]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:700,maxHp:1000,stats:{hp:1000,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='double'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave38-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:12,activeCount:n,rngState:38,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target=null}={})=>({kind:'move',side,actorId,moveId,target:target??(manifests.moves[moveId]?.targetMode==='self'?{side,slot:side==='A'?0:0}:{side:side==='A'?'B':'A',slot:0}),moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const runtime=value=>({nextRandom:()=>value,hasActed:()=>false,willMove:()=>false});
const evidence={single:['r3-move-hooks-wave38:single'],double:['r3-move-hooks-wave38:double']};

test('r3-move-hooks-wave38:single promotes Roost, Burn Up, Psychic Noise, and Dragon Cheer with Wave 38 evidence',()=>{for(const id of ['roost','burn-up','psychic-noise','dragon-cheer'])assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);assert.equal(manifests.moves['psychic-noise'].tags.includes('sound'),true);assert.equal(manifests.moves['dragon-cheer'].bypassSubstitute,true);});

test('Roost heals half max HP, removes Flying only for the turn, and does not change typing when healing fails',()=>{let battle=fixture('single'),actor=battle.sides.A.roster[0];actor.types=['flying','normal'];actor.hp=400;let result=resolveMove(battle,action('roost'),runtime(.5));assert.equal(result.battle.sides.A.roster[0].hp,900);assert.deepEqual(result.battle.sides.A.roster[0].types,['normal']);assert.ok(result.battle.sides.A.roster[0].volatiles.roost);result.battle.phase='END_TURN';const ended=resolveMechanicsEndTurn(result.battle,[],{manifests});assert.deepEqual(ended.battle.sides.A.roster[0].types,['flying','normal']);assert.ok(ended.events.some(e=>e.kind==='typesRestored'&&e.actorId==='a1'));battle=fixture('single');battle.sides.A.roster[0].types=['flying','normal'];battle.sides.A.roster[0].hp=1000;result=resolveMove(battle,action('roost'),runtime(.5));assert.deepEqual(result.battle.sides.A.roster[0].types,['flying','normal']);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noHealing'));});

test('Burn Up requires Fire typing, removes Fire only on a connected use, spends PP on a type failure, and restores typing on switch',()=>{let battle=fixture('single');battle.sides.A.roster[0].types=['fire','flying'];let result=resolveMove(battle,action('burn-up'),runtime(.5));assert.deepEqual(result.battle.sides.A.roster[0].types,['flying']);let switched=applyMechanicsSwitch(result.battle,'A','a1','a3',{manifests});assert.deepEqual(switched.battle.sides.A.roster[0].types,['fire','flying']);battle=fixture('single');battle.sides.A.roster[0].types=['fire','flying'];battle.sides.A.roster[0].stages.accuracy=-6;battle.sides.B.roster[0].stages.evasion=6;result=resolveMove(battle,action('burn-up'),runtime(.999));assert.deepEqual(result.battle.sides.A.roster[0].types,['fire','flying']);assert.ok(result.events.some(e=>e.kind==='moveMissed'));battle=fixture('single');battle.sides.A.roster[0].types=['flying'];const before=battle.sides.A.roster[0].pp['burn-up'];result=resolveMove(battle,action('burn-up'),runtime(.5));assert.equal(result.battle.sides.A.roster[0].pp['burn-up'],before-1);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='requiredUserType'));});

test('Psychic Noise applies two-turn Heal Block that stops move and generic HP recovery without refreshing itself',()=>{let battle=fixture('single');battle.sides.B.roster[0].hp=400;let result=resolveMove(battle,action('psychic-noise'),runtime(.5));let target=result.battle.sides.B.roster[0];assert.equal(target.volatiles['heal-block']?.endTurnTimer,2);let check=validateAction(result.battle,action('roost',{side:'B',actorId:'b1',target:{side:'B',slot:0}}));assert.equal(check.code,'HEALING_BLOCKED');const generic=applyHpGroup(result.battle,[{actorId:'b1',delta:200}],'probe-heal');assert.equal(generic.battle.sides.B.roster[0].hp,target.hp);assert.ok(generic.events.some(e=>e.kind==='healBlocked'&&e.targetId==='b1'));const reapplied=resolveMove(result.battle,action('psychic-noise'),runtime(.5));assert.equal(reapplied.battle.sides.B.roster[0].volatiles['heal-block']?.endTurnTimer,2);let endBattle=structuredClone(reapplied.battle);endBattle.phase='END_TURN';let ended=resolveMechanicsEndTurn(endBattle,[],{manifests});assert.equal(ended.battle.sides.B.roster[0].volatiles['heal-block']?.endTurnTimer,1);endBattle=structuredClone(ended.battle);endBattle.phase='END_TURN';ended=resolveMechanicsEndTurn(endBattle,[],{manifests});assert.equal(ended.battle.sides.B.roster[0].volatiles['heal-block'],undefined);});


test('targeted healing reports noHealing when Psychic Noise blocks the actual HP gain',()=>{let battle=fixture('single');battle.sides.B.roster[0].hp=300;let result=resolveMove(battle,action('psychic-noise'),runtime(.5));const before=result.battle.sides.B.roster[0].hp;result=resolveMove(result.battle,action('heal-pulse',{target:{side:'B',slot:0}}),runtime(.5));assert.equal(result.battle.sides.B.roster[0].hp,before);assert.ok(result.events.some(e=>e.kind==='healBlocked'&&e.targetId==='b1'));assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noHealing'));});

test('Dragon Cheer grants +2 critical stage to Dragon allies, +1 otherwise, and conflicts with Focus Energy',()=>{let battle=fixture('double');battle.sides.A.roster[1].types=['dragon'];let result=resolveMove(battle,action('dragon-cheer',{target:{side:'A',slot:1}}),runtime(.5));assert.equal(result.battle.sides.A.roster[1].volatiles['dragon-cheer']?.criticalRatioStages,2);battle=fixture('double');result=resolveMove(battle,action('dragon-cheer',{target:{side:'A',slot:1}}),runtime(.5));assert.equal(result.battle.sides.A.roster[1].volatiles['dragon-cheer']?.criticalRatioStages,1);battle=fixture('double');battle.sides.A.roster[1].volatiles['focus-energy']={id:'focus-energy',criticalRatioStages:2};result=resolveMove(battle,action('dragon-cheer',{target:{side:'A',slot:1}}),runtime(.5));assert.equal(result.battle.sides.A.roster[1].volatiles['dragon-cheer'],undefined);assert.ok(result.events.some(e=>e.kind==='volatileFailed'&&e.reason==='conflictingCriticalState'));});

test('existing move-driven type replacement now restores original types on switch',()=>{const battle=fixture('single');battle.sides.B.roster[0].types=['fire','flying'];const result=resolveMove(battle,action('soak'),runtime(.5));assert.deepEqual(result.battle.sides.B.roster[0].types,['water']);const switched=applyMechanicsSwitch(result.battle,'B','b1','b3',{manifests});assert.deepEqual(switched.battle.sides.B.roster[0].types,['fire','flying']);});
