import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {abilityStageChange,applyMechanicsSwitch,compilePassiveEffects,createHookRegistry,createMoveActionHandler,HANDLER_DEFINITIONS,preparePersistentEffectsEndTurn} from '../mechanics-v3/index.mjs';

const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const catalog=JSON.parse(await readFile(new URL('../content-validation/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const ids=['simple-beam','baton-pass','curse','parting-shot'];
const moves=Object.fromEntries(catalog.filter(move=>ids.includes(move.id)).map(move=>[move.id,move]));
const resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry:createHookRegistry(HANDLER_DEFINITIONS)});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0});
function unit(actorId,{types=['normal'],abilityId='overgrow',moveIds=ids,hp=300}={}){return {actorId,speciesId:'venusaur',baseSpeciesId:'venusaur',types:[...types],level:50,hp,maxHp:300,stats:{hp:300,atk:120,def:100,spa:120,spd:100,spe:100},stages:stages(),status:null,volatiles:{},pp:Object.fromEntries(moveIds.map(id=>[id,20])),maxPp:Object.fromEntries(moveIds.map(id=>[id,20])),passiveEffects:abilityId&&manifests.abilities?.[abilityId]?compilePassiveEffects({abilityId,manifests}):[],activeAbilityId:abilityId,abilityState:{},itemState:null,buildSnapshot:{moveIds:[...moveIds],abilityId,itemId:null}};}
function fixture(format='single',a1={},b1={}){const n=format==='double'?2:1,a=[unit('a1',a1),unit('a2',{moveIds:[]}),unit('a3',{moveIds:[]})],b=[unit('b1',{moveIds:[],...b1}),unit('b2',{moveIds:[]}),unit('b3',{moveIds:[]})];return {id:`wave52-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:52,activeCount:n,rngState:52,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(id,extra={})=>({kind:'move',side:'A',actorId:'a1',moveId:id,target:{side:'B',slot:0},priority:0,speed:100,...extra});
const runtime={nextRandom:()=>.99,hasActed:()=>false,willMove:()=>true};
const mon=(battle,id)=>[...battle.sides.A.roster,...battle.sides.B.roster].find(unit=>unit.actorId===id);

test('r3-move-hooks-wave52:single/double promotes the state-transfer family with executable evidence',()=>{for(const id of ids){assert.equal(manifests.moves[id].reviewState,'executable',id);assert.equal(manifests.moves[id].unusable,undefined,id);assert.deepEqual(manifests.moves[id].testEvidence,{single:['r3-move-hooks-wave52:single'],double:['r3-move-hooks-wave52:double']},id);}});

test('Simple Beam installs transient Simple and doubles later stat-stage changes, then normal switch restores the original ability',()=>{let battle=fixture(),result=resolveMove(battle,action('simple-beam'),runtime),target=mon(result.battle,'b1');assert.equal(target.activeAbilityId,'simple');assert.equal(abilityStageChange(target,1).requestedDelta,2);assert.equal(abilityStageChange(target,-1).requestedDelta,-2);assert.equal(target.abilityState.transientAbility.originalAbilityId,'overgrow');const switched=applyMechanicsSwitch(result.battle,'B','b1','b3',{manifests});assert.equal(switched.ok,true);assert.equal(mon(switched.battle,'b1').activeAbilityId,'overgrow');assert.equal(mon(switched.battle,'b1').abilityState.transientAbility,undefined);});


test('Simple Beam can target an adjacent ally in Double and uses the Champions immutable-Ability block list',()=>{let battle=fixture('double');let result=resolveMove(battle,{...action('simple-beam'),target:{side:'A',slot:1}},runtime);assert.equal(mon(result.battle,'a2').activeAbilityId,'simple');result=resolveMove(fixture('double'),{...action('simple-beam'),target:{side:'B',slot:0}},runtime);assert.equal(mon(result.battle,'b1').activeAbilityId,'simple');});
test('Simple Beam fails closed against Truant and ability replacement restrictions',()=>{const result=resolveMove(fixture('single',{}, {abilityId:'truant'}),action('simple-beam'),runtime);assert.equal(mon(result.battle,'b1').activeAbilityId,'truant');assert.ok(result.events.some(event=>event.kind==='abilityChangeFailed'&&event.reason==='blockedAbility'));});

test('Baton Pass transfers the Champions whitelist but not infatuation, generic trapping, or type changes',()=>{let battle=fixture();const user=mon(battle,'a1');user.stages={atk:2,def:-1,spa:0,spd:0,spe:1,accuracy:0,evasion:0};user.volatiles.substitute={id:'substitute',hp:55};user.volatiles['aqua-ring']={id:'aqua-ring',sourceId:'aqua-ring'};user.volatiles['leech-seed']={id:'leech-seed',sourceId:'leech-seed',sourceActorId:'b1'};user.volatiles['dragon-cheer']={id:'dragon-cheer',criticalRatioStages:1};user.volatiles['target-lock']={id:'target-lock',targetActorId:'b1',alwaysHitsTarget:true};user.volatiles.telekinesis={id:'telekinesis',endTurnTimer:2};user.volatiles.trapped={id:'trapped',sourceActorId:'b1'};user.volatiles.infatuation={id:'infatuation',sourceId:'b1'};user.volatiles['type-change-state']={id:'type-change-state',originalTypes:['normal']};user.types=['fire'];const result=resolveMove(battle,action('baton-pass',{target:undefined,switchToId:'a3'}),runtime),incoming=mon(result.battle,'a3');assert.equal(result.battle.sides.A.active[0],'a3');assert.equal(incoming.stages.atk,2);assert.equal(incoming.stages.def,-1);assert.equal(incoming.volatiles.substitute.hp,55);assert.ok(incoming.volatiles['aqua-ring']);assert.ok(incoming.volatiles['leech-seed']);assert.ok(incoming.volatiles['dragon-cheer']);assert.equal(incoming.volatiles['target-lock'].targetActorId,'b1');assert.ok(incoming.volatiles.telekinesis);assert.equal(incoming.volatiles.trapped,undefined);assert.equal(incoming.volatiles.infatuation,undefined);assert.equal(incoming.volatiles['type-change-state'],undefined);assert.deepEqual(incoming.types,['normal']);});

test('Baton Pass re-applies Power Trick against the incoming stats instead of copying outgoing raw stats',()=>{let battle=fixture();const user=mon(battle,'a1');user.stats.atk=100;user.stats.def=180;user.volatiles['power-trick']={id:'power-trick'};user.volatiles['stored-stat-overrides']={id:'stored-stat-overrides',originalStats:{atk:180,def:100}};const reserve=mon(battle,'a3');reserve.stats.atk=90;reserve.stats.def=140;const result=resolveMove(battle,action('baton-pass',{target:undefined,switchToId:'a3'}),runtime),incoming=mon(result.battle,'a3');assert.equal(incoming.stats.atk,140);assert.equal(incoming.stats.def,90);assert.deepEqual(incoming.volatiles['stored-stat-overrides'].originalStats,{atk:90,def:140});});

test('Curse branches by current type: non-Ghost boosts self while Ghost curses the selected foe and pays half max HP',()=>{let result=resolveMove(fixture(),action('curse',{target:undefined}),runtime),user=mon(result.battle,'a1');assert.equal(user.stages.atk,1);assert.equal(user.stages.def,1);assert.equal(user.stages.spe,-1);result=resolveMove(fixture('single',{types:['ghost']}),action('curse'),runtime);user=mon(result.battle,'a1');const target=mon(result.battle,'b1');assert.equal(user.hp,150);assert.equal(target.volatiles.curse.sourceActorId,'a1');const persistent=preparePersistentEffectsEndTurn(result.battle),group=persistent.groups.find(entry=>entry.id==='curse-residual');assert.deepEqual(group.changes,[{actorId:'b1',delta:-75}]);});

test('Ghost Curse in Double respects the selected opponent slot',()=>{const result=resolveMove(fixture('double',{types:['ghost']}),action('curse',{target:{side:'B',slot:1}}),runtime);assert.equal(mon(result.battle,'b1').volatiles.curse,undefined);assert.equal(mon(result.battle,'b2').volatiles.curse.sourceActorId,'a1');});

test('Ghost Curse can target an adjacent ally in Double under Champions targeting',()=>{const result=resolveMove(fixture('double',{types:['ghost']}),action('curse',{target:{side:'A',slot:1}}),runtime);assert.equal(mon(result.battle,'a1').hp,150);assert.equal(mon(result.battle,'a2').volatiles.curse.sourceActorId,'a1');});

test('Parting Shot lowers both stats then switches the user; stage immunity prevents the switch',()=>{let result=resolveMove(fixture(),action('parting-shot',{switchToId:'a3'}),runtime);assert.equal(mon(result.battle,'b1').stages.atk,-1);assert.equal(mon(result.battle,'b1').stages.spa,-1);assert.equal(result.battle.sides.A.active[0],'a3');result=resolveMove(fixture('single',{}, {abilityId:'clear-body'}),action('parting-shot',{switchToId:'a3'}),runtime);assert.equal(result.battle.sides.A.active[0],'a1');assert.equal(mon(result.battle,'b1').stages.atk,0);});

test('Parting Shot can target an adjacent ally in Double and still pivots the user',()=>{const result=resolveMove(fixture('double'),action('parting-shot',{target:{side:'A',slot:1},switchToId:'a3'}),runtime);assert.equal(mon(result.battle,'a2').stages.atk,-1);assert.equal(mon(result.battle,'a2').stages.spa,-1);assert.equal(result.battle.sides.A.active[0],'a3');});

test('Parting Shot handles Mirror Armor and Magic Bounce switch ownership',()=>{let result=resolveMove(fixture('single',{}, {abilityId:'mirror-armor'}),action('parting-shot',{switchToId:'a3'}),runtime);assert.equal(result.battle.sides.A.active[0],'a3');assert.equal(mon(result.battle,'b1').stages.atk,0);assert.equal(mon(result.battle,'a1').stages.atk,0,'switched user stages reset after reflected drop');result=resolveMove(fixture('single',{}, {abilityId:'magic-bounce'}),action('parting-shot',{switchToId:'a3'}),runtime);assert.equal(result.battle.sides.A.active[0],'a1');assert.equal(mon(result.battle,'a1').stages.atk,-1);assert.ok(result.battle.forcedReplacements?.B?.some(entry=>entry.actorId==='b1'));assert.ok(result.events.some(event=>event.kind==='forcedReplacementRequested'&&event.actorId==='b1'));});
