import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {compilePassiveEffects,createHeldItemState,createHookRegistry,createMoveActionHandler,createMoveChoiceValidator,HANDLER_DEFINITIONS,resolveMechanicsEndTurn,typeEffectivenessWithHeldItems,unitIsGrounded} from '../mechanics-v3/index.mjs';

const catalog=JSON.parse(await readFile(new URL('../content-candidates/pv-ma-2026-09-12-beta2/normalized/moves.json',import.meta.url),'utf8'));
const manifests=JSON.parse(await readFile(new URL('../content-src/mechanics-v3-manifests.json',import.meta.url),'utf8'));
const ids=['autotomize','gravity','fly','magnet-rise','grav-apple','hypnosis','earthquake','tackle'],byId=Object.fromEntries(catalog.map(move=>[move.id,move])),moves=Object.fromEntries(ids.map(id=>[id,byId[id]]));
const registry=createHookRegistry(HANDLER_DEFINITIONS),resolveMove=createMoveActionHandler({moves,manifests:manifests.moves,abilityManifests:manifests,registry}),validateAction=createMoveChoiceValidator({moves,manifests:manifests.moves});
const stages=()=>({atk:0,def:0,spa:0,spd:0,spe:0,accuracy:0,evasion:0}),pp=()=>Object.fromEntries(ids.map(id=>[id,20]));
const unit=(actorId,overrides={})=>({actorId,speciesId:actorId,types:['normal'],hp:1800,maxHp:1800,stats:{hp:1800,atk:180,def:180,spa:180,spd:180,spe:100},pp:pp(),maxPp:pp(),status:null,volatiles:{},stages:stages(),passiveEffects:[],abilityState:{},buildSnapshot:{abilityId:null,itemId:null,moveIds:ids},itemState:createHeldItemState(null),...overrides});
function fixture(format='single'){const n=format==='double'?2:1,a=[unit('a1'),unit('a2'),unit('a3')],b=[unit('b1'),unit('b2'),unit('b3')];return {id:`wave42-${format}`,format,level:50,phase:'RESOLVE',phaseRevision:1,turn:50,activeCount:n,rngState:42,eventSequence:0,events:[],result:null,field:{},sides:{A:{active:a.slice(0,n).map(x=>x.actorId),roster:a,conditions:{}},B:{active:b.slice(0,n).map(x=>x.actorId),roster:b,conditions:{}}}};}
const action=(moveId,{side='A',actorId='a1',target=null}={})=>({kind:'move',side,actorId,moveId,target:target??(manifests.moves[moveId]?.targetMode==='self'?{side,slot:0}:manifests.moves[moveId]?.targetMode==='field'?null:{side:side==='A'?'B':'A',slot:0}),moveType:byId[moveId].type,moveCategory:byId[moveId].category,priority:manifests.moves[moveId]?.priority??0,speed:100});
const runtime=value=>({nextRandom:()=>value,hasActed:()=>false,willMove:()=>true});
const setAbility=(target,id)=>{target.activeAbilityId=id;target.buildSnapshot.abilityId=id;target.passiveEffects=compilePassiveEffects({abilityId:id,itemId:null,manifests});};
const evidence={single:['r3-move-hooks-wave42:single'],double:['r3-move-hooks-wave42:double']};

test('r3-move-hooks-wave42:single/double promotes Autotomize and Gravity with evidence',()=>{for(const id of ['autotomize','gravity'])assert.deepEqual(manifests.moves[id].testEvidence,evidence,id);});

test('Autotomize raises Speed, accumulates switch-cleared weight reduction, respects Contrary, and fails cleanly at the stage limit',()=>{let battle=fixture();let result=resolveMove(battle,action('autotomize'),runtime(.5));let actor=result.battle.sides.A.roster[0];assert.equal(actor.stages.spe,2);assert.equal(actor.volatiles['weight-reduction']?.reductionHg,1000);result=resolveMove(result.battle,action('autotomize'),runtime(.5));actor=result.battle.sides.A.roster[0];assert.equal(actor.stages.spe,4);assert.equal(actor.volatiles['weight-reduction']?.reductionHg,2000);
 battle=fixture();battle.sides.A.roster[0].stages.spe=6;result=resolveMove(battle,action('autotomize'),runtime(.5));actor=result.battle.sides.A.roster[0];assert.equal(actor.volatiles['weight-reduction'],undefined);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='noStatChange'));
 battle=fixture();setAbility(battle.sides.A.roster[0],'contrary');result=resolveMove(battle,action('autotomize'),runtime(.5));actor=result.battle.sides.A.roster[0];assert.equal(actor.stages.spe,-2);assert.equal(actor.volatiles['weight-reduction']?.reductionHg,1000);});

test('Gravity starts for five turns, grounds airborne targets, aborts airborne charge states, blocks gravity-forbidden choices, and cannot refresh itself',()=>{let battle=fixture('double');const flying=battle.sides.B.roster[0],charging=battle.sides.B.roster[1];flying.types=['flying'];setAbility(flying,'levitate');flying.volatiles['magnet-rise']={id:'magnet-rise',endTurnTimer:5};charging.volatiles['two-turn-move']={id:'two-turn-move',moveId:'fly',semiInvulnerable:'airborne'};
 let result=resolveMove(battle,action('gravity'),runtime(.5));battle=result.battle;assert.equal(battle.field.gravity?.remaining,5);const liveFlying=battle.sides.B.roster[0],liveCharging=battle.sides.B.roster[1];assert.equal(liveFlying.volatiles['magnet-rise'],undefined);assert.equal(liveCharging.volatiles['two-turn-move'],undefined);assert.equal(unitIsGrounded(liveFlying,battle),true);assert.equal(typeEffectivenessWithHeldItems('ground',liveFlying,battle),1);assert.equal(validateAction(battle,action('fly')).code,'GRAVITY_MOVE_BLOCKED');assert.equal(validateAction(battle,action('magnet-rise')).code,'GRAVITY_MOVE_BLOCKED');
 result=resolveMove(battle,action('gravity'),runtime(.5));assert.equal(result.battle.field.gravity?.remaining,5);assert.ok(result.events.some(e=>e.kind==='moveFailed'&&e.reason==='gravityAlreadyActive'));
 for(let i=0;i<5;i++){battle=result.battle;battle.phase='END_TURN';result=resolveMechanicsEndTurn(battle,[],{manifests});}assert.equal(result.battle.field.gravity,undefined);assert.ok(result.events.some(e=>e.kind==='fieldConditionEnded'&&e.condition==='gravity'));});

test('Gravity applies its accuracy multiplier and Grav Apple power modifier without changing their base catalog data',()=>{let battle=fixture();let missed=resolveMove(battle,action('hypnosis'),runtime(.8));assert.equal(missed.battle.sides.B.roster[0].status,null);assert.ok(missed.events.some(e=>e.kind==='moveMissed'));
 battle=fixture();battle.field.gravity={id:'gravity',remaining:5};let hit=resolveMove(battle,action('hypnosis'),runtime(.8));assert.equal(hit.battle.sides.B.roster[0].status?.id??hit.battle.sides.B.roster[0].status,'sleep');
 const plain=resolveMove(fixture(),action('grav-apple'),runtime(.5)),gravityBattle=fixture();gravityBattle.field.gravity={id:'gravity',remaining:5};const boosted=resolveMove(gravityBattle,action('grav-apple'),runtime(.5));const plainDamage=plain.events.find(e=>e.kind==='damage'&&e.moveId==='grav-apple')?.amount,boostedDamage=boosted.events.find(e=>e.kind==='damage'&&e.moveId==='grav-apple')?.amount;assert.ok(boostedDamage>plainDamage);assert.ok(boosted.events.some(e=>e.kind==='movePowerChanged'&&e.moveId==='grav-apple'&&e.fromPower===90&&e.toPower===135));assert.equal(byId['grav-apple'].power,90);});
