import test from 'node:test';
import assert from 'node:assert/strict';
import {applyDamageHit} from '../mechanics-v3/index.mjs';
import {applyV3BattleAction} from '../server/v3-battle-actions.mjs';
import {createV3BattleUnit} from '../server/v3-battle-factory.mjs';
import {v3Catalog} from '../server/v3-catalog.mjs';
import {applyMegaEvolution,validateMegaChoice} from '../server/v3-mega.mjs';
import {createV3BetaProgression} from '../server/v3-progression.mjs';

function progression(){const value=createV3BetaProgression(v3Catalog),build=value.builds.find(entry=>entry.monId==='v3-mon-venusaur');build.itemId='venusaurite';return value;}
function open(mode){let state={schemaVersion:3,seed:919,progressionV3:progression()},result=applyV3BattleAction(state,{type:'battleV3.preview.start',mode,difficulty:'normal'},v3Catalog);assert.equal(result.ok,true);state=result.state;const count=v3Catalog.regulations[0].pick[mode],ids=state.battleV3.playerRoster.slice(0,count).map(entry=>entry.buildId);result=applyV3BattleAction(state,{type:'battleV3.preview.lock',buildIds:ids},v3Catalog);assert.equal(result.ok,true);return result.state;}
function commands(battle,mega=false){return battle.sides.A.active.map((actorId,index)=>{const unit=battle.sides.A.roster.find(entry=>entry.actorId===actorId),moveId=unit.buildSnapshot.moveIds.find(id=>id!=='protect'&&!v3Catalog.movesById[id].mechanics.handlers.some(handler=>handler.id==='apply-pivot-switch')),move=v3Catalog.movesById[moveId],automatic=['self','userSide','field','allAdjacentFoes','allAdjacent','foeSide'].includes(move.mechanics.targetMode);return {kind:'move',actorId,moveId,...(mega&&unit.baseSpeciesId==='venusaur'?{mega:true}:{}),...(automatic?{}:{target:{side:'B',slot:Math.min(index,battle.activeCount-1)}})};});}

for(const mode of ['single','double'])test(`R6 Mega Venusaur resolves before moves in ${mode}`,()=>{const state=open(mode),battle=state.battleV3.battle,result=applyV3BattleAction(state,{type:'battleV3.commands',phaseRevision:battle.phaseRevision,commands:commands(battle,true)},v3Catalog);assert.equal(result.ok,true);const events=result.state.battleV3.lastEvents,megaIndex=events.findIndex(event=>event.kind==='megaEvolved'&&event.actorId==='A-0'),actionIndex=events.findIndex(event=>(event.kind==='moveStarted'||event.kind==='actionCancelled')&&event.actorId==='A-0'),unit=result.state.battleV3.battle.sides.A.roster[0];assert.ok(megaIndex>=0&&megaIndex<actionIndex);assert.equal(unit.speciesId,'venusaur-mega');assert.equal(unit.weightKg,155.5);assert.equal(unit.activeAbilityId,'thick-fat');assert.equal(unit.stats.def,143);assert.equal(unit.megaEvolved,true);assert.equal(result.state.battleV3.battle.megaUsed.A,1);});

test('R6 Mega keeps damage, PP, status, stages and volatiles while recalculating the form',()=>{const state=open('single'),battle=structuredClone(state.battleV3.battle),unit=battle.sides.A.roster[0],pp=unit.pp['giga-drain'];unit.hp-=31;unit.status={id:'paralysis'};unit.stages.spa=2;unit.volatiles.confusion={timer:2};const result=applyMegaEvolution(battle,{side:'A',actorId:unit.actorId},v3Catalog),mega=result.battle.sides.A.roster[0];assert.equal(mega.maxHp-mega.hp,31);assert.equal(mega.pp['giga-drain'],pp);assert.deepEqual(mega.status,{id:'paralysis'});assert.equal(mega.stages.spa,2);assert.deepEqual(mega.volatiles.confusion,{timer:2});});

test('R6 legality rejects a missing stone and a second Mega on the same side',()=>{const state=open('single'),battle=state.battleV3.battle,unit=battle.sides.A.roster[0];unit.buildSnapshot.itemId='miracle-seed';assert.equal(validateMegaChoice(battle,{mega:true,side:'A',actorId:unit.actorId},v3Catalog).code,'MEGA_NOT_ELIGIBLE');unit.buildSnapshot.itemId='venusaurite';battle.megaUsed.A=1;assert.equal(validateMegaChoice(battle,{mega:true,side:'A',actorId:unit.actorId},v3Catalog).code,'MEGA_LIMIT_REACHED');});

test('R6 Thick Fat halves incoming Fire and Ice damage after Mega Evolution',()=>{const state=open('single'),base=state.battleV3.battle,mega=applyMegaEvolution(base,{side:'A',actorId:'A-0'},v3Catalog).battle,attacker=mega.sides.B.roster[0],target=mega.sides.A.roster[0],move={id:'test-fire',type:'fire',category:'special',power:80},runtime={nextRandom:()=>.999};attacker.types=['fire'];attacker.stats.spa=120;const thick=applyDamageHit(mega,{actorId:attacker.actorId,targetId:target.actorId,move},runtime).events[0],without=structuredClone(mega);without.sides.A.roster[0].passiveEffects=[];const normal=applyDamageHit(without,{actorId:attacker.actorId,targetId:target.actorId,move},runtime).events[0];assert.equal(thick.breakdown.passiveModifiers.at(-1).sourceId,'thick-fat');assert.equal(thick.breakdown.passiveModifiers.at(-1).multiplier,.5);assert.ok(thick.amount<normal.amount);});

test('R6 battle unit exposes base identity separately from its active form',()=>{const value=progression(),build=value.builds[0],mon=value.mons[0],unit=createV3BattleUnit('A',0,build,mon,v3Catalog);assert.equal(unit.baseSpeciesId,'venusaur');assert.equal(unit.speciesId,'venusaur');assert.equal(unit.activeAbilityId,'overgrow');assert.equal(unit.weightKg,100);assert.ok(['male','female'].includes(unit.gender));});


