import { SELF } from 'cloudflare:test';
import {describe,it,expect} from 'vitest';
import {setup as rawSetup,validateAction,applyAction,viewFor} from '../src/logic.js';
const setup=(players:string[]):any=>rawSetup(players);
const player='test-owner';
function act(s:any,a:any):any{expect(validateAction(s,player,a).ok).toBe(true);return applyAction(s,player,a);}
function commands(s:any){const b=s.battle;return b.allies.map((m:any,i:number)=>({m,i})).filter((x:any)=>x.m.hp>0&&x.m.slot>=0).map((x:any)=>({kind:'move',actor:x.i,move:0,target:b.enemies.findIndex((m:any)=>m.hp>0&&m.slot>=0)}));}
describe('monster battle rules',()=>{
 it('provides 36 distinct species with four moves and dual types',()=>{const v:any=viewFor(setup([player]),player);expect(v.catalog).toHaveLength(36);expect(new Set(v.catalog.map((d:any)=>d.name)).size).toBe(36);v.catalog.forEach((d:any)=>{expect(d.moves).toHaveLength(4);expect(d.types).toHaveLength(2);expect(d.ability.desc.length).toBeGreaterThan(10);});});
 it('rejects hostile and out of phase actions',()=>{const s=setup([player]);for(const a of [null,{}, {type:'summon',count:-1},{type:'team',ids:[0,0]}, {type:'gym'}, {type:'battle',mode:'single',gym:5},{type:'equip',id:0,item:100}])expect(validateAction(s,player,a).ok).toBe(false);expect(validateAction(s,'intruder',{type:'claim',id:0}).ok).toBe(false);});
 it('pays mailbox rewards exactly once',()=>{const s=setup([player]);const n=act(s,{type:'claim',id:0});expect(n.gems).toBe(s.gems+500);expect(validateAction(n,player,{type:'claim',id:0}).ok).toBe(false);expect(s.mail).toEqual([]);});
 it('trains and equips with correct costs',()=>{let s=setup([player]);s=act(s,{type:'train',id:0});expect(s.coins).toBe(2250);expect(s.collection[0].level).toBe(6);s=act(s,{type:'equip',id:0,item:6});expect(s.collection[0].item).toBe(6);});
 it('applies type immunities and strengths',()=>{const v:any=viewFor(setup([player]),player);const at=(a:string,b:string)=>v.typeChart[v.types.indexOf(a)][v.types.indexOf(b)];expect(at('Flame','Bloom')).toBe(2);expect(at('Volt','Stone')).toBe(0);expect(at('Venom','Steel')).toBe(0);expect(at('Tide','Tide')).toBe(.5);});
 it('preserves seeded deterministic summoning, pity and unique ownership',()=>{const s=setup([player]);expect(act(s,{type:'summon',count:10})).toEqual(act(s,{type:'summon',count:10}));let n=act(s,{type:'summon',count:10});expect(n.gems).toBe(800);expect(n.reveal).toHaveLength(10);expect(['Epic','Legendary']).toContain((viewFor(n,player) as any).catalog[n.reveal[9].id].rarity);n.pity=49;n=act(n,{type:'summon',count:1});expect((viewFor(n,player) as any).catalog[n.reveal[0].id].rarity).toBe('Legendary');expect(n.pity).toBe(0);expect(new Set(n.collection.map((m:any)=>m.id)).size).toBe(n.collection.length);});
 for(const mode of ['single','double'])it('completes '+mode+' battles and rejects duplicate turns',()=>{let s=act(setup([player]),{type:'battle',mode});expect(s.battle.allies.filter((m:any)=>m.slot>=0)).toHaveLength(mode==='single'?1:2);let steps=0;while(!s.battle.result&&steps++<81){let a={type:'turn',round:s.battle.round,commands:commands(s)};const original=JSON.stringify(s);let n=act(s,a);expect(JSON.stringify(s)).toBe(original);expect(validateAction(n,player,a).ok).toBe(false);s=n;for(const m of [...s.battle.allies,...s.battle.enemies]){expect(m.hp).toBeGreaterThanOrEqual(0);expect(m.hp).toBeLessThanOrEqual(m.max);expect(m.energy).toBeGreaterThanOrEqual(0);expect(m.energy).toBeLessThanOrEqual(5);}}expect(s.battle.result).toBeTruthy();expect(s.battle.reward.coins).toBeGreaterThan(0);});
 it('switches reserves and validates double commands',()=>{let s=act(setup([player]),{type:'battle',mode:'double'});expect(validateAction(s,player,{type:'turn',round:1,commands:[commands(s)[0]]}).ok).toBe(false);let c=commands(s);c[0]={kind:'switch',actor:0,to:2} as any;s=act(s,{type:'turn',round:1,commands:c});expect(s.battle.allies[0].slot).toBe(-1);expect(s.battle.log.some((l:string)=>l.includes('switched'))).toBe(true);});
 it('applies held item defense and attack effects',()=>{let s=act(setup([player]),{type:'battle',mode:'single'});s.battle.weather='Clear';s.battle.weatherTurns=0;s.battle.enemies[0].max=10000;s.battle.enemies[0].hp=10000;const run=(item:number)=>{let t=JSON.parse(JSON.stringify(s));t.battle.allies[0].item=item;return act(t,{type:'turn',round:1,commands:commands(t)});};expect(run(2).battle.enemies[0].hp).toBeLessThan(run(0).battle.enemies[0].hp);expect(run(3).battle.allies[0].hp).toBeGreaterThan(run(0).battle.allies[0].hp);});
});
async function open(room:string,p:string){const res=await SELF.fetch('https://test/ws/'+room,{headers:{Upgrade:'websocket'}});expect(res.status).toBe(101);const ws=res.webSocket!;ws.accept();const frames:any[]=[];ws.addEventListener('message',e=>{if(e.data==='__pong')return;try{frames.push(JSON.parse(String(e.data)));}catch{}});ws.send(JSON.stringify({type:'join',playerId:p}));async function wait(predicate:(m:any)=>boolean){for(let i=0;i<150;i++){const f=frames.find(predicate);if(f)return f;await scheduler.wait(10);}throw new Error('Frame timeout: '+JSON.stringify(frames));}return {ws,frames,wait};}
describe('live room protocol',()=>{
 it('persists a claim across reconnect and blocks spectators',async()=>{const room='aether-persist-'+crypto.randomUUID();const a=await open(room,player);const initial=await a.wait(m=>m.type==='state'&&m.view?.gems);expect(initial.view.gems).toBe(1800);a.ws.send(JSON.stringify({type:'action',action:{type:'claim',id:0}}));await a.wait(m=>m.view?.gems===2300);a.ws.close();const again=await open(room,player);const restored=await again.wait(m=>m.type==='state');expect(restored.view.gems).toBe(2300);const spectator=await open(room,'other');const sv=await spectator.wait(m=>m.type==='state');expect(sv.view.spectator).toBe(true);spectator.ws.send(JSON.stringify({type:'action',action:{type:'claim',id:0}}));const err=await spectator.wait(m=>m.type==='error');expect(err.error).toMatch(/spectator/);again.ws.close();spectator.ws.close();});
 it('rejects malformed websocket frames',async()=>{const a=await open('malformed-'+crypto.randomUUID(),player);await a.wait(m=>m.type==='state');a.ws.send('not json');const err=await a.wait(m=>m.type==='error');expect(err.error).toBe('invalid json');a.ws.close();});
});
