import test from 'node:test';
import assert from 'node:assert/strict';
import {v3Catalog} from '../server/v3-catalog.mjs';
import {createV3BetaProgression} from '../server/v3-progression.mjs';
import {applyV3BattleAction} from '../server/v3-battle-actions.mjs';
import {v3BattleView} from '../server/v3-battle-view.mjs';

const initial=()=>({schemaVersion:3,seed:719,progressionV3:createV3BetaProgression(v3Catalog)});
function open(mode){let state=initial(),result=applyV3BattleAction(state,{type:'battleV3.preview.start',mode,difficulty:'normal'},v3Catalog);assert.equal(result.ok,true);state=result.state;const count=v3Catalog.regulations[0].pick[mode],ids=state.battleV3.playerRoster.slice(0,count).map(entry=>entry.buildId);result=applyV3BattleAction(state,{type:'battleV3.preview.lock',buildIds:ids},v3Catalog);assert.equal(result.ok,true);return result.state;}
function playerCommands(battle){return battle.sides.A.active.map((actorId,index)=>{const unit=battle.sides.A.roster.find(entry=>entry.actorId===actorId),move=unit.buildSnapshot.moveIds.map(id=>v3Catalog.movesById[id]).find(entry=>!entry.mechanics.handlers.some(handler=>handler.id==='apply-pivot-switch')),self=['self','userSide','field'].includes(move.mechanics.targetMode);return {kind:'move',actorId,moveId:move.id,...(self?{}:{target:{side:'B',slot:Math.min(index,battle.activeCount-1)}})};});}
function replacements(battle){const active=new Set(battle.sides.A.active),reserves=battle.sides.A.roster.filter(unit=>unit.hp>0&&!active.has(unit.actorId));return battle.sides.A.active.map((actorId,slot)=>({actorId,slot})).filter(entry=>!entry.actorId||battle.sides.A.roster.find(unit=>unit.actorId===entry.actorId)?.hp<=0).slice(0,reserves.length).map((entry,index)=>({slot:entry.slot,actorId:reserves[index].actorId}));}

test('schema-3 preview pins immutable stats, PP and passive effects for Single',()=>{const state=open('single'),battle=state.battleV3.battle,unit=battle.sides.A.roster[0],build=state.progressionV3.builds[0];assert.equal(battle.phase,'COMMAND');assert.equal(battle.sides.A.roster.length,3);assert.equal(unit.pp[build.moveIds[0]],v3Catalog.movesById[build.moveIds[0]].maxPP);assert.deepEqual(unit.passiveEffects.map(entry=>entry.sourceId),[build.abilityId,build.itemId]);build.statPoints.hp=32;assert.notEqual(unit.buildSnapshot.statPoints.hp,32);});

test('schema-3 authoritative Single resolves player and projected AI commands',()=>{let state=open('single'),battle=state.battleV3.battle;const result=applyV3BattleAction(state,{type:'battleV3.commands',phaseRevision:battle.phaseRevision,commands:playerCommands(battle)},v3Catalog);assert.equal(result.ok,true);state=result.state;assert.ok(['COMMAND','REPLACE','FINISHED'].includes(state.battleV3.battle.phase));assert.equal(state.battleV3.lastEvents.some(event=>event.kind==='moveStarted'),true);const view=v3BattleView(state),enemyDamage=view.events.find(event=>event.kind==='damage'&&event.targetId?.startsWith('B-'));assert.equal(view.snapshot.opponent[0].buildSnapshot,undefined);assert.equal(view.snapshot.own[0].buildSnapshot.moveIds.length,4);assert.equal(enemyDamage?.amount,undefined);assert.equal(enemyDamage?.breakdown,undefined);});

test('schema-3 Double requires four picks, starts two leads and resolves a full turn',()=>{let state=open('double'),battle=state.battleV3.battle;assert.equal(battle.sides.A.roster.length,4);assert.equal(battle.sides.A.active.length,2);const stale=applyV3BattleAction(state,{type:'battleV3.commands',phaseRevision:battle.phaseRevision-1,commands:playerCommands(battle)},v3Catalog);assert.equal(stale.code,'STALE_PHASE');const result=applyV3BattleAction(state,{type:'battleV3.commands',phaseRevision:battle.phaseRevision,commands:playerCommands(battle)},v3Catalog);assert.equal(result.ok,true);assert.equal(result.state.battleV3.lastEvents.filter(event=>event.kind==='turnStarted').length,1);});

test('schema-3 battle rejects forged moves and invalid preview lineups',()=>{let state=initial(),start=applyV3BattleAction(state,{type:'battleV3.preview.start',mode:'single'},v3Catalog);state=start.state;assert.equal(applyV3BattleAction(state,{type:'battleV3.preview.lock',buildIds:['missing','x','y']},v3Catalog).code,'INVALID_PREVIEW_SELECTION');state=open('single');const battle=state.battleV3.battle,result=applyV3BattleAction(state,{type:'battleV3.commands',phaseRevision:battle.phaseRevision,commands:[{kind:'move',actorId:'A-0',moveId:'not-a-move'}]},v3Catalog);assert.equal(result.code,'INVALID_MOVE');});

for(const mode of ['single','double'])test(`schema-3 ${mode} beta match reaches a deterministic result`,()=>{let state=open(mode),turns=0;while(state.battleV3.battle.phase!=='FINISHED'&&turns++<100){const battle=state.battleV3.battle,action=battle.phase==='COMMAND'?{type:'battleV3.commands',phaseRevision:battle.phaseRevision,commands:playerCommands(battle)}:{type:'battleV3.replacements',phaseRevision:battle.phaseRevision,replacements:replacements(battle)},first=applyV3BattleAction(state,action,v3Catalog),second=applyV3BattleAction(structuredClone(state),action,v3Catalog);assert.equal(first.ok,true);assert.deepEqual(first,second);state=first.state;}assert.ok(turns<100);assert.ok(['A','B',null].includes(state.battleV3.battle.result.winner));});
