import test from 'node:test';
import assert from 'node:assert/strict';
import {v3Catalog} from '../server/v3-catalog.mjs';
import {createV3BetaProgression,applyV3ProgressionAction} from '../server/v3-progression.mjs';
import {applyV3RecruitmentAction} from '../server/v3-recruitment.mjs';
import {prepareV3RecruitmentState,v3RecruitmentView} from '../server/v3-recruitment-state.mjs';

const makeState=()=>({schemaVersion:3,seed:77,coins:5000,gems:0,recruitmentTickets:1,progressionV3:createV3BetaProgression(v3Catalog)});

test('schema-3 Roster Ranch rolls ten stable unique offers and refreshes idempotently',()=>{const state=makeState();prepareV3RecruitmentState(state,v3Catalog,100000000);const first=v3RecruitmentView(state,v3Catalog,{serverNow:100000000});assert.equal(first.offers.length,10);assert.equal(new Set(first.offers.map(offer=>offer.speciesId)).size,10);prepareV3RecruitmentState(state,v3Catalog,100000010);assert.deepEqual(v3RecruitmentView(state,v3Catalog,{serverNow:100000010}).offers.map(offer=>offer.speciesId),first.offers.map(offer=>offer.speciesId));const action={type:'recruitV3.refresh',actionId:'v3-refresh-1',expectedRevision:first.revision,cycleId:first.cycleId},result=applyV3RecruitmentAction(state,action,v3Catalog,{serverNow:100000010});assert.equal(result.ok,true);assert.equal(result.state.wallet.coins,4650);const duplicate=applyV3RecruitmentAction(result.state,action,v3Catalog,{serverNow:100000020});assert.equal(duplicate.ok,true);assert.equal(duplicate.duplicate,true);assert.equal(duplicate.state.wallet.coins,4650);});

test('schema-3 Trial keeps identity when permanently recruited and is read-only while temporary',()=>{let state=makeState();prepareV3RecruitmentState(state,v3Catalog,200000000);const view=v3RecruitmentView(state,v3Catalog,{serverNow:200000000}),offer=view.offers.find(entry=>entry.ownership==='locked');let result=applyV3RecruitmentAction(state,{type:'recruitV3.trial',actionId:'v3-trial-1',expectedRevision:view.revision,cycleId:view.cycleId,speciesId:offer.speciesId},v3Catalog,{serverNow:200000000});assert.equal(result.ok,true);state=result.state;const trialMon=state.progressionV3.mons.find(mon=>mon.speciesId===offer.speciesId),trialBuild=state.progressionV3.builds.find(build=>build.monId===trialMon.monId);assert.equal(applyV3ProgressionAction(state.progressionV3,{type:'buildV3.save',expectedRevision:trialBuild.revision,build:trialBuild},v3Catalog).code,'TRIAL_READ_ONLY');result=applyV3RecruitmentAction(state,{type:'recruitV3.permanent',actionId:'v3-buy-1',speciesId:offer.speciesId,payment:'ticket'},v3Catalog,{serverNow:200000100});assert.equal(result.ok,true);const permanent=result.state.progressionV3.mons.find(mon=>mon.speciesId===offer.speciesId),build=result.state.progressionV3.builds.find(entry=>entry.monId===permanent.monId);assert.equal(permanent.ownership,'permanent');assert.equal(permanent.monId,trialMon.monId);assert.equal(build.buildId,trialBuild.buildId);assert.equal(result.state.wallet.recruitmentTickets,0);});
