import { createHash } from 'node:crypto';
import { readFile, writeFile, rename, unlink, mkdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const defaultRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const normalize = source => source.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n').replace(/\s+$/u, '') + '\n';

export async function buildLogic(root = defaultRoot) {
  const sourceDir = path.join(root, 'logic-src');
  const manifestPath = path.join(sourceDir, 'manifest.json');
  let manifest;
  try { manifest = JSON.parse(await readFile(manifestPath, 'utf8')); }
  catch (error) { throw new Error(`Cannot read logic-src/manifest.json: ${error.message}`); }
  if (manifest?.formatVersion !== 1 || !Array.isArray(manifest.fragments) || !manifest.fragments.length) {
    throw new Error('logic-src/manifest.json must declare formatVersion 1 and a non-empty fragments array');
  }
  if (new Set(manifest.fragments).size !== manifest.fragments.length) throw new Error('logic fragment names must be unique');

  const parts = [];
  for (const name of manifest.fragments) {
    if (typeof name !== 'string' || !/^[0-9]{2}-[a-z0-9-]+\.js$/.test(name)) throw new Error(`Invalid logic fragment name: ${String(name)}`);
    const fullPath = path.resolve(sourceDir, name);
    if (path.dirname(fullPath) !== sourceDir) throw new Error(`Logic fragment escapes logic-src: ${name}`);
    parts.push({ name, source:normalize(await readFile(fullPath, 'utf8')) });
  }

  const body = parts.map(part => `// ---- ${part.name} ----\n${part.source}`).join('\n');
  const hash = createHash('sha256').update(body).digest('hex');
  return `// GENERATED by scripts/compile-logic.mjs from logic-src/manifest.json.\n// Source hash: ${hash}\n// Do not edit this file directly; edit logic-src fragments and run npm run compile:logic.\n\n${body}`;
}

export async function compileLogic({ root = defaultRoot, verify = false } = {}) {
  const expected = await buildLogic(root);
  const target = path.join(root, 'src', 'logic.js');
  if (verify) {
    let actual;
    try { actual = await readFile(target, 'utf8'); }
    catch (error) { throw new Error(`Cannot verify src/logic.js: ${error.message}`); }
    if (normalize(actual) !== normalize(expected)) throw new Error('src/logic.js is stale; run npm run compile:logic');
    return { changed:false, target };
  }

  let current = '';
  try { current = await readFile(target, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (normalize(current) === normalize(expected)) return { changed:false, target };

  await mkdir(path.dirname(target), { recursive:true });
  const temporary = path.join(path.dirname(target), '.logic.generated.mjs');
  await writeFile(temporary, expected, 'utf8');
  const checked = spawnSync(process.execPath, ['--check', temporary], { encoding:'utf8' });
  if (checked.status !== 0) {
    await unlink(temporary).catch(() => {});
    throw new Error(`Generated logic failed syntax validation:\n${(checked.stderr || checked.stdout).trim()}`);
  }
  await rename(temporary, target);
  return { changed:true, target };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const result = await compileLogic({ verify:process.argv.includes('--verify') });
    console.log(result.changed ? 'logic compiled — src/logic.js updated' : 'logic compiled — already current');
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}

